Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2019-04, with the labels that each got.

#18 fix zap logging
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: size/XS

#22 Document configuration policy in the HCO
  docs/config.md
Labels: size/M

#25 upgrade used cluster network addons operator version to v0.3.0
  Gopkg.lock
  Gopkg.toml
  hack/config
  hack/defaults
  hack/operator-test.sh
  pkg/cnacomponents/cnacomponents.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  tools/manifest-templator/manifest-templator.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/cmd/manager/main.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/components/components.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/controller/networkaddonsconfig/controller.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/controller/networkaddonsconfig/pod_controller.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/controller/networkaddonsconfig/previous.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/controller/statusmanager/status_manager.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/names/names.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/network/cluster-info.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/network/cni/cni.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/network/image-pull-policy.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/network/kubemacpool.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/network/linux-bridge.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/network/multus.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/network/network.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/network/sriov.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/tools/manifest-templator/manifest-templator.go
Labels: size/XXL

#15 Add Makefile
  Makefile
  hack/clean.sh
  hack/common.sh
  hack/deploy.sh
Labels: size/L

#29 fix network addons sed
  hack/defaults
Labels: size/XS

#32 bump network addons version to 0.4.0
  Gopkg.lock
  Gopkg.toml
  deploy/converged/cluster_role.yaml
  deploy/converged/crds/cna.crd.yaml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/cna.crd.yaml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/operator.yaml
  deploy/standard/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  hack/build-manifests.sh
  hack/config
  hack/defaults
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
  tools/manifest-templator/manifest-templator.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/components/components.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/network/sriov.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/tools/manifest-templator/manifest-templator.go
Labels: size/XL

#36 Update kubevirt to 0.16.0
  Gopkg.lock
  Gopkg.toml
  deploy/converged/cluster_role.yaml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  vendor/kubevirt.io/kubevirt/cmd/virt-handler/virt-handler.go
  vendor/kubevirt.io/kubevirt/pkg/api/v1/deepcopy_generated.go
  vendor/kubevirt.io/kubevirt/pkg/api/v1/openapi_generated.go
  vendor/kubevirt.io/kubevirt/pkg/api/v1/types.go
  vendor/kubevirt.io/kubevirt/pkg/api/v1/types_swagger_generated.go
  vendor/kubevirt.io/kubevirt/pkg/controller/expectations.go
  vendor/kubevirt.io/kubevirt/pkg/controller/virtinformers.go
  vendor/kubevirt.io/kubevirt/pkg/testutils/mock_config.go
  vendor/kubevirt.io/kubevirt/pkg/testutils/mock_queue.go
  vendor/kubevirt.io/kubevirt/pkg/util/migrations/migrations.go
  vendor/kubevirt.io/kubevirt/pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  vendor/kubevirt.io/kubevirt/pkg/virt-config/config-map.go
  vendor/kubevirt.io/kubevirt/pkg/virt-config/feature-gates.go
  vendor/kubevirt.io/kubevirt/pkg/virt-controller/services/template.go
  vendor/kubevirt.io/kubevirt/pkg/virt-controller/watch/application.go
  vendor/kubevirt.io/kubevirt/pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
  vendor/kubevirt.io/kubevirt/pkg/virt-controller/watch/drain/evacuation/evacuation.go
  vendor/kubevirt.io/kubevirt/pkg/virt-controller/watch/migration.go
  vendor/kubevirt.io/kubevirt/pkg/virt-controller/watch/replicaset.go
  vendor/kubevirt.io/kubevirt/pkg/virt-controller/watch/vm.go
  vendor/kubevirt.io/kubevirt/pkg/virt-handler/cmd-client/client.go
  vendor/kubevirt.io/kubevirt/pkg/virt-handler/cmd-client/generated_mock_client.go
  vendor/kubevirt.io/kubevirt/pkg/virt-handler/vm.go
  vendor/kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/api/converter.go
  vendor/kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/cmd-server/server.go
  vendor/kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/generated_mock_manager.go
  vendor/kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/manager.go
  vendor/kubevirt.io/kubevirt/pkg/virt-operator/application.go
  vendor/kubevirt.io/kubevirt/pkg/virt-operator/creation/components/deployments.go
  vendor/kubevirt.io/kubevirt/pkg/virt-operator/creation/rbac/controller.go
  vendor/kubevirt.io/kubevirt/pkg/virt-operator/creation/rbac/operator.go
  vendor/kubevirt.io/kubevirt/pkg/virt-operator/install-strategy/create.go
  vendor/kubevirt.io/kubevirt/pkg/virt-operator/install-strategy/delete.go
  vendor/kubevirt.io/kubevirt/pkg/virt-operator/install-strategy/strategy.go
  vendor/kubevirt.io/kubevirt/pkg/virt-operator/kubevirt.go
  vendor/kubevirt.io/kubevirt/pkg/virt-operator/util/readycheck.go
  vendor/kubevirt.io/kubevirt/pkg/virt-operator/util/types.go
  vendor/kubevirt.io/kubevirt/tests/utils.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/client_go_adapter.go
Labels: size/XXL

#35 Remove oc from README and update note about OLM
  README.md
Labels: size/M

#37 Make operator-courier happy
  deploy/standard/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
Labels: size/M

#38 allow customization of network addons sriov type
  hack/defaults
Labels: size/XS

#44 bump network addons operator version to 0.5.0
  Gopkg.lock
  Gopkg.toml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/operator.yaml
  deploy/standard/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  hack/config
  hack/defaults
  tools/manifest-templator/manifest-templator.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/automation/check-patch.k8s-1.11.0.mounts
  vendor/github.com/kubevirt/cluster-network-addons-operator/automation/check-patch.k8s-1.11.0.packages
  vendor/github.com/kubevirt/cluster-network-addons-operator/automation/check-patch.k8s-1.11.0.sh
  vendor/github.com/kubevirt/cluster-network-addons-operator/automation/check-patch.os-3.11.0.mounts
  vendor/github.com/kubevirt/cluster-network-addons-operator/automation/check-patch.os-3.11.0.packages
  vendor/github.com/kubevirt/cluster-network-addons-operator/automation/check-patch.os-3.11.0.sh
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/components/components.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/controller/statusmanager/status_manager.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/network/kubemacpool.go
Labels: size/L

#33 add SSP operator
  Gopkg.lock
  Gopkg.toml
  README.md
  cmd/manager/main.go
  deploy/converged/cluster_role.yaml
  deploy/converged/cluster_role_binding.yaml
  deploy/converged/crds/ssp.crd.yaml
  deploy/converged/operator.yaml
  deploy/converged/service_account.yaml
  deploy/standard/cluster_role.yaml
  deploy/standard/crds/hco.cr.yaml
  hack/clean.sh
  hack/common.sh
  hack/config
  hack/defaults
  hack/deploy.sh
  hack/operator-test.sh
  pkg/controller/hyperconverged/hyperconverged_controller.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/apis/addtoscheme_kubevirt_v1.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/apis/apis.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/apis/kubevirt/v1/doc.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/apis/kubevirt/v1/register.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/apis/kubevirt/v1/types.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/apis/kubevirt/v1/zz_generated.deepcopy.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/client/clientset/versioned/clientset.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/client/clientset/versioned/doc.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/client/clientset/versioned/fake/doc.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/client/clientset/versioned/fake/register.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/client/clientset/versioned/scheme/doc.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/client/clientset/versioned/scheme/register.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/client/informers/externalversions/factory.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/client/informers/externalversions/generic.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/client/informers/externalversions/kubevirt/interface.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/client/informers/externalversions/kubevirt/v1/interface.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/client/informers/externalversions/kubevirt/v1/kubevirtcommontemplatesbundle.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/client/informers/externalversions/kubevirt/v1/kubevirtnodelabellerbundle.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/client/informers/externalversions/kubevirt/v1/kubevirttemplatevalidator.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/client/listers/kubevirt/v1/expansion_generated.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/client/listers/kubevirt/v1/kubevirtcommontemplatesbundle.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/client/listers/kubevirt/v1/kubevirtnodelabellerbundle.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/client/listers/kubevirt/v1/kubevirttemplatevalidator.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/versions/versions.go
Labels: size/XXL

#24 Add kubevirt-web-ui
  Gopkg.lock
  Gopkg.toml
  README.md
  deploy/converged/cluster_role.yaml
  deploy/converged/cluster_role_binding.yaml
  deploy/converged/crds/kwebui.crd.yaml
  deploy/converged/operator.yaml
  deploy/converged/service_account.yaml
  deploy/standard/cluster_role.yaml
  hack/common.sh
  hack/config
  hack/defaults
  hack/deploy.sh
  hack/operator-test.sh
  pkg/apis/hco/v1alpha1/hyperconverged_types.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  templates/cluster_role.yaml.in
  templates/cluster_role_binding.yaml.in
  templates/crds/kwebui.crd.yaml.in
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kwebui-operator.crb.yaml.in
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kwebui.crd.yaml.in
  templates/operator.yaml.in
  templates/service_account.yaml.in
  tools/manifest-templator/manifest-templator.go
  vendor/github.com/kubevirt/web-ui-operator/LICENSE
  vendor/github.com/kubevirt/web-ui-operator/build/kubevirt-web-ui-ansible/playbooks/kubevirt-web-ui/private/roles
  vendor/github.com/kubevirt/web-ui-operator/cmd/manager/main.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/apis/addtoscheme_kubevirt_v1alpha1.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/apis/apis.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/apis/kubevirt/v1alpha1/doc.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/apis/kubevirt/v1alpha1/kwebui_types.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/apis/kubevirt/v1alpha1/register.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/apis/kubevirt/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/components/components.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/controller/add_kwebui.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/controller/controller.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/controller/kwebui/helper.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/controller/kwebui/kwebui_controller.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/controller/kwebui/provision.go
  vendor/github.com/kubevirt/web-ui-operator/version/version.go
Labels: size/XXL

#51 Revert "Add SSP to generate code path (#48)"
  deploy/converged/crds/common-template-bundles.crd.yaml
  deploy/converged/crds/hco.cr.yaml
  deploy/converged/crds/kwebui.crd.yaml
  deploy/converged/crds/node-labeller-bundles.crd.yaml
  deploy/converged/crds/template-validator.crd.yaml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/common-template-bundles.crd.yaml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kwebui-operator.crb.yaml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kwebui.crd.yaml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/node-labeller-bundles.crd.yaml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/template-validator.crd.yaml
  deploy/converged/operator.yaml
  templates/cluster_role.yaml.in
  templates/cluster_role_binding.yaml.in
  templates/crds/common-template-bundles.crd.yaml.in
  templates/crds/node-labeller-bundles.crd.yaml.in
  templates/crds/template-validator.crd.yaml.in
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
  templates/operator.yaml.in
  templates/service_account.yaml.in
Labels: size/XL

#53 Install common templates to the openshift namespace
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: size/XS

#49 web-ui: Hardocde branding to okdvirt
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: size/XS

#47 Create KubeVirt's configuration ConfigMap
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: size/M

#50 ssp: fix hack/operator-test.sh script
  hack/clean.sh
  hack/common.sh
  hack/defaults
  hack/deploy.sh
  hack/operator-test.sh
Labels: size/S

#55 Create a script to point at quay registries for operator bundles
  Makefile
  hack/quay-registry.sh
Labels: size/M

#56 Align NMO to version v0.2.0
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/operator.yaml
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
  templates/operator.yaml.in
Labels: size/S

#57 Fix nmo format
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
Labels: size/L

#61 Update converged manifests
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/operator.yaml
Labels: size/S
