Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2019-11, with the labels that each got.

#334 Move leading ARG in Dockerfile
  deploy/Dockerfile.registry.upgrade
  hack/upgrade-test.sh
Labels: dco-signoff: yes, size/S

#337 Update okd 4.1
  cluster-up/cluster/okd-4.1/provider.sh
Labels: dco-signoff: yes, size/XS

#339 Replace COPY --chown with USER directive
  deploy/Dockerfile.registry.upgrade
Labels: dco-signoff: yes, size/XS

#343 Add KVM_EMULATION flag to templates
  deploy/olm-catalog/kubevirt-hyperconverged/0.0.3/kubevirt-hyperconverged-operator.v0.0.3.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/deploy.sh
  pkg/components/components.go
Labels: dco-signoff: yes, size/S

#341 add missing permission for ssp operator
  deploy/cluster_role.yaml
  templates/cluster_role.yaml.in
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
Labels: dco-signoff: yes, size/XS

#347 Update okd 4.1 (#337)
  cluster-up/cluster/okd-4.1/provider.sh
Labels: dco-signoff: yes, size/XS

#340 Add back v2v support on release-2.1 (reverts #306 and #310)
  deploy/crds/v2vvmware.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/0.0.2/kubevirt-hyperconverged-operator.v0.0.2.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/0.0.2/v2vvmware.crd.yaml
  deploy/operator.yaml
  hack/build-manifests.sh
  pkg/controller/hyperconverged/hyperconverged_controller.go
  templates/crds/v2vvmware.crd.yaml.in
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion_merger.yaml.in
Labels: dco-signoff: yes, size/M

#344 Fix OpenShift CI Upgrade Test
  Makefile
  hack/dump-state.sh
  hack/upgrade-openshiftci-config
  hack/upgrade-stdci-config
  hack/upgrade-test.sh
Labels: dco-signoff: yes, size/M

#342 Sync permissions between ssp operator and HCO.
  deploy/cluster_role.yaml
  templates/cluster_role.yaml.in
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
Labels: dco-signoff: yes, size/L

#348 Update HCO CSS
  deploy/olm-catalog/kubevirt-hyperconverged/0.0.3/kubevirt-hyperconverged-operator.v0.0.3.clusterserviceversion.yaml
Labels: dco-signoff: yes, size/M

#349 Fix typo
  README.md
Labels: dco-signoff: yes, size/XS

#353 Enable kvm emulation in ci
  deploy/Dockerfile.registry.ci
  deploy/Dockerfile.registry.upgrade
  hack/dump-state.sh
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion_merger.yaml.in
Labels: dco-signoff: yes, size/S

#357 Merge also hostpath-provisioner CSV
  tools/csv-merger/csv-merger.go
Labels: dco-signoff: yes, size/XS

#325 Rename master version as v1.0.0
  README.md
  deploy/hco.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/cdi.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/cna.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/common-template-bundles.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/hco.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/kubevirt-hyperconverged-operator.v1.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/kubevirt.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/metrics-aggregation.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/node-labeller-bundles.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/nodemaintenance.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/template-validator.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/v2vvmware.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/kubevirt-hyperconverged.package.yaml
  hack/build-manifests.sh
  templates/olm-catalog/kubevirt-hyperconverged/kubevirt-hyperconverged.package.yaml.in
  tools/quay-registry.sh
  version/version.go
Labels: dco-signoff: yes, size/XXL

#336 HCO Upgrade test validates HCO CR condition statuses
  Makefile
  hack/check-state.sh
  hack/upgrade-test.sh
Labels: dco-signoff: yes, ok-to-test, size/L
