Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2019-05, with the labels that each got.

#64 Bump ssp to 1.0.0 and update CSV
  Gopkg.lock
  Gopkg.toml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/ssp-op
  deploy/standard/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
Labels: size/L

#65 Add Web-UI scheme registration code
  cmd/manager/main.go
Labels: size/XS

#69 ssp-operator: update manifests to export POD_NAME
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/operator.yaml
  deploy/converged/ssp-op
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
  templates/operator.yaml.in
Labels: size/S

#68 Gopkg.toml: Bump web-ui-operator v0.1.5
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/kubevirt/web-ui-operator/cmd/manager/main.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/apis/addtoscheme_kubevirt_v1alpha1.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/components/components.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/controller/add_kwebui.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/controller/kwebui/helper.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/controller/kwebui/kwebui_controller.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/controller/kwebui/provision.go
Labels: size/M

#58 web-ui: let operator set the registry and tag
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/operator.yaml
  hack/build-manifests.sh
  pkg/controller/hyperconverged/hyperconverged_controller.go
  tools/manifest-templator/manifest-templator.go
Labels: size/M

#75 Web ui operator v0.1.6
  Gopkg.lock
  Gopkg.toml
  deploy/converged/cluster_role.yaml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  hack/defaults
  vendor/github.com/kubevirt/web-ui-operator/pkg/components/components.go
  vendor/kubevirt.io/kubevirt/pkg/kubecli/kubevirt_test_utils.go
Labels: size/S

#77 Bump cdi to version v1.9.0
  Gopkg.lock
  Gopkg.toml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/operator.yaml
  tools/manifest-templator/manifest-templator.go
  vendor/kubevirt.io/containerized-data-importer/cmd/cdi-cloner/clonertarget.go
  vendor/kubevirt.io/containerized-data-importer/cmd/cdi-controller/controller.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apiserver/apiserver.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apiserver/webhooks/validating-webhook/validating-webhook.go
  vendor/kubevirt.io/containerized-data-importer/pkg/common/common.go
  vendor/kubevirt.io/containerized-data-importer/pkg/controller/clone-controller.go
  vendor/kubevirt.io/containerized-data-importer/pkg/controller/config-controller.go
  vendor/kubevirt.io/containerized-data-importer/pkg/controller/datavolume-controller.go
  vendor/kubevirt.io/containerized-data-importer/pkg/controller/util.go
  vendor/kubevirt.io/containerized-data-importer/pkg/importer/data-processor.go
  vendor/kubevirt.io/containerized-data-importer/pkg/importer/http-datasource.go
  vendor/kubevirt.io/containerized-data-importer/pkg/importer/s3-datasource.go
  vendor/kubevirt.io/containerized-data-importer/pkg/importer/upload-datasource.go
  vendor/kubevirt.io/containerized-data-importer/pkg/importer/util.go
  vendor/kubevirt.io/containerized-data-importer/pkg/operator/controller/controller.go
  vendor/kubevirt.io/containerized-data-importer/pkg/operator/resources/cluster/apiserver.go
  vendor/kubevirt.io/containerized-data-importer/pkg/operator/resources/cluster/controller.go
  vendor/kubevirt.io/containerized-data-importer/pkg/operator/resources/cluster/factory.go
  vendor/kubevirt.io/containerized-data-importer/pkg/operator/resources/cluster/rbac.go
  vendor/kubevirt.io/containerized-data-importer/pkg/operator/resources/namespaced/apiserver.go
  vendor/kubevirt.io/containerized-data-importer/pkg/operator/resources/namespaced/common.go
  vendor/kubevirt.io/containerized-data-importer/pkg/operator/resources/namespaced/controller.go
  vendor/kubevirt.io/containerized-data-importer/pkg/operator/resources/namespaced/factory.go
  vendor/kubevirt.io/containerized-data-importer/pkg/operator/resources/namespaced/uploadproxy.go
  vendor/kubevirt.io/containerized-data-importer/pkg/operator/resources/operator/components.go
  vendor/kubevirt.io/containerized-data-importer/pkg/operator/resources/operator/factory.go
  vendor/kubevirt.io/containerized-data-importer/pkg/operator/resources/operator/operator.go
  vendor/kubevirt.io/containerized-data-importer/pkg/operator/resources/utils/common.go
  vendor/kubevirt.io/containerized-data-importer/pkg/util/util.go
  vendor/kubevirt.io/containerized-data-importer/tests/framework/pv.go
  vendor/kubevirt.io/containerized-data-importer/tests/framework/pvc.go
  vendor/kubevirt.io/containerized-data-importer/tests/utils/pod.go
  vendor/kubevirt.io/containerized-data-importer/tests/utils/pv.go
  vendor/kubevirt.io/containerized-data-importer/tests/utils/pvc.go
  vendor/kubevirt.io/containerized-data-importer/tests/utils/upload.go
  vendor/kubevirt.io/containerized-data-importer/tools/manifest-generator/manifest-generator.go
  vendor/kubevirt.io/kubevirt/pkg/kubecli/kubevirt_test_utils.go
Labels: size/XXL

#78 Fixed cluster_role manifest
  deploy/converged/cluster_role.yaml
  deploy/converged/ssp-op
  templates/cluster_role.yaml.in
Labels: size/XS

#80 Update Kubevirt to v0.17.0
  Gopkg.lock
  Gopkg.toml
  deploy/converged/cluster_role.yaml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  vendor/kubevirt.io/kubevirt/cmd/virt-handler/virt-handler.go
  vendor/kubevirt.io/kubevirt/cmd/virt-launcher/virt-launcher.go
  vendor/kubevirt.io/kubevirt/pkg/controller/virtinformers.go
  vendor/kubevirt.io/kubevirt/pkg/kubecli/generated_mock_kubevirt.go
  vendor/kubevirt.io/kubevirt/pkg/util/util.go
  vendor/kubevirt.io/kubevirt/pkg/virt-api/api.go
  vendor/kubevirt.io/kubevirt/pkg/virt-api/ca-manager.go
  vendor/kubevirt.io/kubevirt/pkg/virt-api/filesystem.go
  vendor/kubevirt.io/kubevirt/pkg/virt-api/generated_mock_filesystem.go
  vendor/kubevirt.io/kubevirt/pkg/virt-controller/watch/migration.go
  vendor/kubevirt.io/kubevirt/pkg/virt-handler/migration-proxy/migration-proxy.go
  vendor/kubevirt.io/kubevirt/pkg/virt-handler/vm.go
  vendor/kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
  vendor/kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/cli/libvirt.go
  vendor/kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/manager.go
  vendor/kubevirt.io/kubevirt/pkg/virt-operator/creation/rbac/apiserver.go
  vendor/kubevirt.io/kubevirt/pkg/virt-operator/creation/rbac/handler.go
  vendor/kubevirt.io/kubevirt/tests/utils.go
Labels: size/XXL

#83 Web ui operator v0.1.8
  Gopkg.lock
  Gopkg.toml
  deploy/converged/cluster_role.yaml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/operator.yaml
  hack/defaults
  vendor/github.com/kubevirt/web-ui-operator/pkg/components/components.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/controller/kwebui/provision.go
  vendor/kubevirt.io/kubevirt/pkg/kubecli/generated_mock_kubevirt.go
Labels: size/L

#82 web-ui: hardcode "Version: automatic"
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: size/XS

#84 Follow up #80 with update to hack script
  hack/config
  hack/defaults
Labels: size/XS

#85 cna 0.7.0
  Gopkg.lock
  Gopkg.toml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/operator.yaml
  hack/config
  hack/defaults
  tools/manifest-templator/manifest-templator.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/components/components.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/network/linux-bridge.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/tools/manifest-templator/manifest-templator.go
Labels: size/L

#88 Web ui operator v0.1.10
  Gopkg.lock
  Gopkg.toml
  deploy/converged/cluster_role.yaml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  hack/defaults
  vendor/github.com/kubevirt/web-ui-operator/cmd/manager/main.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/components/components.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/controller/kwebui/kwebui_controller.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/controller/kwebui/provision.go
Labels: size/M

#89 Enable CPU feature discovery for kubevirt
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: size/XS

#91 SSP: update operator APIs to 1.0.1
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/apis/kubevirt/v1/types.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/versions/versions.go
Labels: size/S

#94 SSP: don't specify component versions
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: size/XS

#97 * Vendor cdi related csv methods from cdi v1.9.1
  Gopkg.lock
  Gopkg.toml
  deploy/converged/cluster_role.yaml
  deploy/converged/crds/cdi.crd.yaml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/cdi.crd.yaml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/operator.yaml
  pkg/cdicomponents/cdicomponents.go
  tools/manifest-templator/manifest-templator.go
  vendor/kubevirt.io/containerized-data-importer/pkg/operator/resources/operator/components.go
  vendor/kubevirt.io/containerized-data-importer/pkg/operator/resources/operator/operator.go
Labels: size/XXL

#96 Add Node Maintenance CRD
  README.md
  deploy/converged/crds/nodemaintenance.crd.yaml
  templates/crds/nodemaintenance.crd.yaml.in
  vendor/kubevirt.io/kubevirt/pkg/kubecli/generated_mock_kubevirt.go
Labels: size/L

#98 SSP: watch all the namespaces
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/operator.yaml
  deploy/converged/ssp-op
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
  templates/operator.yaml.in
Labels: size/S

#101 Align NMO to version v0.3.0
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/operator.yaml
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
  templates/operator.yaml.in
Labels: size/XS

#103 bump cna to 0.9.0
  Gopkg.lock
  Gopkg.toml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/operator.yaml
  hack/config
  hack/defaults
  tools/manifest-templator/manifest-templator.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1alpha1/zz_generated.defaults.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/components/components.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/network/image-pull-policy.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/network/kubemacpool.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/network/network.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/network/nmstate.go
Labels: size/XL
