Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2019-10, with the labels that each got.

#316 Update to KubeVirt 0.20.8 with new image-prefix flag
  Gopkg.lock
  Gopkg.toml
  tools/manifest-templator/manifest-templator.go
  vendor/kubevirt.io/client-go/kubecli/handler.go
  vendor/kubevirt.io/kubevirt/pkg/container-disk/container-disk.go
  vendor/kubevirt.io/kubevirt/pkg/virt-handler/vm.go
  vendor/kubevirt.io/kubevirt/pkg/virt-operator/creation/components/deployments.go
  vendor/kubevirt.io/kubevirt/pkg/virt-operator/creation/csv/csv.go
  vendor/kubevirt.io/kubevirt/pkg/virt-operator/install-strategy/strategy.go
  vendor/kubevirt.io/kubevirt/pkg/virt-operator/kubevirt.go
  vendor/kubevirt.io/kubevirt/pkg/virt-operator/util/config.go
  vendor/kubevirt.io/kubevirt/staging/src/kubevirt.io/client-go/kubecli/handler.go
  vendor/kubevirt.io/kubevirt/tests/utils.go
  vendor/kubevirt.io/kubevirt/tools/csv-generator/csv-generator.go
  vendor/kubevirt.io/kubevirt/tools/manifest-templator/manifest-templator.go
  vendor/kubevirt.io/kubevirt/tools/resource-generator/resource-generator.go
Labels: dco-signoff: yes, size/L

#318 Bug 1757784: Use predicates to prevent noisy reconcile
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: dco-signoff: yes, size/XS

#315 [CNV-3175] HCO add debugging information when an upgrade fails
  Makefile
  hack/dump-state.sh
  hack/upgrade-test.sh
Labels: dco-signoff: yes, ok-to-test, size/L

#319 bump CNAO to 0.18.0
  Gopkg.lock
  Gopkg.toml
  deploy/olm-catalog/kubevirt-hyperconverged/0.0.3/kubevirt-hyperconverged-operator.v0.0.3.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/config
  hack/defaults
  tools/manifest-templator/manifest-templator.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/components/components.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/test/releases/0.19.0.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/tools/manifest-templator/manifest-templator.go
Labels: dco-signoff: yes, size/L

#321 Update SSP operator to v1.0.16
  Gopkg.lock
  Gopkg.toml
  deploy/olm-catalog/kubevirt-hyperconverged/0.0.3/kubevirt-hyperconverged-operator.v0.0.3.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/common.sh
  hack/config
  hack/defaults
  hack/deploy.sh
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/apis/kubevirt/v1/types.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/apis/kubevirt/v1/zz_generated.deepcopy.go
Labels: dco-signoff: yes, size/L

#324 Update okd-4.1 image to fix "make cluster-up"
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/okd-4.1/provider.sh
Labels: dco-signoff: yes, size/S

#277 Add basic VMI functionality tests
  Gopkg.lock
  Makefile
  automation/test.sh
  hack/build-tests.sh
  hack/common.sh
  hack/defaults
  hack/functest.sh
  hack/in-docker.sh
  hack/run-tests.sh
  hack/unit-test.sh
  tests/build/Dockerfile
  tests/build/entrypoint.sh
  tests/build/fedora.repo
  tests/func-tests/main_test.go
  tests/func-tests/utils.go
  tests/func-tests/virtual_machines_test.go
  tests/travis-tests/Dockerfile
  tests/travis-tests/README.md
  tests/travis-tests/kubernetes.repo
  tests/travis-tests/test.sh
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/LICENSE
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/automation/check-patch.k8s-1.15.1.mounts
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/automation/check-patch.k8s-1.15.1.packages
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/automation/check-patch.k8s-1.15.1.sh
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/automation/check-patch.okd-4.1.mounts
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/automation/check-patch.okd-4.1.packages
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/automation/check-patch.okd-4.1.sh
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/cmd/hyperconverged-cluster-operator/main.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/apis/addtoscheme_hco_v1alpha1.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/apis/apis.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/apis/hco/v1alpha1/doc.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/apis/hco/v1alpha1/hyperconverged_types.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/apis/hco/v1alpha1/register.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/apis/hco/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/apis/hco/v1alpha1/zz_generated.defaults.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/apis/hco/v1alpha1/zz_generated.openapi.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/components/components.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/controller/add_hyperconverged.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/controller/controller.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/controller/hyperconverged/hyperconverged_controller.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/tools/csv-merger/csv-merger.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/tools/manifest-templator/manifest-templator.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/tools/util/marshaller.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/version/version.go
Labels: dco-signoff: yes, size/XXL

#328 Fix vendor issue
  Gopkg.lock
  hack/build-tests.sh
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/LICENSE
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/automation/check-patch.k8s-1.15.1.mounts
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/automation/check-patch.k8s-1.15.1.packages
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/automation/check-patch.k8s-1.15.1.sh
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/automation/check-patch.okd-4.1.mounts
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/automation/check-patch.okd-4.1.packages
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/automation/check-patch.okd-4.1.sh
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/cmd/hyperconverged-cluster-operator/main.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/apis/addtoscheme_hco_v1alpha1.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/apis/apis.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/apis/hco/v1alpha1/doc.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/apis/hco/v1alpha1/hyperconverged_types.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/apis/hco/v1alpha1/register.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/apis/hco/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/apis/hco/v1alpha1/zz_generated.defaults.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/apis/hco/v1alpha1/zz_generated.openapi.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/components/components.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/controller/add_hyperconverged.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/controller/controller.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/controller/hyperconverged/hyperconverged_controller.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/tools/csv-merger/csv-merger.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/tools/manifest-templator/manifest-templator.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/tools/util/marshaller.go
  vendor/github.com/kubevirt/hyperconverged-cluster-operator/version/version.go
Labels: dco-signoff: yes, size/XXL

#327 Set replaces on the CSV only if we have a value
  tools/csv-merger/csv-merger.go
Labels: dco-signoff: yes, size/XS

#313 Modify upgrade test for OpenShift CI
  deploy/Dockerfile
  deploy/Dockerfile.registry.intermediate
  deploy/Dockerfile.registry.upgrade
  hack/build-registry-bundle.sh
  hack/upgrade-create-new-version.sh
  hack/upgrade-test-build-images.sh
  hack/upgrade-test.sh
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
Labels: dco-signoff: yes, size/L

#329 Run functionality tests after upgrade
  automation/test.sh
Labels: dco-signoff: yes, size/XS
