Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2019-08, with the labels that each got.

#193 Fix minor typo
  README.md
Labels: size/XS

#196 Add some tools to help publish bundles
  Makefile
  docs/dev-tools.md
  tools/operator-courier/push.sh
  tools/quay-registry.sh
  tools/token.sh
Labels: size/L

#195 Add a space after strings to form a list
  hack/deploy.sh
Labels: size/XS

#204 Remove " so for loop doesn't treat it as single string
  hack/deploy.sh
Labels: size/XS

#199 Metrics aggregation
  Gopkg.toml
  deploy/crds/metrics-aggregation.crd.yaml
  deploy/deploy.sh
  deploy/operator.yaml
  hack/defaults
  pkg/controller/hyperconverged/factory.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  templates/crds/metrics-aggregation.crd.yaml.in
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
Labels: size/M

#197 WIP: HCO conditions
  Gopkg.lock
  cmd/hyperconverged-cluster-operator/main.go
  deploy/olm-catalog/kubevirt-hyperconverged/0.0.2/kubevirt-hyperconverged-operator.v0.0.2.clusterserviceversion.yaml
  deploy/operator.yaml
  docs/status.md
  pkg/apis/hco/v1alpha1/hyperconverged_types.go
  pkg/components/components.go
  pkg/controller/hyperconverged/factory.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  vendor/github.com/openshift/custom-resource-status/LICENSE
  vendor/github.com/openshift/custom-resource-status/conditions/v1/_doc.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/conditions.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/types.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/custom-resource-status/objectreferences/v1/_doc.go
  vendor/github.com/openshift/custom-resource-status/objectreferences/v1/objectreferences.go
  vendor/github.com/openshift/custom-resource-status/tools/tools.go
Labels: do-not-merge/work-in-progress, size/XXL

#192 Add channels to HCO's package
  deploy/olm-catalog/kubevirt-hyperconverged/kubevirt-hyperconverged.package.yaml
  templates/olm-catalog/kubevirt-hyperconverged/kubevirt-hyperconverged.package.yaml.in
  tools/quay-registry.sh
Labels: do-not-merge/work-in-progress, size/M

#188 Few updates to the README
  Makefile
  README.md
  cluster/sync.sh
  images/HCO-design.jpg
Labels: size/M
