Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2019-03, with the labels that each got.

#4 Create the CDI CustomResource through the HCO
  README.md
  cmd/manager/main.go
  deploy/cluster_role_binding.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/service_account.yaml
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: size/L

#5 WIP: Provide a script to test glueing together operators
  hack/README.md
  hack/config
  hack/defaults
  hack/jinja2/cdi-j2.py
  hack/operator-test.sh
Labels: do-not-merge/work-in-progress, size/L

#10 add network addons operator
  Gopkg.lock
  Gopkg.toml
  README.md
  cmd/manager/main.go
  hack/config
  hack/defaults
  hack/operator-test.sh
  pkg/apis/hco/v1alpha1/hyperconverged_types.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/LICENSE
  vendor/github.com/kubevirt/cluster-network-addons-operator/cmd/manager/main.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/apis.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1alpha1/doc.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1alpha1/register.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1alpha1/zz_generated.defaults.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apply/apply.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apply/merge.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/controller/manager.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/controller/networkaddonsconfig/controller.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/controller/networkaddonsconfig/previous.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/names/names.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/network/image-pull-policy.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/network/linux-bridge.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/network/multus.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/network/network.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/render/render.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/util/k8s/dynamicrestmapper.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/util/k8s/unstructured.go
  vendor/golang.org/x/tools/internal/lsp/cache/pkg.go
  vendor/golang.org/x/tools/internal/lsp/protocol/preserve/basic.go
  vendor/golang.org/x/tools/internal/lsp/protocol/preserve/diagnostics.go
  vendor/golang.org/x/tools/internal/lsp/protocol/preserve/general.go
  vendor/golang.org/x/tools/internal/lsp/protocol/preserve/language.go
  vendor/golang.org/x/tools/internal/lsp/protocol/preserve/registration.go
  vendor/golang.org/x/tools/internal/lsp/protocol/preserve/text.go
  vendor/golang.org/x/tools/internal/lsp/protocol/preserve/window.go
  vendor/golang.org/x/tools/internal/lsp/protocol/preserve/workspace.go
  vendor/golang.org/x/tools/internal/lsp/protocol/tsprotocol.go
Labels: size/XXL

#14 operator-test.sh: add timeout parameter to oc-wait
  hack/defaults
  hack/operator-test.sh
Labels: size/XS
