Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2019-07, with the labels that each got.

#147 NMO was using wrong api group
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/standard/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
Labels: size/S

#144 Disable KubeMacPool for CNV 2.0
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: size/XS

#149 NMO was using wrong api group (#147)
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/standard/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
Labels: size/S

#104 Refactor HCO controller reconcile function
  pkg/apis/hco/v1alpha1/register.go
  pkg/controller/hyperconverged/factory.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
Labels: size/XL

#150 Update all the references to kubevirt to v0.18.1 and regenerate manifests with new dependencies
  Gopkg.lock
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/operator.yaml
  deploy/converged/ssp-op
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
  templates/operator.yaml.in
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/cmd/json-patch/file_flag.go
  vendor/github.com/evanphx/json-patch/cmd/json-patch/main.go
  vendor/github.com/evanphx/json-patch/errors.go
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
Labels: size/XXL

#151 Update all the references to kubevirt to v0.17.4
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/operator.yaml
  deploy/converged/ssp-op
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
  templates/operator.yaml.in
Labels: size/S

#153 Update SSP RBAC rules
  deploy/converged/cluster_role.yaml
  templates/cluster_role.yaml.in
Labels: size/M

#154 Fix template files.
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/cdi-operator.crb.yaml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/cna-operator.crb.yaml
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/cdi-operator.crb.yaml.in
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/cna-operator.crb.yaml.in
Labels: size/M

#152 Set component versions based on Gopkg.toml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/operator.yaml
  hack/build-manifests.sh
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
  templates/operator.yaml.in
  tools/manifest-templator/manifest-templator.go
Labels: size/L

#157 Align the upstream CSV with d/s and expand description
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/standard/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
  tools/manifest-templator/manifest-templator.go
Labels: size/L

#159 bump CNA to 0.11.0
  Gopkg.lock
  Gopkg.toml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/operator.yaml
  hack/config
  hack/defaults
  tools/manifest-templator/manifest-templator.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/automation/check-patch.lifecycle.k8s-1.11.0.mounts
  vendor/github.com/kubevirt/cluster-network-addons-operator/automation/check-patch.lifecycle.k8s-1.11.0.packages
  vendor/github.com/kubevirt/cluster-network-addons-operator/automation/check-patch.lifecycle.k8s-1.11.0.sh
  vendor/github.com/kubevirt/cluster-network-addons-operator/automation/check-patch.lifecycle.os-3.11.0.mounts
  vendor/github.com/kubevirt/cluster-network-addons-operator/automation/check-patch.lifecycle.os-3.11.0.packages
  vendor/github.com/kubevirt/cluster-network-addons-operator/automation/check-patch.lifecycle.os-3.11.0.sh
  vendor/github.com/kubevirt/cluster-network-addons-operator/automation/check-patch.workflow.k8s-1.11.0.mounts
  vendor/github.com/kubevirt/cluster-network-addons-operator/automation/check-patch.workflow.k8s-1.11.0.packages
  vendor/github.com/kubevirt/cluster-network-addons-operator/automation/check-patch.workflow.k8s-1.11.0.sh
  vendor/github.com/kubevirt/cluster-network-addons-operator/automation/check-patch.workflow.os-3.11.0.mounts
  vendor/github.com/kubevirt/cluster-network-addons-operator/automation/check-patch.workflow.os-3.11.0.packages
  vendor/github.com/kubevirt/cluster-network-addons-operator/automation/check-patch.workflow.os-3.11.0.sh
  vendor/github.com/kubevirt/cluster-network-addons-operator/cmd/manager/main.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1alpha1/zz_generated.defaults.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apply/apply.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apply/merge.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/components/components.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/controller/statusmanager/status_manager.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/network/multus.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/network/nmstate.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/util/k8s/unstructured.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/test/check/check.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/test/check/components.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/test/check/conditions.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/test/operations/operations.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/test/releases/0.10.0.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/test/releases/0.11.0.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/test/releases/0.12.0.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/test/releases/releases.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/tools/manifest-templator/manifest-templator.go
Labels: size/XXL

#162 Make the quay-registry script more configurable
  Makefile
  README.md
  tools/quay-registry.sh
Labels: size/M

#165 Initial preparations for OKD ci
  tests/Dockerfile
  tests/README.md
  tests/kubernetes.repo
  tests/test.sh
Labels: size/M

#164 Add readiness probe to the HCO
  Gopkg.lock
  cmd/manager/main.go
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/operator.yaml
  deploy/standard/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/standard/operator.yaml
  pkg/components/components.go
Labels: size/M

#167 Update README.md with the updated instructions for OCP 4.2
  README.md
Labels: size/XS

#161 Separately handle operator_tag and component_tag
  Gopkg.lock
  Gopkg.toml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/operator.yaml
  deploy/standard/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  hack/build-manifests.sh
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
  templates/operator.yaml.in
  tools/manifest-templator/manifest-templator.go
  vendor/github.com/kubevirt/web-ui-operator/cmd/manager/main.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/components/components.go
Labels: size/M

#169 Update ssp operator to 1.0.4
  Gopkg.lock
  Gopkg.toml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/operator.yaml
  deploy/standard/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
Labels: size/S

#174 Remove web-ui from HCO
  Gopkg.lock
  Gopkg.toml
  cmd/manager/main.go
  deploy/converged/cluster_role.yaml
  deploy/converged/cluster_role_binding.yaml
  deploy/converged/crds/kwebui.crd.yaml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kwebui.crd.yaml
  deploy/converged/operator.yaml
  deploy/converged/service_account.yaml
  deploy/deploy.sh
  deploy/standard/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  hack/build-manifests.sh
  hack/clean.sh
  hack/common.sh
  hack/config
  hack/defaults
  hack/deploy.sh
  hack/operator-test.sh
  pkg/apis/hco/v1alpha1/hyperconverged_types.go
  pkg/controller/hyperconverged/factory.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  templates/cluster_role.yaml.in
  templates/cluster_role_binding.yaml.in
  templates/crds/kwebui.crd.yaml.in
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kwebui.crd.yaml.in
  templates/operator.yaml.in
  templates/service_account.yaml.in
  tools/manifest-templator/manifest-templator.go
  vendor/github.com/kubevirt/web-ui-operator/LICENSE
  vendor/github.com/kubevirt/web-ui-operator/build/kubevirt-web-ui-ansible/playbooks/kubevirt-web-ui/private/roles
  vendor/github.com/kubevirt/web-ui-operator/cmd/manager/main.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/apis/addtoscheme_kubevirt_v1alpha1.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/apis/apis.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/apis/kubevirt/v1alpha1/doc.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/apis/kubevirt/v1alpha1/kwebui_types.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/apis/kubevirt/v1alpha1/register.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/apis/kubevirt/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/components/components.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/controller/add_kwebui.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/controller/controller.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/controller/kwebui/helper.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/controller/kwebui/kwebui_controller.go
  vendor/github.com/kubevirt/web-ui-operator/pkg/controller/kwebui/provision.go
  vendor/github.com/kubevirt/web-ui-operator/version/version.go
Labels: size/XXL

#175 Update cdi to 1.9.4
  Gopkg.lock
  Gopkg.toml
  deploy/converged/cluster_role.yaml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/standard/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  vendor/kubevirt.io/containerized-data-importer/cmd/cdi-controller/controller.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apiserver/apiserver.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apiserver/util.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apiserver/webhooks/api/clone-validate.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apiserver/webhooks/datavolume-mutate.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apiserver/webhooks/datavolume-validate.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apiserver/webhooks/handler.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apiserver/webhooks/scheme.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apiserver/webhooks/validating-webhook/util.go
  vendor/kubevirt.io/containerized-data-importer/pkg/common/common.go
  vendor/kubevirt.io/containerized-data-importer/pkg/controller/clone-controller.go
  vendor/kubevirt.io/containerized-data-importer/pkg/controller/datavolume-controller.go
  vendor/kubevirt.io/containerized-data-importer/pkg/controller/util.go
  vendor/kubevirt.io/containerized-data-importer/pkg/importer/data-processor.go
  vendor/kubevirt.io/containerized-data-importer/pkg/operator/resources/cluster/apiserver.go
  vendor/kubevirt.io/containerized-data-importer/pkg/operator/resources/namespaced/controller.go
  vendor/kubevirt.io/containerized-data-importer/pkg/operator/resources/operator/operator.go
  vendor/kubevirt.io/containerized-data-importer/pkg/token/token.go
  vendor/kubevirt.io/containerized-data-importer/pkg/uploadproxy/uploadproxy.go
  vendor/kubevirt.io/containerized-data-importer/tests/framework/framework.go
  vendor/kubevirt.io/containerized-data-importer/tests/framework/pvc.go
  vendor/kubevirt.io/containerized-data-importer/tests/utils/datavolume.go
  vendor/kubevirt.io/containerized-data-importer/tests/utils/pvc.go
  vendor/kubevirt.io/containerized-data-importer/tests/utils/upload.go
Labels: size/XXL

#176 Add replaces and use Tags for each operator
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/converged/operator.yaml
  deploy/standard/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  hack/build-manifests.sh
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
  tools/manifest-templator/manifest-templator.go
Labels: size/M

#163 Standarize conditions across component operators
  docs/conditions.md
Labels: size/L

#173 Add instructions on how to deploy through marketplace
  README.md
  deploy/hco.yaml
Labels: size/M

#172 Operator courier part 1
  Makefile
  README.md
  cluster/sync.sh
  deploy/cluster_role.yaml
  deploy/cluster_role_binding.yaml
  deploy/converged/crds/ssp.crd.yaml
  deploy/converged/olm-catalog/kubevirt-hyperconverged/0.0.1/hco.crd.yaml
  deploy/converged/ssp-op
  deploy/crds/cdi.crd.yaml
  deploy/crds/cna.crd.yaml
  deploy/crds/common-template-bundles.crd.yaml
  deploy/crds/hco.cr.yaml
  deploy/crds/hco.crd.yaml
  deploy/crds/kubevirt.crd.yaml
  deploy/crds/node-labeller-bundles.crd.yaml
  deploy/crds/nodemaintenance.crd.yaml
  deploy/crds/template-validator.crd.yaml
  deploy/deploy.sh
  deploy/olm-catalog/kubevirt-hyperconverged/0.0.1/cdi.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/0.0.1/cna.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/0.0.1/common-template-bundles.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/0.0.1/hco.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/0.0.1/node-labeller-bundles.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/0.0.1/nodemaintenance.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/0.0.1/template-validator.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/kubevirt-hyperconverged.package.yaml
  deploy/operator.yaml
  deploy/service_account.yaml
  deploy/standard/cluster_role.yaml
  deploy/standard/cluster_role_binding.yaml
  deploy/standard/crds/hco.cr.yaml
  deploy/standard/olm-catalog/kubevirt-hyperconverged/0.0.1/hco.crd.yaml
  deploy/standard/olm-catalog/kubevirt-hyperconverged/0.0.1/kubevirt-hyperconverged-operator.v0.0.1.clusterserviceversion.yaml
  deploy/standard/olm-catalog/kubevirt-hyperconverged/kubevirt-hyperconverged.package.yaml
  deploy/standard/operator.yaml
  deploy/standard/service_account.yaml
  hack/build-manifests.sh
  hack/clean.sh
  hack/deploy.sh
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/cdi.crd.yaml.in
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/cna.crd.yaml.in
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/hco.crd.yaml.in
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt.crd.yaml.in
  tools/operator-courier/Dockerfile
  tools/operator-courier/push.sh
  tools/operator-registry/Dockerfile
Labels: size/XXL

#178 Increase timeout on HCO container
  hack/deploy.sh
Labels: size/XS

#182 Add missing double-quotes
  hack/defaults
Labels: size/XS

#180 Improve CI
  README.md
  deploy/deploy.sh
  deploy/hco.cr.yaml
  hack/clean.sh
  hack/deploy.sh
  hack/functest.sh
Labels: size/L

#183 Integrate with openshift CI presubmit jobs
  .gitignore
  Makefile
  build/Dockerfile.okd
  cluster/sync.sh
  cmd/hyperconverged-cluster-operator/main.go
  hack/deploy.sh
Labels: size/M

#185 Small typo
  docs/conditions.md
Labels: size/XS

#187 Update conditions repo location
  docs/conditions.md
Labels: size/XS
