Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2020-04, with the labels that each got.

#520 Don't call handleComponentConditions for KubeVirtMetricsAggregation
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#517 bump SSP to v1.0.29
  deploy/cluster_role.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/build-manifests.sh
  hack/config
  hack/defaults
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#522 CI: try to avoid false positives on upgrade checks
  hack/check-state.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#521 Fix sync script to still pull in from a local registry.
  cluster/sync.sh
  hack/deploy.sh
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  tests/func-tests/certificates_test.go
Labels: dco-signoff: yes, release-note-none, size/XL

#519 Move v2vvmware CRD under v2v.kubevirt.io API group
  deploy/crds/hco01.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/hco01.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#529 Simplify how we track component versions
  hack/build-manifests.sh
  hack/common.sh
  hack/config
  hack/defaults
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#516 API Group Overlap Validation Among Operators
  tools/csv-merger/csv-merger.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#530 drop SR-IOV from config
  hack/defaults
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#531 bump cnao to 0.27.7
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#542 [release-2.3] Fix CI for klog/v2
  tests/build/Dockerfile
Labels: dco-signoff: yes, lgtm, release-note-none, size/XS

#541 [release-2.3] disable kubemacpool
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  tests/func-tests/certificates_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#543 Add a nightly bundle test Dockerfile
  deploy/nightly-bundle/Dockerfile
  deploy/nightly-bundle/deploy.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#535 Bump SSP to 1.0.30
  deploy/cluster_role.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/modules.txt
Labels: dco-signoff: yes, release-note, size/S

#539 disable kubemacpool
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  tests/func-tests/certificates_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#534 Bump NMO to 0.5.0
  deploy/cluster_role.yaml
  deploy/crds/node-maintenance00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/node-maintenance00.crd.yaml
  deploy/operator.yaml
  hack/config
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#538 bump cnao to 0.35.1
  deploy/crds/cluster-network-addons00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/cluster-network-addons00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/Makefile
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/go113.go
  vendor/github.com/pkg/errors/stack.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#532 Integrate API Groups overlap validation test
  hack/build-manifests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#546 Bump CDI to v1.16.0
  deploy/cluster_role.yaml
  deploy/crds/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/deepcopy_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types_swagger_generated.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#547 Bump kubevirt to v0.28.0
  deploy/cluster_role.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  hack/config
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#537 Reuse test image
  hack/build-in-docker.sh
  tests/build/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#549 fix a bug in the build-in-docker script
  hack/build-in-docker.sh
  tests/build/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#550 use pre-prepared image for kubevirtci tests
  hack/in-docker.sh
  tests/README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#463 Introducing kustomize for HCO deployment
  README.md
  deploy/deploy_imageregistry.sh
  deploy/deploy_marketplace.sh
  deploy/kustomize/README.md
  deploy/kustomize/base/hco_cr.yaml
  deploy/kustomize/base/kustomization.yaml
  deploy/kustomize/base/operator_group.yaml
  deploy/kustomize/base/subscription.yaml
  deploy/kustomize/deploy_kustomize.sh
  deploy/kustomize/image_registry/catalog_source.yaml
  deploy/kustomize/image_registry/kustomization.yaml
  deploy/kustomize/kvm_emulation/kustomization.yaml
  deploy/kustomize/kvm_emulation/subscription.patch.yaml
  deploy/kustomize/marketplace/catalog_source_config.yaml
  deploy/kustomize/marketplace/kustomization.yaml
  deploy/kustomize/marketplace/operator_source.yaml
  deploy/kustomize/namespace.yaml
  deploy/kustomize/private_repo/kustomization.yaml
  deploy/kustomize/private_repo/operator_source.patch.yaml
  images/HCO_Kustomize_Diagram.png
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L
