Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2020-10, with the labels that each got.

#842 Add documentation for node-placement
  docs/cluster-configuration.md
  docs/config.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#848 [release-1.2] Bump NETWORK_ADDONS to v0.42.2
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/kubevirt-hyperconverged-operator.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/addtoscheme_networkaddonsoperator_v1.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/addtoscheme_networkaddonsoperator_v1alpha1.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/apis.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#847 Fix ValidateUpdate on the validating webhook
  pkg/apis/hco/v1beta1/hyperconverged_webhook.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#854 Partially reconcile IMS ConfigMap
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_components_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#855 Bump KUBEVIRT_VMWARE v2.0.0-9
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/config
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#859 Bump VM_IMPORT to v0.2.3
  deploy/crds/vm-import-operator00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/vm-import-operator00.crd.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  pkg/apis/hco/v1beta1/hyperconverged_resources.go
  pkg/apis/hco/v1beta1/hyperconverged_resources_test.go
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/hyperconverged_webhook_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  vendor/github.com/kubevirt/vm-import-operator/pkg/apis/v2v/v1beta1/vmimportconfig_types.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/LICENSE
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/api/types.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#851 Add additonal info about node placement APIs
  docs/cluster-configuration.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#861 [release-1.2] Bump VM-Import to v0.2.3 (#859)
  deploy/crds/vm-import-operator00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/kubevirt-hyperconverged-operator.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/vm-import-operator00.crd.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  pkg/apis/hco/v1beta1/hyperconverged_resources.go
  pkg/apis/hco/v1beta1/hyperconverged_resources_test.go
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/hyperconverged_webhook_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  vendor/github.com/kubevirt/vm-import-operator/pkg/apis/v2v/v1beta1/vmimportconfig_types.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/LICENSE
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/api/types.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#862 Bump CDI to v1.24.0
  deploy/crds/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  pkg/apis/hco/v1beta1/hyperconverged_resources.go
  pkg/apis/hco/v1beta1/hyperconverged_resources_test.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/BUILD.bazel
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/BUILD.bazel
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#863 Add the VIRTV2V_IMAGE environment variable to the CSV
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/build-manifests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#864 Add Operator Descriptors to properly render node placement on UI
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#868 [release-1.2] Add Operator Descriptors to properly render node placement on UI (#864)
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/kubevirt-hyperconverged-operator.v1.2.0.clusterserviceversion.yaml
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#871 Fix the reconciliation of components CRs
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_components_test.go
  pkg/controller/hyperconverged/testUtils_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#875 [release-1.2] Rebuild the CSV due to kubevirt-ssp-operator v1.2.1
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/kubevirt-hyperconverged-operator.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#872 Rebuild the CSV due to kubevirt-ssp-operator v1.2.1
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/kubevirt-hyperconverged-operator.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/vm-import-operator00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#877 Build manifest: Validate the yaml files
  hack/build-manifests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#880 Add new test to check the node placement feature
  hack/deploy.sh
  hack/np-config-hook.sh
  hack/test-node-placement.sh
  hack/testvm.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#884 build-manifests: don't attach a TTY to yamllint
  hack/build-manifests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#885 Build upgrade test images with fedora-33
  deploy/Dockerfile.registry.upgrade
  deploy/Dockerfile.registry.upgrade-prev
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#881 Adding CSV Annotation for HCO CR deployment during installation
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  pkg/components/components.go
  tools/csv-merger/csv-merger.go
  tools/util/marshaller.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#889 Bump VM_IMPORT to v0.2.4
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#892 [release-1.2] Bump VM_IMPORT to v0.2.4
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/kubevirt-hyperconverged-operator.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/build-manifests.sh
  hack/config
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#890 Remove set-context from deploy.sh
  deploy/deploy.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#886 Fix the node placement test
  automation/test.sh
  hack/deploy.sh
  hack/deploy_only_cr.sh
  hack/np-config-hook.sh
  hack/test-node-placement.sh
  tests/func-tests/virtual_machines_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#893 Split operator and webhook into two different pods
  cluster/sync.sh
  cmd/hyperconverged-cluster-operator/main.go
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/deploy.sh
  pkg/apis/hco/v1beta1/hyperconverged_webhook.go
  pkg/components/components.go
  pkg/util/cluster.go
  pkg/util/consts.go
  pkg/util/util.go
  tools/manifest-templator/manifest-templator.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#896 [release-1.2] Split operator and webhook into two different pods (#893)
  cluster/sync.sh
  cmd/hyperconverged-cluster-operator/main.go
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/kubevirt-hyperconverged-operator.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/deploy.sh
  pkg/apis/hco/v1beta1/hyperconverged_webhook.go
  pkg/components/components.go
  pkg/util/consts.go
  pkg/util/util.go
  tools/manifest-templator/manifest-templator.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#897 csv: align 1.2.0 with what on release-1.2 branch
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/kubevirt-hyperconverged-operator.v1.2.0.clusterserviceversion.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#894 Bump VM_IMPORT to v0.2.5
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#900 Use root user when calling create-new-version
  deploy/Dockerfile.registry.upgrade
  deploy/Dockerfile.registry.upgrade-prev
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#902 move some code to common folder
  pkg/controller/common/hcoConditions.go
  pkg/controller/common/hco_request.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_components_test.go
  pkg/controller/hyperconverged/testUtils_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#823 Disable VMI migration upon K8s unschedulable taint
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_components_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#903 move KV and CDI to the new operand pkg
  pkg/controller/common/consts.go
  pkg/controller/common/hco_request.go
  pkg/controller/commonTestUtils/testClient.go
  pkg/controller/commonTestUtils/testUtils.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_components_test.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testClient_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cdi_test.go
  pkg/controller/operands/ensure_result.go
  pkg/controller/operands/ensure_result_test.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
  pkg/controller/operands/operand.go
  pkg/controller/operands/operands_suite_test.go
  pkg/controller/operands/testUtils_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#904 [release-1.2] Disable VMI migration upon K8s unschedulable taint (#823)
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_components_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#905 move CNA to the new operand pkg
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_components_test.go
  pkg/controller/operands/networkAddons.go
  pkg/controller/operands/networkAddons_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#906 move VM-Import to the new operand pkg
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_components_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/vmImport.go
  pkg/controller/operands/vmImport_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#907 move SSP to the new operand pkg
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_components_test.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/ssp.go
  pkg/controller/operands/ssp_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#908 move IMSConfigForCR and CliDownload to the new operand pkg
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_components_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/cliDownload.go
  pkg/controller/operands/cliDownload_test.go
  pkg/controller/operands/vmImport.go
  pkg/controller/operands/vmImport_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#909 Move ensure and delete operands to the new package
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cdi_test.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
  pkg/controller/operands/networkAddons.go
  pkg/controller/operands/networkAddons_test.go
  pkg/controller/operands/operandHandler.go
  pkg/controller/operands/ssp.go
  pkg/controller/operands/ssp_test.go
  pkg/controller/operands/vmImport.go
  pkg/controller/operands/vmImport_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L
