Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2020-12, with the labels that each got.

#975 Move the nightly build test script to the HCO repo.
  automation/nightly/test-nightly-build.sh
  hack/build-manifests.sh
  tools/digester/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#951 Make uninstall safer and faster
  pkg/apis/hco/v1alpha1/hyperconverged_webhook.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/operands/operandHandler.go
  pkg/util/util.go
  pkg/webhooks/webhooks.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#969 Provide default values for ceph RBD.
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cdi_test.go
  pkg/controller/operands/operandHandler.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#980 fix the nightly build script to use the correct images
  automation/nightly/test-nightly-build.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#984 Modify nightly build to use correct CSV version
  automation/nightly/test-nightly-build.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#981 Create Sanity Action
  .github/workflows/pr-sanity.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#983 Remove the webhook application from the operator image
  build/Dockerfile
  build/Dockerfile.okd
  build/Dockerfile.webhook
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#985 Remove travis
  .github/workflows/pr-sanity.yaml
  .travis.yml
  hack/build-tests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#978 Add monitoring and alerting resources
  cmd/hyperconverged-cluster-operator/main.go
  deploy/cluster_role.yaml
  deploy/index-image/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  go.mod
  pkg/components/components.go
  pkg/controller/commonTestUtils/testUtils.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/monitoring.go
  pkg/controller/operands/monitoring_test.go
  pkg/controller/operands/operandHandler.go
  vendor/github.com/coreos/prometheus-operator/LICENSE
  vendor/github.com/coreos/prometheus-operator/NOTICE
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/register.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/doc.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/register.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#991 try to fix some failed CI tests
  hack/run-tests.sh
  hack/test_delete_ns.sh
  hack/upgrade-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#995 Excludes CDI.Spec.Config from HCO Reconciliation Loop.
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cdi_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#989 Tiny typo fix
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#996 CI: track oc version
  hack/upgrade-openshiftci-config
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#997 Test Quickstart deployment
  build/Dockerfile.okd
  hack/run-tests.sh
  hack/testFiles/test_quickstart.yaml
  hack/test_quick_start.sh
  hack/upgrade-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#998 Patch csv-generator to workaround an OLM bug
  tools/csv-merger/csv-merger.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1000 Delete ConsoleQuickStart on HyperConverged deletion
  hack/run-tests.sh
  hack/upgrade-test.sh
  pkg/controller/commonTestUtils/testUtils.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/operands/operandHandler.go
  pkg/controller/operands/operandHandler_test.go
  pkg/controller/operands/operands_suite_test.go
  pkg/controller/operands/quickStart.go
  pkg/controller/operands/quickStart_test.go
  pkg/controller/operands/utils_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#992 Handling OVS opt-in annotation in HCO CR
  deploy/index-image/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  hack/check_upgrade_ovs.sh
  hack/upgrade-test.sh
  pkg/components/components.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/operands/networkAddons.go
  pkg/controller/operands/networkAddons_test.go
  tests/func-tests/virtual_machines_test.go
  tests/go.mod
  tests/go.sum
  tests/vendor/github.com/kubevirt/cluster-network-addons-operator/LICENSE
  tests/vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/shared/doc.go
  tests/vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/shared/networkaddonsconfig_types.go
  tests/vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/shared/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1/doc.go
  tests/vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1/networkaddonsconfig_types.go
  tests/vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1/register.go
  tests/vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1/zz_generated.deepcopy.go
  tests/vendor/sigs.k8s.io/controller-runtime/LICENSE
  tests/vendor/sigs.k8s.io/controller-runtime/pkg/scheme/scheme.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1004 CI: try to mitigate some CI issues
  hack/dump-state.sh
  hack/test_delete_ns.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1006 Bump KUBEVIRT to v0.36.0
  deploy/images.csv
  deploy/images.env
  deploy/index-image/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  hack/upgrade-test.sh
  tests/go.mod
  tests/go.sum
  tests/vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/shared/networkaddonsconfig_types.go
  tests/vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1/networkaddonsconfig_types.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1002 Revert cert config
  deploy/crds/hco00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.3.0/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/hco00.crd.yaml
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
  pkg/controller/operands/networkAddons.go
  pkg/controller/operands/networkAddons_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1010 Upgrade test: wait for CSV
  hack/upgrade-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1012 Don't run the digester bot if the "update image digests" already exists
  .github/workflows/digester_bot.yml
  .github/workflows/pr-sanity.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1018 Do not execute go mod tidy
  automation/nightly/test-nightly-build.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1023 Remove deprecated packages
  pkg/apis/hco/v1alpha1/register.go
  pkg/apis/hco/v1beta1/register.go
  pkg/controller/commonTestUtils/testUtils.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/operands/quickStart_test.go
  pkg/util/predicate/predicate.go
  pkg/webhooks/webhooks_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/log/log.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1019 get ready for 1.4.0
  deploy/index-image/bundle.Dockerfile
  deploy/index-image/kubevirt-hyperconverged/1.4.0/cluster-network-addons00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.4.0/containerized-data-importer00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.4.0/hco01.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.4.0/hco02.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.4.0/hostpath-provisioner00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/index-image/kubevirt-hyperconverged/1.4.0/kubevirt00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.4.0/metadata/annotations.yaml
  deploy/index-image/kubevirt-hyperconverged/1.4.0/node-maintenance00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.4.0/scheduling-scale-performance00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.4.0/scheduling-scale-performance01.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.4.0/scheduling-scale-performance02.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.4.0/scheduling-scale-performance03.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.4.0/vm-import-operator00.crd.yaml
  deploy/kustomize/deploy_kustomize.sh
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/cluster-network-addons00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/hco01.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/hco02.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/hostpath-provisioner00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/kubevirt00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/metadata/annotations.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/node-maintenance00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/scheduling-scale-performance00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/scheduling-scale-performance01.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/scheduling-scale-performance02.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/scheduling-scale-performance03.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/vm-import-operator00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/kubevirt-hyperconverged.package.yaml
  deploy/operator.yaml
  hack/make_local.py
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#1025 Fix digester
  automation/digester/update_images.sh
  automation/release-bumper/release-bumper.sh
  tools/digester/go.mod
  tools/digester/go.sum
  tools/digester/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1001 Add cert-manager into deploy.sh for webhooks
  .gitignore
  cmd/hyperconverged-cluster-webhook/main.go
  deploy/cert-manager.yaml
  deploy/deploy.sh
  deploy/operator.yaml
  deploy/webhooks.yaml
  hack/clean.sh
  hack/deploy.sh
  pkg/apis/hco/v1beta1/hyperconverged_webhook.go
  pkg/components/components.go
  pkg/webhooks/webhooks.go
  pkg/webhooks/webhooks_test.go
  tools/manifest-templator/manifest-templator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#1031 Fix issue in Quick-start
  pkg/controller/operands/quickStart.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS
