Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2020-11, with the labels that each got.

#912 Validate updates to the whole .spec stanza
  pkg/apis/hco/v1beta1/hyperconverged_webhook.go
  pkg/apis/hco/v1beta1/hyperconverged_webhook_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#915 Use different directory as a source for index-image test
  deploy/index-image/bundle.Dockerfile
  deploy/index-image/kubevirt-hyperconverged/1.3.0/cluster-network-addons00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.3.0/containerized-data-importer00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.3.0/hco00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.3.0/hco01.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.3.0/hco02.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.3.0/hostpath-provisioner00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/index-image/kubevirt-hyperconverged/1.3.0/kubevirt00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.3.0/metadata/annotations.yaml
  deploy/index-image/kubevirt-hyperconverged/1.3.0/node-maintenance00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.3.0/scheduling-scale-performance00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.3.0/scheduling-scale-performance01.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.3.0/scheduling-scale-performance02.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.3.0/scheduling-scale-performance03.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.3.0/vm-import-operator00.crd.yaml
  hack/build-manifests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#916 Remove a CI hack
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  hack/build-manifests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#910 Use a generic method to ensure components - CDI
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cdi_test.go
  pkg/controller/operands/operand.go
  pkg/controller/operands/operandHandler.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#920 [bump-bot] Fix go.mod version update
  README.md
  automation/release-bumper/release-bumper.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#921 Move webhook implementation to a new package
  cmd/hyperconverged-cluster-operator/main.go
  pkg/apis/hco/v1beta1/hyperconverged_webhook.go
  pkg/webhooks/webhooks.go
  pkg/webhooks/webhooks_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#919 Distinguish reconciliation requests triggered by the primary resource from ones triggered by others
  go.mod
  pkg/controller/common/hco_request.go
  pkg/controller/commonTestUtils/testUtils.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cdi_test.go
  pkg/controller/operands/ensure_result.go
  pkg/controller/operands/ensure_result_test.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
  pkg/controller/operands/networkAddons.go
  pkg/controller/operands/networkAddons_test.go
  pkg/controller/operands/operand.go
  pkg/controller/operands/operandHandler.go
  pkg/controller/operands/ssp.go
  pkg/controller/operands/ssp_test.go
  pkg/controller/operands/testUtils_test.go
  pkg/controller/operands/vmImport.go
  pkg/controller/operands/vmImport_test.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#918 Signal unsupported mode with a TaintedConfiguration condition
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/controller/common/consts.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/L

#925 Move new crs
  cmd/hyperconverged-cluster-operator/main.go
  pkg/apis/hco/v1beta1/hyperconverged_resources.go
  pkg/apis/hco/v1beta1/hyperconverged_resources_test.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cdi_test.go
  pkg/controller/operands/cliDownload.go
  pkg/controller/operands/cliDownload_test.go
  pkg/controller/operands/ensure_result_test.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
  pkg/controller/operands/networkAddons.go
  pkg/controller/operands/networkAddons_test.go
  pkg/controller/operands/operand.go
  pkg/controller/operands/operandHandler.go
  pkg/controller/operands/ssp.go
  pkg/controller/operands/ssp_test.go
  pkg/webhooks/webhooks.go
  pkg/webhooks/webhooks_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#924 fix run-local after it was broke
  cmd/hyperconverged-cluster-operator/main.go
  hack/make_local.py
  hack/make_local.sh
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#926 Use a watch predicate to filter on generation or annotation change
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/util/predicate/predicate.go
  pkg/util/predicate/predicate_suite_test.go
  pkg/util/predicate/predicate_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/L

#929 [release-1.2] Hide nodePlacement APIs from the UI
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/kubevirt-hyperconverged-operator.v1.2.0.clusterserviceversion.yaml
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#928 Change CNA handler to use the genreric ensure method
  pkg/controller/operands/networkAddons.go
  pkg/controller/operands/networkAddons_test.go
  pkg/controller/operands/operandHandler.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#930 Bump KUBEVIRT to v0.35.0
  deploy/index-image/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#931 Change KV handler to use the genreric ensure method
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
  pkg/controller/operands/operand.go
  pkg/controller/operands/operandHandler.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#914 Added certificate rotation config to HCO CR
  deploy/crds/hco00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.3.0/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/controller/operands/networkAddons.go
  pkg/controller/operands/networkAddons_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#932 @nunnatsa Change KV Config & Priority class handlers to use the genreric ensure method
  pkg/controller/operands/cdi.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
  pkg/controller/operands/networkAddons.go
  pkg/controller/operands/operand.go
  pkg/controller/operands/operandHandler.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#933 Validate a CR update with all the operators
  pkg/webhooks/webhooks.go
  pkg/webhooks/webhooks_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#937 Add Andrey, Erkan and Zvi
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#934 Change VM Import handler to use the genreric ensure method
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/operand.go
  pkg/controller/operands/operandHandler.go
  pkg/controller/operands/vmImport.go
  pkg/controller/operands/vmImport_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#938 Change SSP handlers to use the genreric ensure method
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/operand.go
  pkg/controller/operands/ssp.go
  pkg/controller/operands/ssp_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#939 Fix nil address panic in webhook
  pkg/apis/hco/v1beta1/hyperconverged_webhook.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#940 Split hooks and field in handlers
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cdi_test.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
  pkg/controller/operands/networkAddons.go
  pkg/controller/operands/networkAddons_test.go
  pkg/controller/operands/operand.go
  pkg/controller/operands/operandHandler.go
  pkg/controller/operands/ssp.go
  pkg/controller/operands/ssp_test.go
  pkg/controller/operands/vmImport.go
  pkg/controller/operands/vmImport_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#941 Refresh hyperconverged-cluster-operator:1.3.0
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#936 Add Prometheus metric for out-of-band modifications to secondary resources
  go.mod
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/operandHandler.go
  pkg/metrics/metrics.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/L

#942 Call the sub-component webhooks in parallel
  hack/build-manifests.sh
  hack/run-tests.sh
  pkg/webhooks/webhooks.go
  pkg/webhooks/webhooks_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#944 Fix the Release Bumper Bot
  .github/workflows/release-bumper.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#946 Use a fully qualified finalizer name
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#948 Try to fix #947, by using yamllint in container
  hack/build-manifests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#945 Digester
  .github/workflows/digester_bot.yml
  automation/digester/update_images.sh
  deploy/images.csv
  deploy/images.env
  tools/digester/.gitignore
  tools/digester/go.mod
  tools/digester/go.sum
  tools/digester/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#950 Use pre-prepared list of image digests to build the CSV
  .github/workflows/digester_bot.yml
  .github/workflows/release-bumper.yml
  automation/release-bumper/release-bumper.sh
  deploy/index-image/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/build-manifests.sh
  tools/digester/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#952 Fix issues in developer workflow doc
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#955 Fix the bump version bot
  automation/release-bumper/release-bumper.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#949 Add a mutating webhook to protect hco namespace
  deploy/index-image/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  hack/test_delete_ns.sh
  hack/upgrade-test.sh
  pkg/apis/hco/v1beta1/hyperconverged_webhook.go
  pkg/components/components.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/util/consts.go
  pkg/webhooks/webhooks.go
  pkg/webhooks/webhooks_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#956 Remove workarounds on namespace deletion test
  hack/test_delete_ns.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#957 Reconcile certificate configuration for KubeVirt
  deploy/crds/hco00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.3.0/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
  pkg/controller/operands/networkAddons.go
  pkg/controller/operands/networkAddons_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#962 add new app for webhook
  Makefile
  build/Dockerfile.webhook
  cmd/hyperconverged-cluster-webhook/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#965 [Release Bump Bot] Exit on Error
  automation/release-bumper/release-bumper.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#967 Add webhook to the image in order to have a working image for next phase tests
  build/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#960 Split the webhook out of the operator to its own application
  Makefile
  build/Dockerfile
  build/Dockerfile.okd
  build/Dockerfile.webhook
  build/bin/entrypoint
  cmd/hyperconverged-cluster-operator/main.go
  deploy/index-image/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/dump-state.sh
  pkg/components/components.go
  pkg/util/consts.go
  pkg/util/util.go
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#973 Preperations for splitting the webhook to a new image
  automation/release-bumper/release-bumper.sh
  build/Dockerfile.wh.okd
  deploy/Dockerfile.registry.kubevirt.nightly
  deploy/Dockerfile.registry.upgrade
  deploy/Dockerfile.registry.upgrade-prev
  hack/build-manifests.sh
  tools/digester/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#974 Use the new webhook image in deployment/CI/CSV
  build/Dockerfile.webhook
  cluster/sync.sh
  deploy/images.csv
  deploy/images.env
  deploy/index-image/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/deploy.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#976 Use OPERATOR_NAME/OPERATOR_NAMESPACE envvars in build-manifests.sh
  hack/build-manifests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
