Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2020-03, with the labels that each got.

#481 Improve upgrade test suite
  README.md
  deploy/deploy_imageregistry.sh
  hack/build-registry-bundle.sh
  hack/deploy.sh
  hack/dump-state.sh
  hack/upgrade-openshiftci-config
  hack/upgrade-stdci-config
  hack/upgrade-test-build-images.sh
  hack/upgrade-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#466 bump SSP to v1.0.23
  deploy/cluster_role.yaml
  deploy/crds/scheduling-scale-performance00.crd.yaml
  deploy/crds/scheduling-scale-performance01.crd.yaml
  deploy/crds/scheduling-scale-performance02.crd.yaml
  deploy/crds/scheduling-scale-performance03.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/kubevirt-hyperconverged-operator.v1.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/scheduling-scale-performance00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/scheduling-scale-performance01.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/scheduling-scale-performance02.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/scheduling-scale-performance03.crd.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/build-manifests.sh
  hack/config
  hack/defaults
  pkg/components/components.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/apis/kubevirt/v1/register.go
  vendor/modules.txt
Labels: dco-signoff: yes, do-not-merge/hold, lgtm, release-note, size/M

#487 Fix the CSV version to 1.0.0 on release-2.3 branch
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/kubevirt-hyperconverged-operator.v1.0.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/build-manifests.sh
  hack/deploy.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#484 feature: make hco crd a singleton
  cmd/hyperconverged-cluster-operator/main.go
  deploy/crds/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/kubevirt-hyperconverged-operator.v1.0.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.sum
  pkg/apis/hco/v1alpha1/hyperconverged_types.go
  pkg/components/components.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/util/util.go
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#489 [release-2.3] feature: make hco crd a singleton
  cmd/hyperconverged-cluster-operator/main.go
  deploy/crds/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/kubevirt-hyperconverged-operator.v1.0.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.sum
  pkg/apis/hco/v1alpha1/hyperconverged_types.go
  pkg/components/components.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/util/util.go
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
Labels: dco-signoff: yes, release-note, size/L

#479 Hide internal CRDs
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/kubevirt-hyperconverged-operator.v1.0.0.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#490 [release-2.3] Hide internal CRDs
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/kubevirt-hyperconverged-operator.v1.0.0.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: dco-signoff: yes, release-note, size/M

#492 Hide also VMware v2v CRD from OLM UI
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/kubevirt-hyperconverged-operator.v1.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: dco-signoff: yes, lgtm, release-note-none, size/S

#493 [release-2.3] Hide also VMware v2v CRD from OLM UI
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/kubevirt-hyperconverged-operator.v1.0.0.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: dco-signoff: yes, release-note-none, size/XS

#485 Emit a warning event on failed uninstall
  cmd/hyperconverged-cluster-operator/main.go
  deploy/cluster_role.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/kubevirt-hyperconverged-operator.v1.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  pkg/components/components.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/util/util.go
Labels: dco-signoff: yes, lgtm, release-note, size/L

#354 Fix typo
  docs/kni.md
Labels: dco-signoff: yes, release-note-none, size/XS

#496 Add pull request template to write release note
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#497 Let the user set a custom value for smbios at CSV level
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/build-manifests.sh
  pkg/components/components.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, lgtm, size/L

#499 BZ 1768751: Add Web UI to rotate-certs.sh
  tools/rotate-certs.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#503 fix rotate-certs.sh Web UI namespace
  tools/rotate-certs.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#501 remove CNV from cert-rotate README
  tools/README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#502 updating script to allow for proxy environment usecases
  tools/mirror-csv-release/mirror_csv_release.sh
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/M

#504 Add forgotten webui_namespace variable
  tools/rotate-certs.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#495 Correct behaviour for ocp-* providers.
  cluster/sync.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#507 bump SSP to v1.0.26
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/build-manifests.sh
  hack/config
  hack/defaults
  vendor/modules.txt
Labels: dco-signoff: yes, lgtm, release-note, size/S

#509 Enable 1.0.0 -> 1.1.0 upgrade path
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  hack/build-manifests.sh
  version/version.go
Labels: dco-signoff: yes, lgtm, release-note-none, size/XS

#511 Increase all the tests timeouts by 50%
  hack/defaults
  hack/deploy.sh
  hack/run-tests.sh
  tests/func-tests/certificates_test.go
  tests/func-tests/virtual_machines_test.go
  tools/rotate-certs.sh
Labels: dco-signoff: yes, lgtm, release-note-none, size/M

#513 bump SSP to v1.0.28
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/build-manifests.sh
  hack/config
  hack/defaults
  vendor/modules.txt
Labels: dco-signoff: yes, lgtm, release-note-none, size/S

#514 change TARGET to TARGET_NAMESPACE in cleanup_marketplace.sh to match deploy_marketplace.sh
  deploy/cleanup_marketplace.sh
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/S

#508 Fix missing "Available" condition bug
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#515 Add a new simple, positive only test for HCO deletion
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M
