Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2020-01, with the labels that each got.

#397 Comment out ssp cert rotation for now
  tests/func-tests/certificates_test.go
Labels: dco-signoff: yes, ok-to-test, size/M

#392 Add GIT_URL and GIT_SHA to docker labels
  Makefile
  build/Dockerfile
Labels: dco-signoff: yes, size/S

#396 Add a script to cleanup the environment after marketplace deployment
  deploy/cleanup_marketplace.sh
Labels: dco-signoff: yes, size/S

#393 Don't create problematic ownerReferences for CDI and NetworkAddonsConfig
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: dco-signoff: yes, size/L

#402 Check code formatting in CI
  .travis.yml
  Makefile
  pkg/controller/hyperconverged/hyperconverged_controller.go
  tests/func-tests/csv_tests.go
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
Labels: dco-signoff: yes, size/L

#400 Ignore invalid requests
  .gitignore
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/kubevirt-hyperconverged-operator.v1.0.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/components/components.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
Labels: dco-signoff: yes, size/L

#405 Improve OperatorGroup count check in deploy_marketplace.sh
  deploy/deploy_marketplace.sh
Labels: dco-signoff: yes, ok-to-test, size/XS

#404 Avoid creating the OperatorSource if already there
  deploy/deploy_marketplace.sh
Labels: dco-signoff: yes, ok-to-test, size/XS

#399 Let the user set a custom namespace in alm-example at CSV compose time
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/kubevirt-hyperconverged-operator.v1.0.0.clusterserviceversion.yaml
  pkg/components/components.go
  tools/csv-merger/csv-merger.go
Labels: dco-signoff: yes, size/XS

#407 Additional custom values for CSV generator
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/kubevirt-hyperconverged-operator.v1.0.0.clusterserviceversion.yaml
  hack/build-manifests.sh
  pkg/components/components.go
  tools/csv-merger/csv-merger.go
Labels: dco-signoff: yes, size/M

#410 Set KVM_EMULATION in deploy_marketplace.sh and deploy_imageregistry.sh
  deploy/deploy_imageregistry.sh
  deploy/deploy_marketplace.sh
Labels: dco-signoff: yes, size/M

#411 increase timeout to 15 mins
  deploy/deploy_imageregistry.sh
  deploy/deploy_marketplace.sh
Labels: dco-signoff: yes, size/XS

#414 Add 'go mod vendor' to sanity tests
  .travis.yml
  Makefile
Labels: dco-signoff: yes, size/XS

#415 Skip OperatorGroup creation with CONTENT_ONLY option
  deploy/deploy_imageregistry.sh
  deploy/deploy_marketplace.sh
Labels: dco-signoff: yes, size/M

#418 Set spec.targetNamespaces from deploy scripts
  deploy/deploy_imageregistry.sh
  deploy/deploy_marketplace.sh
Labels: dco-signoff: yes, size/XS

#417 Correctly wait for a successful deployment
  deploy/deploy_imageregistry.sh
  deploy/deploy_marketplace.sh
Labels: dco-signoff: yes, size/XS

#419 removing 'PHASE' column on 'oc get hco' command
  deploy/crds/hco.crd.yaml
  pkg/components/components.go
Labels: dco-signoff: yes, size/XS
