Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2020-02, with the labels that each got.

#421 Use "kubevirt-hyperconverged" as the hco resource name
  deploy/cleanup_marketplace.sh
  deploy/deploy_imageregistry.sh
  deploy/deploy_marketplace.sh
  deploy/hco.cr.yaml
  hack/check-state.sh
  hack/clean.sh
  hack/deploy.sh
  hack/dump-state.sh
  hack/upgrade-test.sh
  pkg/components/components.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
Labels: dco-signoff: yes, size/M

#425 Fix the name of hyperconverged resource in deploy scripts
  deploy/deploy_imageregistry.sh
  deploy/deploy_marketplace.sh
Labels: dco-signoff: yes, size/XS

#424 Adjust rotate script for older HCO installations
  hack/run-tests.sh
  tests/func-tests/certificates_test.go
  tools/rotate-certs.sh
Labels: dco-signoff: yes, size/M

#427 Change the configmap default to Filesystem/ReadWriteOnce
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
Labels: dco-signoff: yes, size/S

#429 bug: do not reconcile status updates
  pkg/controller/hyperconverged/hyperconverged_controller.go
  vendor/github.com/operator-framework/operator-sdk/pkg/predicate/predicate.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/M

#437 Remove STDCI
  automation/check-patch.k8s-1.15.1.mounts
  automation/check-patch.k8s-1.15.1.packages
  automation/check-patch.k8s-1.15.1.sh
  automation/check-patch.mounts
  automation/check-patch.okd-4.1.mounts
  automation/check-patch.okd-4.1.packages
  automation/check-patch.okd-4.1.sh
  automation/check-patch.packages
  automation/check-patch.sh
  stdci.yaml
Labels: dco-signoff: yes, lgtm, release-note-none, size/M

#442 Avoid failing the whole upgrade test on "$RECONCILE_COMPLETED" = 'Unknown'
  hack/check-state.sh
Labels: dco-signoff: yes, lgtm, release-note-none, size/XS

#441 Add owner files to be compliant with other projects
  OWNERS
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#433 Allow custom names for relatedImages
  tools/csv-merger/csv-merger.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#443 Bump fedora base image used for tests
  tests/build/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#439 Add a tool to mirror the whole release starting from the CSV
  tools/mirror-csv-release/Dockerfile
  tools/mirror-csv-release/Dockerfile_appregistry
  tools/mirror-csv-release/README.md
  tools/mirror-csv-release/mirror_csv_release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#445 Add selinuxLauncherType to kubevirt configmap
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: dco-signoff: yes, lgtm, release-note, size/XS

#451 Set default value (BlockUninstallIfWorkloadsExist) for UninstallStrategy on Kubevirt
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
Labels: dco-signoff: yes, lgtm, release-note, size/M

#453 Generate HCO CRDs from csv-merger and remove templates
  build/Dockerfile
  deploy/crds/hco00.crd.yaml
  deploy/crds/hco01.crd.yaml
  deploy/deploy.sh
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/hco01.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/kubevirt-hyperconverged-operator.v1.0.0.clusterserviceversion.yaml
  hack/build-manifests.sh
  templates/cluster_role.yaml.in
  templates/cluster_role_binding.yaml.in
  templates/crds/cdi.crd.yaml.in
  templates/crds/cna.crd.yaml.in
  templates/crds/common-template-bundles.crd.yaml.in
  templates/crds/hco.crd.yaml.in
  templates/crds/kubevirt.crd.yaml.in
  templates/crds/metrics-aggregation.crd.yaml.in
  templates/crds/node-labeller-bundles.crd.yaml.in
  templates/crds/nodemaintenance.crd.yaml.in
  templates/crds/template-validator.crd.yaml.in
  templates/crds/v2vvmware.crd.yaml.in
  templates/hco.cr.yaml.in
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
  templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion_merger.yaml.in
  templates/olm-catalog/kubevirt-hyperconverged/kubevirt-hyperconverged.package.yaml.in
  templates/operator.yaml.in
  templates/service_account.yaml.in
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
Labels: dco-signoff: yes, lgtm, release-note, size/XXL

#461 Adding SuggestedNamespace annotation in HCO CSV for OLM
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/kubevirt-hyperconverged-operator.v1.0.0.clusterserviceversion.yaml
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#460 Upgrade go to the latest version (1.13.8) + Dockerfile refactoring
  build/Dockerfile
  build/bin/user_setup
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#462 Include manifest generation in sanity tests
  Makefile
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#467 [release-2.3] Adding SuggestedNamespace annotation in HCO CSV for OLM
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/kubevirt-hyperconverged-operator.v1.0.0.clusterserviceversion.yaml
  pkg/components/components.go
Labels: dco-signoff: yes, release-note-none, size/XS

#469 Give more time to HCO to become ready
  hack/deploy.sh
Labels: dco-signoff: yes, lgtm, release-note-none, size/XS

#472 Bump CDI to v1.13.1
  deploy/cluster_role.yaml
  deploy/crds/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/kubevirt-hyperconverged-operator.v1.0.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/build-manifests.sh
  hack/config
  hack/defaults
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/deepcopy_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types.go
  vendor/modules.txt
Labels: dco-signoff: yes, lgtm, release-note, size/L

#474 [release-2.3] Bump CDI to v1.13.1
  deploy/cluster_role.yaml
  deploy/crds/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/kubevirt-hyperconverged-operator.v1.0.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/build-manifests.sh
  hack/config
  hack/defaults
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/deepcopy_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types.go
  vendor/modules.txt
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, lgtm, size/L

#473 Set default value (BlockUninstallIfWorkloadsExist) for UninstallStrategy on CDI
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#457 bump CNAO to 0.27.2
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/kubevirt-hyperconverged-operator.v1.0.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/build-manifests.sh
  hack/config
  hack/defaults
  vendor/modules.txt
Labels: dco-signoff: yes, lgtm, release-note, size/M

#477 [release-2.3] Bump CNAO to 0.27.2
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/kubevirt-hyperconverged-operator.v1.0.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/build-manifests.sh
  hack/config
  hack/defaults
  vendor/modules.txt
Labels: dco-signoff: yes, lgtm, release-note, size/M

#449 Avoid InstallModeTypeMultiNamespace and InstallModeTypeAllNamespaces
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/kubevirt-hyperconverged-operator.v1.0.0.clusterserviceversion.yaml
  hack/dump-state.sh
  hack/upgrade-test.sh
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#480 [release-2.3] Avoid InstallModeTypeMultiNamespace and InstallModeTypeAllNamespaces
  deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/kubevirt-hyperconverged-operator.v1.0.0.clusterserviceversion.yaml
  hack/dump-state.sh
  hack/upgrade-test.sh
  pkg/components/components.go
Labels: dco-signoff: yes, release-note, size/M
