Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2020-06, with the labels that each got.

#607 Bump to v1.2.0
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/cluster-network-addons00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/hco01.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/hco02.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/hostpath-provisioner00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/kubevirt-hyperconverged-operator.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/kubevirt00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/node-maintenance00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/scheduling-scale-performance00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/scheduling-scale-performance01.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/scheduling-scale-performance02.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/scheduling-scale-performance03.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/vm-import-operator00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/kubevirt-hyperconverged.package.yaml
  deploy/operator.yaml
  hack/build-manifests.sh
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#609 Fix bug 1839837 were HCO updates fails duo to previous update.
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testClient_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#598 Rebase Bot
  .github/workflows/rebase-bot.yml
  automation/rebase-bot/rebase-bot.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#612 changing the rebase script to executable
  automation/rebase-bot/rebase-bot.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#614 Split huge test file into smaller files
  pkg/controller/hyperconverged/hyperconverged_controller_components_test.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#610 Add validating webhook
  cmd/hyperconverged-cluster-operator/main.go
  deploy/cluster_role.yaml
  deploy/crds/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/kubevirt-hyperconverged-operator.v1.2.0.clusterserviceversion.yaml
  hack/deploy.sh
  pkg/apis/hco/v1alpha1/hyperconverged_webhook.go
  pkg/apis/hco/v1alpha1/hyperconverged_webhook_test.go
  pkg/components/components.go
  pkg/util/consts.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/.gitignore
  vendor/sigs.k8s.io/controller-runtime/.golangci.yml
  vendor/sigs.k8s.io/controller-runtime/CONTRIBUTING.md
  vendor/sigs.k8s.io/controller-runtime/FAQ.md
  vendor/sigs.k8s.io/controller-runtime/Makefile
  vendor/sigs.k8s.io/controller-runtime/OWNERS
  vendor/sigs.k8s.io/controller-runtime/OWNERS_ALIASES
  vendor/sigs.k8s.io/controller-runtime/README.md
  vendor/sigs.k8s.io/controller-runtime/SECURITY_CONTACTS
  vendor/sigs.k8s.io/controller-runtime/TMP-LOGGING.md
  vendor/sigs.k8s.io/controller-runtime/VERSIONING.md
  vendor/sigs.k8s.io/controller-runtime/alias.go
  vendor/sigs.k8s.io/controller-runtime/code-of-conduct.md
  vendor/sigs.k8s.io/controller-runtime/doc.go
  vendor/sigs.k8s.io/controller-runtime/go.mod
  vendor/sigs.k8s.io/controller-runtime/go.sum
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/conversion/conversion.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/conversion/conversion.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/conversion/decoder.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#617 Add the "all" category to HCO CRD
  deploy/crds/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/hco00.crd.yaml
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#619 Update openshift-ci test assets
  deploy/nightly-bundle/Dockerfile
  deploy/nightly-bundle/kubevirt-tests-pod-spec-override.json.in
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#616 Add missing fields, required by OLM
  pkg/apis/hco/v1alpha1/hyperconverged_types.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_components_test.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#621 [release-2.4] Bump kubevirt v0.30.0 rc.2
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  vendor/kubevirt.io/client-go/api/v1/openapi_generated.go
  vendor/kubevirt.io/client-go/api/v1/schema.go
  vendor/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  vendor/kubevirt.io/client-go/api/v1/types.go
  vendor/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  vendor/kubevirt.io/kubevirt/pkg/container-disk/container-disk.go
  vendor/kubevirt.io/kubevirt/pkg/util/util.go
  vendor/kubevirt.io/kubevirt/pkg/virt-config/config-map.go
  vendor/kubevirt.io/kubevirt/pkg/virt-config/virt-config.go
  vendor/kubevirt.io/kubevirt/pkg/virt-controller/services/template.go
  vendor/kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/api/converter.go
  vendor/kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/api/defaults.go
  vendor/kubevirt.io/kubevirt/pkg/virt-operator/creation/components/crds.go
  vendor/kubevirt.io/kubevirt/pkg/virt-operator/creation/components/deployments.go
  vendor/kubevirt.io/kubevirt/pkg/virt-operator/creation/components/scc.go
  vendor/kubevirt.io/kubevirt/pkg/virt-operator/util/BUILD.bazel
  vendor/kubevirt.io/kubevirt/pkg/virt-operator/util/config.go
  vendor/kubevirt.io/kubevirt/tests/BUILD.bazel
  vendor/kubevirt.io/kubevirt/tests/utils.go
  vendor/kubevirt.io/kubevirt/tools/vms-generator/utils/utils.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#620 [release-2.4] Bump SSP to v1.0.36
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#622 [release-2.4] Add missing fields, required by OLM
  pkg/apis/hco/v1alpha1/hyperconverged_types.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#627 Aling v1.1.0 CSV with the content of release-2.4 branch
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#625 prevent bots running on forks
  .github/workflows/rebase-bot.yml
  .github/workflows/release-bumper.yml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#629 prevent workflows running on forks - fix
  .github/workflows/rebase-bot.yml
  .github/workflows/release-bumper.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#631 Improve the upgrade detection
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#633 Bump VMWARE_CONTAINER_VERSION to v2.0.0-4
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/kubevirt-hyperconverged-operator.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/config
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#637 [release-2.4] Bump VM_IMPORT to v0.0.3 (#630)
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/cloud.google.com/go/compute/metadata/metadata.go
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/github.com/golang/protobuf/proto/lib.go
  vendor/github.com/golang/protobuf/proto/text.go
  vendor/github.com/kubevirt/vm-import-operator/pkg/apis/v2v/v1alpha1/virtualmachineimport_types.go
  vendor/github.com/kubevirt/vm-import-operator/pkg/apis/v2v/v1alpha1/vmimportconfig_types.go
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/transport.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_linux_mips64x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_386.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_386.go
  vendor/golang.org/x/sys/unix/ztypes_linux_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mipsle.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_s390x.go
  vendor/golang.org/x/sys/unix/ztypes_linux_sparc64.go
  vendor/google.golang.org/genproto/googleapis/rpc/status/status.pb.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#578 Use custom SELinux launcher type for virt-launcher
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#641 Modify test assets to test on ocp-4.5
  deploy/nightly-bundle/Dockerfile
  deploy/nightly-bundle/kubevirt-tests-pod-spec-override.json.in
Labels: dco-signoff: yes, lgtm, release-note-none, size/XS

#642 Bump KUBEVIRT to v0.30.1 [Release 2.4]
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/kubevirt.io/kubevirt/tests/utils.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#623 [release-2.4] Add the "all" category to HCO CRD (#617)
  deploy/crds/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/hco00.crd.yaml
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#647 Bump SSP to v1.0.37 (#646) [Release 2.4]
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  vendor/github.com/MarSik/kubevirt-ssp-operator/pkg/apis/kubevirt/v1/types.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#650 [release-2.4] Bump CDI to v1.19.0 (#648)
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/github.com/openshift/custom-resource-status/conditions/v1/doc.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/BUILD.bazel
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/upload/v1alpha1/BUILD.bazel
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/upload/v1alpha1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/upload/v1alpha1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/upload/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#651 Bump NETWORK_ADDONS to 0.39.1
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/kubevirt-hyperconverged-operator.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  hack/upgrade-test.sh
  pkg/controller/hyperconverged/hyperconverged_controller.go
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/README.md
  vendor/github.com/emicklei/go-restful/path_processor.go
  vendor/github.com/emicklei/go-restful/response.go
  vendor/github.com/go-openapi/jsonreference/go.mod
  vendor/github.com/go-openapi/jsonreference/go.sum
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#652 [release-2.4] Bump NETWORK_ADDONS to 0.39.1
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  hack/upgrade-test.sh
  pkg/controller/hyperconverged/hyperconverged_controller.go
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/README.md
  vendor/github.com/emicklei/go-restful/path_processor.go
  vendor/github.com/emicklei/go-restful/response.go
  vendor/github.com/go-openapi/jsonreference/go.mod
  vendor/github.com/go-openapi/jsonreference/go.sum
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#656 [release-2.4] Bump VMWARE_CONTAINER_VERSION to v2.0.0-4 (#633)
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/config
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#653 Deployment using kustomize on main README
  README.md
  deploy/kustomize/README.md
  deploy/kustomize/namespace.yaml
  hack/upgrade-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#628 Track changes on SCC
  automation/test.sh
  hack/compare_scc.sh
  hack/deploy.sh
  hack/upgrade-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#657 Bump SSP to Version v1.0.38
  deploy/cluster_role.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/kubevirt-hyperconverged-operator.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/build-manifests.sh
  hack/config
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#659 [Release 2.4] Bump SSP to Version v1.0.38 (#657)
  deploy/cluster_role.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/build-manifests.sh
  hack/config
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#664 [Release 2.4] Bump NETWORK_ADDONS to 0.39.2 (#663)
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#665 [Release 2.4] Bump KUBEVIRT to v0.30.2 (#660)
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/kubevirt.io/kubevirt/pkg/virtctl/pause/pause.go
  vendor/kubevirt.io/kubevirt/tests/BUILD.bazel
  vendor/kubevirt.io/kubevirt/tests/utils.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#654 Allow running HCO locally, for development and debug
  .gitignore
  Makefile
  cmd/hyperconverged-cluster-operator/main.go
  deploy/deploy.sh
  docs/run-locally.md
  hack/make_local.py
  hack/make_local.sh
  images/local_goland_env.png
  images/run_local_from_goland.png
  images/run_local_from_vscode.png
  images/running_local_from_goland.png
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/signals/signal.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#667 Bump SSP to v1.0.39
  deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/kubevirt-hyperconverged-operator.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#671 [Release 2.4] Bump SSP to v1.0.39 (#667)
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#669 Create a PriorityClass for KubeVirt on startup
  cmd/hyperconverged-cluster-operator/main.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_components_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/util/util.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#672 [release-2.4] Bump CDI to v1.18.1
  deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/kubevirt-hyperconverged-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/BUILD.bazel
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/deepcopy_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/upload/v1alpha1/BUILD.bazel
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/upload/v1alpha1/deepcopy_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/upload/v1alpha1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/upload/v1alpha1/types.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL
