Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2021-02, with the labels that each got.

#1104 Fix code smells reported by SonarCloud
  pkg/components/components.go
  pkg/controller/common/hcoConditions.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/webhooks/webhooks.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1116 Remove HyperConverged v1alpha1 API
  deploy/crds/hco00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  pkg/apis/hco/v1alpha1/doc.go
  pkg/apis/hco/v1alpha1/hyperconverged_resources.go
  pkg/apis/hco/v1alpha1/hyperconverged_types.go
  pkg/apis/hco/v1alpha1/hyperconverged_types_test.go
  pkg/apis/hco/v1alpha1/hyperconverged_webhook.go
  pkg/apis/hco/v1alpha1/hyperconverged_webhook_test.go
  pkg/apis/hco/v1alpha1/register.go
  pkg/apis/hco/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/hco/v1alpha1/zz_generated.defaults.go
  pkg/apis/hco/v1alpha1/zz_generated.openapi.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1117 Reduce sonarCloud duplecation warnings
  pkg/controller/commonTestUtils/testUtils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1113 Fix the Default Values in the FeatureGates field
  deploy/crds/hco00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  pkg/apis/hco/v1beta1/hyperconverged_types.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1114 Refactor ReconcileHyperConverged.Reconcile()
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1120 Move cmds' common code to a new package
  cmd/cmdcommon/cmdcommon.go
  cmd/hyperconverged-cluster-operator/main.go
  cmd/hyperconverged-cluster-webhook/main.go
  pkg/util/util.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1123 [release-1.3] Bump gogo/protobuf to fix a security issue
  go.mod
  go.sum
  vendor/github.com/gogo/protobuf/proto/text_parser.go
  vendor/golang.org/x/tools/go/internal/gcimporter/gcimporter.go
  vendor/golang.org/x/tools/go/internal/packagesdriver/sizes.go
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/go/packages/visit.go
  vendor/golang.org/x/tools/internal/event/core/event.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/gocommand/version.go
  vendor/golang.org/x/tools/internal/packagesinternal/packages.go
  vendor/golang.org/x/tools/internal/typesinternal/errorcode.go
  vendor/golang.org/x/tools/internal/typesinternal/errorcode_string.go
  vendor/golang.org/x/tools/internal/typesinternal/types.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1122 Add SRIOV Live Migration feature-gate to HyperConverged CR
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/hyperconverged_types_test.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1115 Introduce a test container for func-tests
  Makefile
  build/Dockerfile.functest
  hack/common.sh
  hack/run-tests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1126 Fix typo
  cmd/hyperconverged-cluster-operator/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1127 Remove leftover exit
  hack/run-tests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1130 Bump CDI to version v1.30.0
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  tools/digester/main.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1132 Fix nightly builds
  automation/nightly/test-nightly-build.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1129 Add missing binaries into test container
  build/Dockerfile.functest
  hack/run-tests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1133 Add new make target for running tests in pod
  Makefile
  hack/run-tests-in-container.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1136 Remove BareMetalPlatform from spec
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/kustomize/base/hco_cr.yaml
  deploy/nightly-bundle/deploy.sh
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  docs/kni.md
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/components/components.go
  pkg/controller/operands/cdi_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1125 Refactor controller registration code to reduce boilerplating
  cmd/hyperconverged-cluster-operator/main.go
  pkg/controller/add_hyperconverged.go
  pkg/controller/controller.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1138 Fix a bug where HCO failed to trigger some events
  pkg/apis/hco/v1beta1/hyperconverged_types_test.go
  pkg/controller/commonTestUtils/eventEmitterMock.go
  pkg/controller/commonTestUtils/testClient.go
  pkg/controller/commonTestUtils/testUtils.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/operandHandler.go
  pkg/controller/operands/operandHandler_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#1139 Fix --csv-overrides flag
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  hack/build-manifests.sh
  tools/csv-merger/csv-merger.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1094 add default for HypervStrictCheck featureGate
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  docs/cluster-configuration.md
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/hyperconverged_types_test.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1143 Add OvS Opt-In and jsonpatch annotations documentation
  docs/cluster-configuration.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1142 Change the InstallMode of HCO Operator to AllNamespaces
  README.md
  cmd/cmdcommon/cmdcommon.go
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/kustomize/base/operator_group.yaml
  deploy/nightly-bundle/deploy.sh
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  docs/cluster-configuration.md
  hack/kubevirt-nightly-test.sh
  hack/patch_og.sh
  hack/upgrade-test.sh
  pkg/components/components.go
  pkg/util/consts.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1140 Add some more unit tests to increase the coverage
  pkg/controller/common/common_test.go
  pkg/controller/common/hcoConditions_test.go
  pkg/controller/common/hcoRequest.go
  pkg/controller/common/hcoRequest_test.go
  pkg/controller/commonTestUtils/testClient.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cdi_test.go
  pkg/controller/operands/cliDownload_test.go
  pkg/controller/operands/operandHandler_test.go
  pkg/webhooks/webhooks.go
  pkg/webhooks/webhooks_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#1146 fix test descriptions
  pkg/apis/hco/v1beta1/hyperconverged_types_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1145 Add GPU and HostDevices Feature Gates to HCO
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/hyperconverged_types_test.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1147 Add explicit defaults for sriovLiveMigration and hotplugVolumes FGs
  deploy/crds/hco00.crd.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/apis/hco/v1beta1/hyperconverged_types.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1152 Force go 1.15.8 on github action for consistency
  .github/workflows/pr-sanity.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
