Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2021-07, with the labels that each got.

#1424 Reduce the number of the sonar-cloud warnings
  cmd/hyperconverged-cluster-operator/main.go
  hack/strip_old_descriptions.py
  tools/docgen/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1413 Remove the spec.version field as it's not needed anymore
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/hco00.crd.yaml
  docs/api.md
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/hyperconverged_types_test.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1420 Add workflow for dashboard configmaps
  .github/workflows/dashboard-updater.yml
  automation/dashboard-updater/dashboard-updater.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1427 Set PriorityClass for the two deployments
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1428 Move dashboard configmaps to /assets folder
  .github/workflows/dashboard-updater.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1430 Fix periodic-hco-push-nightly-build-main automation
  automation/nightly/test-nightly-build.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1425 Add alert for unsafe modifications
  docs/cluster-configuration.md
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/monitoring.go
  pkg/metrics/metrics.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1412 Test that VM created before upgrade, is still runninig after the upgrade is done
  hack/upgrade-test-index-image.sh
  hack/vm.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1418 add new API field CommonTemplatesNamespace
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/zz_generated.deepcopy.go
  pkg/apis/hco/v1beta1/zz_generated.openapi.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/ssp.go
  pkg/controller/operands/ssp_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1432 Handle two todo comments to reduce sonarCloud warnings
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  pkg/components/components.go
  tools/csv-merger/csv-merger.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1421 Add new controller for dashboard configmaps
  build/Dockerfile.okd
  cmd/hyperconverged-cluster-operator/main.go
  hack/run-tests-in-container.sh
  hack/run-tests.sh
  hack/testFiles/test_config.yaml
  hack/testFiles/test_dashboard_cm.yaml
  pkg/controller/commonTestUtils/file.go
  pkg/controller/operands/dashboard.go
  pkg/controller/operands/dashboard_test.go
  pkg/controller/operands/operandHandler.go
  pkg/controller/operands/operandHandler_test.go
  pkg/controller/operands/quickStart.go
  pkg/controller/operands/quickStart_test.go
  pkg/controller/operands/testFiles/dashboards/kubevirt-top-consumers.yaml
  pkg/controller/operands/testFiles/quickstarts/quickstart.yaml
  pkg/util/error.go
  pkg/util/file.go
  tests/func-tests/config.go
  tests/func-tests/dashboard_test.go
  tests/func-tests/quickstart_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1437 Add dashboard configmaps into operator container
  build/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1438 Set KVM_EMULATION during upgrade tests if required
  hack/upgrade-test-index-image.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1439 Cleanup testvm
  hack/testvm.yaml
  hack/vm.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1440 Change operator's LeaderElectionResourceLock to "configmapsleases"
  cmd/hyperconverged-cluster-operator/main.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1441 Move rbacs for config reader to a separate handler
  cmd/hyperconverged-cluster-operator/main.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cdi_test.go
  pkg/controller/operands/cliDownload.go
  pkg/controller/operands/dashboard.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/monitoring.go
  pkg/controller/operands/networkAddons.go
  pkg/controller/operands/operand.go
  pkg/controller/operands/operandHandler.go
  pkg/controller/operands/quickStart.go
  pkg/controller/operands/ssp.go
  pkg/controller/operands/vmImport.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1431 check uptime of a test VM before and after the upgrade
  deploy/Dockerfile.src.ci
  hack/upgrade-test-index-image.sh
  hack/vmuptime.ext
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1444 Reduce permissions
  cmd/hyperconverged-cluster-operator/main.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  pkg/apis/hco/v1beta1/hyperconverged_types_test.go
  pkg/components/components.go
  pkg/controller/operands/operandHandler.go
  pkg/util/consts.go
  tools/manifest-templator/manifest-templator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#1447 unstable index image in deploy_kustomize.sh
  deploy/kustomize/base/subscription.yaml
  deploy/kustomize/deploy_kustomize.sh
  deploy/kustomize/image_registry/catalog_source.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1448 Add the `runbook_url` annotation to all the alerts
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/controller/operands/monitoring.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1435 Set DiskVerification memory usage limit in KubeVirt CR
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1453 fix a bug in community operators publish workflow
  .github/workflows/publish-community-operators.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1455 Update Publish workflow due to changes in community-operators
  automation/publisher/publisher.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1452 Update components versions for release-1.4
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  hack/upgrade-test-index-image.sh
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/names/names.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/upload/v1alpha1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/upload/v1beta1/openapi_generated.go
  vendor/modules.txt
Labels: dco-signoff: yes, release-note-none, size/XXL
