Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2021-05, with the labels that each got.

#1293 get ready for 1.5.0
  README.md
  deploy/index-image/Dockerfile.bundle.ci-index-image-upgrade
  deploy/index-image/bundle.Dockerfile
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/cluster-network-addons00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/containerized-data-importer00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/hco01.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/hco02.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/node-maintenance00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/vm-import-operator00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/metadata/annotations.yaml
  deploy/kustomize/base/subscription.yaml
  deploy/kustomize/deploy_kustomize.sh
  deploy/olm-catalog/Dockerfile.bundle.ci-index-image-upgrade
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/cluster-network-addons00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/hco01.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/hco02.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/node-maintenance00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/vm-import-operator00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/metadata/annotations.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/kubevirt-hyperconverged.package.yaml
  deploy/operator.yaml
  docs/functest-container.md
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#1300 [release-1.4] Fix hco-e2e-upgrade-*index-* lanes
  deploy/index-image/Dockerfile.bundle.ci-index-image-upgrade
  deploy/olm-catalog/Dockerfile.bundle.ci-index-image-upgrade
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1304 Switch index image to semver mode in "unstable" workflow
  .github/workflows/build-push-images.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  hack/build-index-image.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1306 [release-1.4] update build-push-images workflow
  .github/workflows/build-push-images.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1305 change the default branch to main
  .github/workflows/build-push-images.yaml
  .github/workflows/digester_bot.yml
  .github/workflows/pr-sanity.yaml
  .github/workflows/publish-community-operators.yaml
  .github/workflows/release-bumper.yml
  README.md
  deploy/deploy.sh
  docs/conditions.md
  hack/make_local.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1309 Fix KubevirtHyperconvergedClusterOperatorCRModification alert and metrics
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/cdi.go
  pkg/controller/operands/monitoring.go
  pkg/controller/operands/operandHandler.go
  pkg/controller/operands/vmImport.go
  pkg/metrics/metrics.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1310 Validate that this repository does not contain offensive language
  Makefile
  hack/validate-no-offensive-lang.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1311 Enforce more checks on certConfig
  pkg/webhooks/webhooks.go
  pkg/webhooks/webhooks_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1314 [release-1.4] Fix KubevirtHyperconvergedClusterOperatorCRModification alert and metrics
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/cdi.go
  pkg/controller/operands/monitoring.go
  pkg/controller/operands/operandHandler.go
  pkg/controller/operands/vmImport.go
  pkg/metrics/metrics.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1316 Change the enforced min value for cert rotation
  pkg/webhooks/webhooks.go
  pkg/webhooks/webhooks_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1307 Update Community-Operators Publisher Workflow
  .github/workflows/publish-community-operators.yaml
  automation/publisher/publisher.sh
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  hack/check_defaults.sh
  hack/upgrade-test-index-image.sh
  hack/upgrade-test.sh
  hack/validate-no-offensive-lang.sh
  pkg/webhooks/webhooks.go
  pkg/webhooks/webhooks_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1319 Make deploy/kustomize compatible with kustomize v3
  deploy/kustomize/base/hco_cr.yaml
  deploy/kustomize/base/kustomization.yaml
  deploy/kustomize/base/operator_group.yaml
  deploy/kustomize/base/subscription.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1320 [release-1.4] create the index image in semver mode
  hack/build-index-image.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1322 [release-1.4] manual cherry-pick of #1307
  .github/workflows/publish-community-operators.yaml
  automation/publisher/publisher.sh
  hack/check_defaults.sh
  hack/upgrade-test-index-image.sh
  hack/upgrade-test.sh
  pkg/webhooks/webhooks.go
  pkg/webhooks/webhooks_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1325 Increase the initialDelay for the liveness probe
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1318 Default Permitted PCI Host Devices
  automation/nightly/test-nightly-build.sh
  build/Dockerfile
  build/Dockerfile.functest
  build/Dockerfile.webhook
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/webhooks.yaml
  docs/api.md
  docs/cluster-configuration.md
  hack/check_defaults.sh
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/hyperconverged_types_test.go
  pkg/apis/hco/v1beta1/hyperconverged_webhook.go
  pkg/apis/hco/v1beta1/hyperconverged_webhook_test.go
  pkg/apis/hco/v1beta1/zz_generated.openapi.go
  pkg/components/components.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
  pkg/util/consts.go
  pkg/webhooks/webhooks_test.go
  tests/build/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1326 [release-1.4] Increase the initialDelay for the liveness probe
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1328 Fix initialDelay for the liveness probe
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/components/components.go
Labels: approved, dco-signoff: yes, release-note, size/M

#1337 Move to go version 1.16.4 (latest)
  .github/workflows/digester_bot.yml
  .github/workflows/pr-sanity.yaml
  .github/workflows/release-bumper.yml
  automation/nightly/test-nightly-build.sh
  build/Dockerfile
  build/Dockerfile.functest
  build/Dockerfile.webhook
  go.mod
  go.sum
  tests/build/Dockerfile
  tools/digester/go.mod
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1332 [release-1.4] Bump SSP to v0.2.0 (#1331)
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1339 [release-1.4] Bump CDI to v1.34.0 (#1301)
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/types_transfer.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1340 allow to run the digester and the release-bumper actions manually
  .github/workflows/digester_bot.yml
  .github/workflows/release-bumper.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1342 Properly collect junit output on KV smoke tests
  hack/kv-smoke-tests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1346 Add a statement to clarify checklist in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1347 [release-1.4] Bump NETWORK_ADDONS to v0.54.0 (#1324)
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  hack/kv-smoke-tests.sh
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1349 test upgrade with a real config map
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/hyperconverged_suite_test.go
  pkg/controller/hyperconverged/test-files/kubevirt-config.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1350 Fix a bug in adopting the kubevirt-config CM
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1351 [release-1.4] Fix a bug in adopting the kubevirt-config CM
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/hyperconverged_suite_test.go
  pkg/controller/hyperconverged/test-files/kubevirt-config.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1352 Fix bug 1962135: liveMigrationConfig fields from kubevirt-config conf…
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1356 Fix upgrade path to unstable versions
  tools/csv-merger/csv-merger.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1357 [release-1.4] allow manually running component version bump
  .github/workflows/release-bumper.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1360 Auto add [release-1.4] in Bump PRs titles and PR branches
  .github/workflows/release-bumper.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1363 Allow manually bump a specific component to a specific version
  .github/workflows/release-bumper.yml
  automation/release-bumper/release-bumper.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1353 migrate *.v2v.kubevirt.io CRDs to apiextensions.k8s.io/v1
  deploy/crds/hco01.crd.yaml
  deploy/crds/hco02.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/hco01.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/hco02.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/hco01.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/hco02.crd.yaml
  hack/kv-smoke-tests.sh
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1365 fix the release bump action
  .github/workflows/release-bumper.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1370 Fix the realease bump action bug
  automation/release-bumper/release-bumper.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1367 Sonar cloud fix: Remove code duplications
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#1372 doc: add another jsonpatch annotation example
  docs/cluster-configuration.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1373 Remove a few TODO comments
  cmd/cmdcommon/cmdcommon.go
  pkg/apis/hco/v1beta1/hyperconverged_webhook.go
  pkg/components/components.go
  pkg/webhooks/webhooks.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S
