Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2021-03, with the labels that each got.

#1158 Fix csplit delimiter in build-manifests.sh
  hack/build-manifests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1161 Fix Documentation of Unreleased Bundles
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1162 Fix: add wait for hco webhook
  deploy/deploy.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1153 Add api documentation with po-docgen
  Makefile
  docs/api.md
  tools/docgen/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1156 Populate all mandatory KV configurations
  CONTRIBUTING.md
  docs/api.md
  docs/cluster-configuration.md
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/hyperconverged_types_test.go
  pkg/controller/commonTestUtils/testClient.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
  pkg/webhooks/webhooks_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1163 Add alert tests
  .github/workflows/pr-sanity.yaml
  Makefile
  hack/prom-rule-ci/prom-rules-tests.yaml
  hack/prom-rule-ci/rule-spec-dumper.go
  hack/prom-rule-ci/verify-rules.sh
  pkg/controller/operands/monitoring.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1164 Add Live Migration Configuration
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/hyperconverged_types_test.go
  pkg/apis/hco/v1beta1/zz_generated.deepcopy.go
  pkg/apis/hco/v1beta1/zz_generated.openapi.go
  pkg/controller/commonTestUtils/testUtils.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/ensure_result_test.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
  pkg/webhooks/webhooks_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1165 Wait to set CDI featuregates until "config authority" annotation is set
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  go.mod
  go.sum
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cdi_test.go
  vendor/github.com/onsi/ginkgo/.travis.yml
  vendor/github.com/onsi/ginkgo/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/README.md
  vendor/github.com/onsi/ginkgo/config/config.go
  vendor/github.com/onsi/ginkgo/go.mod
  vendor/github.com/onsi/ginkgo/go.sum
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_darwin.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_dragonfly.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_freebsd.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_linux.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_linux_mips64le.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_netbsd.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_openbsd.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_solaris.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_unix.go
  vendor/github.com/onsi/ginkgo/internal/spec/specs.go
  vendor/github.com/onsi/ginkgo/internal/suite/suite.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/go.mod
  vendor/github.com/onsi/gomega/go.sum
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers/consist_of.go
  vendor/github.com/onsi/gomega/matchers/contain_elements_matcher.go
  vendor/github.com/onsi/gomega/matchers/match_error_matcher.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1166 [Release 1.3] Wait to set CDI featuregates until "config authority" annotation is set (#1165)
  .github/workflows/pr-sanity.yaml
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cdi_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1141 Add Polarion Reporter and Documentation into functest image
  Makefile
  build/Dockerfile.functest
  docs/functest-container.md
  hack/run-tests.sh
  tests/func-tests/main_test.go
  tests/go.mod
  tests/go.sum
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1167 Update feature gate APIs
  CONTRIBUTING.md
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/hyperconverged_types_test.go
  pkg/apis/hco/v1beta1/zz_generated.deepcopy.go
  pkg/apis/hco/v1beta1/zz_generated.openapi.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
  pkg/controller/operands/operandHandler.go
  pkg/webhooks/webhooks.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1155 Workflow for auto-publishing tagged HCO versions to community-operators
  .github/workflows/publish-community-operators.yaml
  automation/publisher/publisher.sh
  cmd/cmdcommon/cmdcommon.go
  deploy/Dockerfile.registry.upgrade
  deploy/Dockerfile.registry.upgrade-prev
  deploy/index-image/bundle.Dockerfile
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/cluster-network-addons00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/containerized-data-importer00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/hco01.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/hco02.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/node-maintenance00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/vm-import-operator00.crd.yaml
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/cluster-network-addons00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/hco01.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/hco02.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/node-maintenance00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/vm-import-operator00.crd.yaml
  hack/build-manifests.sh
  hack/upgrade-create-new-version.sh
  pkg/components/components.go
  pkg/util/consts.go
  tools/csv-merger/csv-merger.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1173 Remove KubeVirt ConfigMap
  hack/upgrade-test.sh
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
  pkg/controller/operands/operandHandler.go
  tests/func-tests/main_test.go
  tests/func-tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1171 Introduces configuration interface for functional test container
  docs/functest-container.md
  hack/check_labels.sh
  hack/run-tests.sh
  tests/func-tests/config.go
  tests/func-tests/quickstart_test.go
  tests/func-tests/unprivileged_test.go
  tests/go.mod
  tests/go.sum
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1179 Support Permitted Host Devices
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/zz_generated.deepcopy.go
  pkg/apis/hco/v1beta1/zz_generated.openapi.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1184 [release-1.3] Rebuild Operator and Webhook Images
  deploy/images.csv
  deploy/images.env
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1187 Update the image digests for version 1.3
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.3.0/manifests/cluster-network-addons00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.3.0/manifests/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.3.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.3.0/manifests/hco01.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.3.0/manifests/hco02.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.3.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.3.0/manifests/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.3.0/manifests/kubevirt00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.3.0/manifests/node-maintenance00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.3.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.3.0/manifests/vm-import-operator00.crd.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1181 Keep forcing the absence of the KubeVirt ConfigMap after upgrade
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/kubevirtConfigMap.go
  pkg/controller/operands/kubevirtConfigMap_test.go
  pkg/controller/operands/operandHandler.go
  pkg/util/util.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1169 Expose API for certificate rotation configuration
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/hco00.crd.yaml
  docs/api.md
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cdi_test.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/networkAddons.go
  pkg/controller/operands/operand.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1180 Add pprof instrumentation for optional cpu and memory profiling
  cmd/cmdcommon/cmdcommon.go
  cmd/hyperconverged-cluster-operator/main.go
  cmd/hyperconverged-cluster-webhook/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1190 Enhancement for the Publisher Workflow
  .github/workflows/publish-community-operators.yaml
  automation/publisher/publisher.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1191 [release-1.3] Adding publish workflow for release-1.3
  .github/workflows/publish-community-operators.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1193 Align 1.3.0 manifests for upgrade testing
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.3.0/manifests/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.3.0/manifests/scheduling-scale-performance00.crd.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1192 [release-1.3] Update Images Digests
  deploy/images.csv
  deploy/images.env
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.3.0/manifests/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1195 hco, Bump kubevirtci
  cluster/kubevirtci.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1194 hco, Update build-in-docker.sh to use quay.io
  hack/build-in-docker.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1197 hco, Update file of tests/build in order to trigger postsubmit job
  tests/build/entrypoint.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1200 Add documentation about profiling HCO with pprof
  docs/profiling.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1202 hco, Update hco-test-build image to point to quay
  hack/in-docker.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1204 Fix jsonpatch annotation docs
  docs/cluster-configuration.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1205 Make jsonpatch annotation doc more readable
  docs/cluster-configuration.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1189 Run KV smoke tests on openshift-ci
  Makefile
  hack/kv-smoke-tests.sh
  hack/test-config.json
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1206 hco, Use quay.io for nightly builds
  automation/nightly/test-nightly-build.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1203 Reconcile CDI configurations
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/hyperconverged_types_test.go
  pkg/apis/hco/v1beta1/zz_generated.deepcopy.go
  pkg/apis/hco/v1beta1/zz_generated.openapi.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cdi_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1208 hco, Use quay.io kubevirt repository
  automation/nightly/test-nightly-build.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1207 Cert config defaults
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/hco00.crd.yaml
  docs/api.md
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/hyperconverged_types_test.go
  pkg/apis/hco/v1beta1/zz_generated.deepcopy.go
  pkg/apis/hco/v1beta1/zz_generated.openapi.go
  pkg/components/components.go
  pkg/controller/commonTestUtils/testUtils.go
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cdi_test.go
  pkg/controller/operands/operand.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1214 hco, Fix CSV image links of nightly builds
  automation/nightly/test-nightly-build.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1213 Fix the go version in all go-based github actions to 1.15.10
  .github/workflows/digester_bot.yml
  .github/workflows/pr-sanity.yaml
  .github/workflows/release-bumper.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1210 Migrate IMS config
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/hco00.crd.yaml
  docs/api.md
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/zz_generated.deepcopy.go
  pkg/apis/hco/v1beta1/zz_generated.openapi.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/vmImport.go
  pkg/controller/operands/vmImport_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1216 Add log when can't complete the upgrade
  pkg/controller/operands/operand.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1219 Prevent git Conflicts
  hack/build-manifests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1218 Refactor the operator package
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/cdi.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/monitoring.go
  pkg/controller/operands/networkAddons.go
  pkg/controller/operands/operand.go
  pkg/controller/operands/quickStart.go
  pkg/controller/operands/ssp.go
  pkg/controller/operands/vmImport.go
  pkg/controller/operands/vmImport_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L
