Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2021-04, with the labels that each got.

#1222 Expose an environmental value to virtio win image
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/build-manifests.sh
  pkg/components/components.go
  pkg/controller/commonTestUtils/testUtils.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/operandHandler_test.go
  pkg/controller/operands/vmImport.go
  pkg/controller/operands/vmImport_test.go
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1226 Fix metric name to fit the kubevirt guidelines
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/controller/operands/monitoring.go
  pkg/metrics/metrics.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1232 Update repository owners
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1233 Revert kubevirt to 0.39.0
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1229 Add golangci-lint into project and solve existing issues
  .github/workflows/pr-sanity.yaml
  Makefile
  pkg/components/components.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cliDownload.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/networkAddons_test.go
  pkg/controller/operands/operand.go
  pkg/controller/operands/ssp_test.go
  pkg/controller/operands/vmImport.go
  pkg/util/cluster.go
  pkg/util/consts.go
  pkg/webhooks/webhooks_test.go
  tools/csv-merger/csv-merger.go
  tools/docgen/main.go
  tools/util/marshaller.go
  vendor/github.com/openshift/api/security/v1/0000_03_security-openshift_01_scc.crd.yaml
  vendor/github.com/openshift/api/security/v1/consts.go
  vendor/github.com/openshift/api/security/v1/doc.go
  vendor/github.com/openshift/api/security/v1/generated.pb.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/legacy.go
  vendor/github.com/openshift/api/security/v1/register.go
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/api/security/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/security/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#1196 Wire up CNAO SelfSignedConfiguration to HCO
  pkg/controller/operands/networkAddons.go
  pkg/controller/operands/networkAddons_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1236 Simplify csv-merger.go with csvv1alpha1.RelatedImage
  tools/csv-merger/csv-merger.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1239 Move ConsoleCLIDownload controller to operandHandler
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/cliDownload.go
  pkg/controller/operands/cliDownload_test.go
  pkg/controller/operands/operandHandler.go
  pkg/controller/operands/operandHandler_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1240 Use CI-generated index image for HCO upgrade tests
  Makefile
  deploy/index-image/Dockerfile.bundle.ci-index-image-upgrade
  deploy/olm-catalog/Dockerfile.bundle.ci-index-image-upgrade
  hack/build-manifests.sh
  hack/upgrade-test-index-image.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1242 Add missing environment variables to run locally
  hack/generate_local_env.py
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1238 In deploy files, change the HC operator and webhook images to use a the unstable version
  .github/workflows/build-push-images.yaml
  automation/nightly/test-nightly-build.sh
  deploy/images.csv
  deploy/images.env
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/build-manifests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1244 Replace operator-courier with operator-sdk bundle validation.
  .github/workflows/pr-sanity.yaml
  Makefile
  tools/operator-sdk-validate/Dockerfile
  tools/operator-sdk-validate/validate-bundles.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1251 minor fix in CI index-image upgrade test
  hack/upgrade-test-index-image.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1253 Add kubevirt.io/qe-tools to the list of release-bumper exclusions
  automation/release-bumper/release-bumper.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1250 Workaround for SSP stuck upgrades
  hack/build-tests.sh
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_components_test.go
Labels: dco-signoff: yes, lgtm, release-note, size/L

#1256 Improve unit tests of SSP upgrade workaround
  pkg/controller/hyperconverged/hyperconverged_controller_components_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1258 Fix CSV validation in upgrade test
  hack/upgrade-test-index-image.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1261 fix subscription patch command in index image upgrade
  hack/upgrade-test-index-image.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1262 sourcing the script for patching OperatorGroup on index upgrade test
  hack/upgrade-test-index-image.sh
Labels: dco-signoff: yes, release-note-none, size/XS

#1264 fix sed command in upgrade-index-ci Dockerfile
  .github/workflows/build-push-images.yaml
  deploy/index-image/Dockerfile.bundle.ci-index-image-upgrade
  deploy/olm-catalog/Dockerfile.bundle.ci-index-image-upgrade
Labels: approved, dco-signoff: yes, release-note-none, size/S

#1265 Use skipRange to enable upgrade in semver mode
  deploy/index-image/Dockerfile.bundle.ci-index-image-upgrade
  deploy/olm-catalog/Dockerfile.bundle.ci-index-image-upgrade
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1267 adding quotes to olm.skipRange annotation
  deploy/index-image/Dockerfile.bundle.ci-index-image-upgrade
  deploy/olm-catalog/Dockerfile.bundle.ci-index-image-upgrade
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#1268 Fix typos
  docs/cluster-configuration.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1270 [index image upgrade script] patch subscription's installPlanApproval
  deploy/index-image/Dockerfile.bundle.ci-index-image-upgrade
  deploy/olm-catalog/Dockerfile.bundle.ci-index-image-upgrade
  hack/upgrade-test-index-image.sh
Labels: dco-signoff: yes, release-note-none, size/XS

#1263 Add CPU Plugin configuration
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/zz_generated.deepcopy.go
  pkg/apis/hco/v1beta1/zz_generated.openapi.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1259 Fix cluster-sync for dual stack env
  cluster/sync.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1255 Change KubevirtHyperconvergedClusterOperatorCRModification alert rule
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/controller/operands/monitoring.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1273 Adjustments to the test upgrade index-image script
  hack/build-index-image.sh
  hack/upgrade-test-index-image.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1275 [upgrade test] Approve new InstallPlan on upgrade
  hack/upgrade-test-index-image.sh
Labels: dco-signoff: yes, release-note-none, size/S

#1228 Add reviewer checks to pr template
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#754 Adding Disconnected Annotation to the CSV
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, lifecycle/stale, release-note, size/XS

#1276 Fix golangcli-lint issue
  .github/workflows/pr-sanity.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1278 [upgrade bundle] fix olm.skipRange to enable upgrade from all previouss versions
  deploy/index-image/Dockerfile.bundle.ci-index-image-upgrade
  deploy/olm-catalog/Dockerfile.bundle.ci-index-image-upgrade
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1280 Don't run build-push-images workflow on irrelevant branches and paths
  .github/workflows/build-push-images.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1281 Change the default for the HypervStrictCheck and WithHostModelCPU feature gates
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
  pkg/controller/operands/operandHandler.go
  pkg/webhooks/webhooks.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1257 Hardening the defaulting mechanism
  CONTRIBUTING.md
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/hco00.crd.yaml
  docs/api.md
  hack/check_defaults.sh
  hack/run-tests.sh
  hack/upgrade-test-index-image.sh
  hack/upgrade-test.sh
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/hyperconverged_types_test.go
  pkg/apis/hco/v1beta1/zz_generated.deepcopy.go
  pkg/apis/hco/v1beta1/zz_generated.openapi.go
  pkg/components/components.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/cdi_test.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
  pkg/controller/operands/networkAddons_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1277 Add Insecure Registries for Imported containerized Data Images
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/hyperconverged_types_test.go
  pkg/apis/hco/v1beta1/zz_generated.deepcopy.go
  pkg/apis/hco/v1beta1/zz_generated.openapi.go
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cdi_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1284 fix wrong example for storageImport configurations
  docs/cluster-configuration.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1286 Change the implemntation of the Feature Gates to get more robust results
  pkg/controller/operands/kubevirt.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1287 fix typo in field documentation
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/hco00.crd.yaml
  docs/api.md
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/zz_generated.openapi.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1288 Fix a bug in Obsolete CPU Models
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/zz_generated.openapi.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1294 Make sanity test working for the release-1.4 branch
  .github/workflows/pr-sanity.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1295 Document out of band modification alert
  docs/cluster-configuration.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S
