Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2021-11, with the labels that each got.

#1583 Disable VM upgrade tests when 'workloadUpdateMethods' is empty
  Makefile
  hack/upgrade-test-index-image.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1580 Fetch junit.xml of func tests into artifacts
  build/Dockerfile.functest
  build/Dockerfile.functest.ci
  hack/run-tests-in-container.sh
  hack/run-tests.sh
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#1589 try to fix the hco-test-build image
  tests/build/Dockerfile
Labels: release-note-none, size/XS, dco-signoff: yes

#1587 Refresh hco-test-build
  tests/build/Dockerfile
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#1590 fix hco-test-build
  tests/build/Dockerfile
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#1591 Dumb PR to rebuild hco-test-build
  tests/build/Dockerfile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1593 Fix again hco-test-build
  tests/build/entrypoint.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1594 trigger another build
  tests/build/Dockerfile
Labels: release-note-none, size/XS, dco-signoff: yes

#1595 Build again hco-test-build
  tests/build/Dockerfile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1592 Update the hco-test-build to the latest version
  hack/build-in-docker.sh
  hack/in-docker.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1586 Apply upgrade patches according to a yaml file
  assets/upgradePatches.json
  build/Dockerfile.okd
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/test-files/upgradePatches/badJson.json
  pkg/controller/hyperconverged/test-files/upgradePatches/badPatches1.json
  pkg/controller/hyperconverged/test-files/upgradePatches/badPatches2.json
  pkg/controller/hyperconverged/test-files/upgradePatches/badPatches3.json
  pkg/controller/hyperconverged/test-files/upgradePatches/badSemverRange.json
  pkg/controller/hyperconverged/test-files/upgradePatches/empty.json
  pkg/controller/hyperconverged/test-files/upgradePatches/upgradePatches.json
  pkg/controller/hyperconverged/upgradePatches.go
  pkg/controller/hyperconverged/upgradePatches_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1598 Recursively sort imports and validate
  Makefile
  pkg/apis/hco/v1beta1/hyperconverged_types_test.go
  pkg/apis/hco/v1beta1/register.go
  pkg/controller/common/hcoConditions.go
  pkg/controller/common/hcoConditions_test.go
  pkg/controller/common/hcoRequest.go
  pkg/controller/commonTestUtils/eventEmitterMock.go
  pkg/controller/commonTestUtils/testClient.go
  pkg/controller/commonTestUtils/testUtils.go
  pkg/controller/hyperconverged/crdsRemover.go
  pkg/controller/hyperconverged/upgradePatches.go
  pkg/controller/hyperconverged/upgradePatches_test.go
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cdi_test.go
  pkg/controller/operands/cliDownload.go
  pkg/controller/operands/cliDownload_test.go
  pkg/controller/operands/dashboard.go
  pkg/controller/operands/dashboard_test.go
  pkg/controller/operands/ensure_result.go
  pkg/controller/operands/ensure_result_test.go
  pkg/controller/operands/monitoring_test.go
  pkg/controller/operands/networkAddons.go
  pkg/controller/operands/networkAddons_test.go
  pkg/controller/operands/operand.go
  pkg/controller/operands/operandHandler.go
  pkg/controller/operands/operandHandler_test.go
  pkg/controller/operands/operand_test.go
  pkg/controller/operands/quickStart.go
  pkg/controller/operands/quickStart_test.go
  pkg/controller/operands/ssp.go
  pkg/controller/operands/utils_test.go
  pkg/metrics/metrics.go
  pkg/util/event_emmiter_test.go
  pkg/webhooks/setup_test.go
  pkg/webhooks/validator/validator.go
  pkg/webhooks/validator/validator_test.go
  tests/func-tests/cli_download_test.go
  tests/func-tests/config.go
  tests/func-tests/dashboard_test.go
  tests/func-tests/dependency_objects_test.go
  tests/func-tests/main_test.go
  tests/func-tests/node_placement_test.go
  tests/func-tests/quickstart_test.go
  tests/func-tests/unprivileged_test.go
  tests/func-tests/utils.go
  tests/func-tests/virtual_machines_test.go
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#1599 [release-1.5] Apply upgrade patches according to a yaml file (#1586)
  assets/upgradePatches.json
  build/Dockerfile.okd
  go.mod
  go.sum
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/test-files/upgradePatches/badJson.json
  pkg/controller/hyperconverged/test-files/upgradePatches/badPatches1.json
  pkg/controller/hyperconverged/test-files/upgradePatches/badPatches2.json
  pkg/controller/hyperconverged/test-files/upgradePatches/badPatches3.json
  pkg/controller/hyperconverged/test-files/upgradePatches/badSemverRange.json
  pkg/controller/hyperconverged/test-files/upgradePatches/empty.json
  pkg/controller/hyperconverged/test-files/upgradePatches/upgradePatches.json
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/hyperconverged/upgradePatches.go
  pkg/controller/hyperconverged/upgradePatches_test.go
  vendor/github.com/evanphx/json-patch/.gitignore
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/modules.txt
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1601 Avoid using go get to install executables
  hack/build-tests.sh
  tests/build/Dockerfile
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#1604 Make upgrade patches log more readable
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1582 Bump KUBEVIRT to v0.47.1 and adapt the code
  cmd/hyperconverged-cluster-operator/main.go
  cmd/hyperconverged-cluster-webhook/main.go
  deploy/cluster_role.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  pkg/controller/commonTestUtils/testUtils.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
  pkg/controller/operands/operandHandler.go
  pkg/controller/operands/operandHandler_test.go
  pkg/webhooks/mutator/mutator_test.go
  pkg/webhooks/validator/validator.go
  pkg/webhooks/validator/validator_test.go
  tools/util/marshaller.go
  vendor/kubevirt.io/client-go/api/v1/register.go
  vendor/kubevirt.io/client-go/apis/core/register.go
  vendor/kubevirt.io/client-go/apis/core/v1/componentconfig.go
  vendor/kubevirt.io/client-go/apis/core/v1/deepcopy_generated.go
  vendor/kubevirt.io/client-go/apis/core/v1/defaults.go
  vendor/kubevirt.io/client-go/apis/core/v1/doc.go
  vendor/kubevirt.io/client-go/apis/core/v1/openapi_generated.go
  vendor/kubevirt.io/client-go/apis/core/v1/register.go
  vendor/kubevirt.io/client-go/apis/core/v1/schema.go
  vendor/kubevirt.io/client-go/apis/core/v1/schema_swagger_generated.go
  vendor/kubevirt.io/client-go/apis/core/v1/types.go
  vendor/kubevirt.io/client-go/apis/core/v1/types_swagger_generated.go
  vendor/kubevirt.io/client-go/apis/core/v1/utils.go
  vendor/kubevirt.io/client-go/apis/core/v1/zz_generated.defaults.go
  vendor/kubevirt.io/client-go/precond/precond.go
  vendor/modules.txt
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#1605 Amend 'bandwidthPerMigration' config using 'upgradePatches'
  assets/upgradePatches.json
  go.mod
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#1585 Bump CDI to v1.41.1 + use CDI-API
  automation/release-bumper/release-bumper.sh
  deploy/cluster_role.yaml
  deploy/crds/containerized-data-importer00.crd.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/containerized-data-importer00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  hack/config
  pkg/controller/operands/ssp_test.go
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#1607 Use the new CDI API in the code
  cmd/hyperconverged-cluster-operator/main.go
  cmd/hyperconverged-cluster-webhook/main.go
  go.mod
  go.sum
  pkg/controller/commonTestUtils/testUtils.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cdi_test.go
  pkg/controller/operands/operandHandler.go
  pkg/controller/operands/operandHandler_test.go
  pkg/controller/operands/operand_test.go
  pkg/webhooks/mutator/mutator_test.go
  pkg/webhooks/validator/validator.go
  pkg/webhooks/validator/validator_test.go
  vendor/kubevirt.io/containerized-data-importer-api/LICENSE
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/register.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/doc.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/register.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_transfer.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/utils.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#1606 Remove CDI configuration upgrade code
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#1579 Enable (again) default workloadUpdates strategies
  assets/upgradePatches.json
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  hack/check_defaults.sh
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/components/components.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/kubevirt_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1610 Enable ExpandDisks FeatureGate
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/kubevirt.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#1611 Exclude SSP CRDs from CRDRemover
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#1612 Bump the operator capability level to Deep Insights
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  pkg/components/components.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#1615 Bump SSP to v0.13.0-rc.2 and adopt the new Golden Images API
  assets/dataImportCronTemplates/dataImportCronTemplates.yaml
  deploy/cluster_role.yaml
  deploy/crds/hco00.crd.yaml
  deploy/crds/scheduling-scale-performance00.crd.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  hack/retry.sh
  hack/upgrade-test-index-image.sh
  pkg/controller/operands/ssp_test.go
  pkg/controller/operands/testFiles/dataImportCronTemplates/dataImportCronTemplates.yaml
  pkg/controller/operands/testFiles/dataImportCronTemplates/wrongDataImportCronTemplates.yaml
  tools/util/marshaller.go
  vendor/kubevirt.io/ssp-operator/api/v1beta1/ssp_types.go
  vendor/modules.txt
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#1614 Stop migrating kubevirt-config configurations to HCO
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#1608 Support Automatic configuration of mediated devices
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1619 Make dependabot happy
  tests/go.mod
  tests/go.sum
  tests/vendor/modules.txt
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#1621 Enable the KubeVirt NUMA featuregate
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/kubevirt.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#1624 Consume latest github.com/u-root/u-root in tests/
  tests/go.mod
  tests/go.sum
  tests/vendor/github.com/google/goexpect/README.md
  tests/vendor/github.com/google/goexpect/expect.go
  tests/vendor/golang.org/x/term/term.go
  tests/vendor/modules.txt
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#1626 Be more tolerant parsing previous version
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1628 fix nightly builds
  automation/nightly/test-nightly-build.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1622 Add common labels into alert definitions
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/controller/operands/monitoring.go
Labels: size/M, release-note, ok-to-test, dco-signoff: yes, lgtm, approved

#1616 Use the kubevirt.io/api package instead of kubevirt.io/client-go
  assets/dataImportCronTemplates/dataImportCronTemplates.yaml
  automation/release-bumper/release-bumper.sh
  cmd/hyperconverged-cluster-operator/main.go
  cmd/hyperconverged-cluster-webhook/main.go
  go.mod
  go.sum
  hack/check_golden_images.sh
  hack/run-tests-in-container.sh
  pkg/controller/commonTestUtils/testUtils.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
  pkg/controller/operands/operandHandler.go
  pkg/controller/operands/operandHandler_test.go
  pkg/webhooks/mutator/mutator_test.go
  pkg/webhooks/validator/validator.go
  pkg/webhooks/validator/validator_test.go
  tools/util/marshaller.go
  vendor/kubevirt.io/api/LICENSE
  vendor/kubevirt.io/api/core/register.go
  vendor/kubevirt.io/api/core/v1/componentconfig.go
  vendor/kubevirt.io/api/core/v1/deepcopy_generated.go
  vendor/kubevirt.io/api/core/v1/defaults.go
  vendor/kubevirt.io/api/core/v1/doc.go
  vendor/kubevirt.io/api/core/v1/register.go
  vendor/kubevirt.io/api/core/v1/schema.go
  vendor/kubevirt.io/api/core/v1/schema_swagger_generated.go
  vendor/kubevirt.io/api/core/v1/types.go
  vendor/kubevirt.io/api/core/v1/types_swagger_generated.go
  vendor/kubevirt.io/api/core/v1/zz_generated.defaults.go
  vendor/kubevirt.io/client-go/apis/core/v1/openapi_generated.go
  vendor/kubevirt.io/client-go/apis/core/v1/utils.go
  vendor/kubevirt.io/containerized-data-importer/LICENSE
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/BUILD.bazel
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/register.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/BUILD.bazel
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/doc.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/register.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/types_transfer.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/utils.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#1623 Add a tool to automatically generate release notes
  tools/release-notes/Makefile
  tools/release-notes/git.go
  tools/release-notes/github.go
  tools/release-notes/go.mod
  tools/release-notes/go.sum
  tools/release-notes/release-notes.go
  tools/release-notes/semver.go
  tools/release-notes/types.go
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#1631 Add a badge for nightly images
  README.md
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1632 Force an older docker API version
  automation/nightly/test-nightly-build.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved
