Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2021-06, with the labels that each got.

#1380 Always update objectReferences in a single pass
  pkg/controller/operands/cdi_test.go
  pkg/controller/operands/cliDownload_test.go
  pkg/controller/operands/kubevirt_test.go
  pkg/controller/operands/monitoring_test.go
  pkg/controller/operands/networkAddons_test.go
  pkg/controller/operands/operand.go
  pkg/controller/operands/quickStart_test.go
  pkg/controller/operands/ssp_test.go
  pkg/controller/operands/vmImport_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1387 [release-1.4] Remove the default PCI host devices
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/webhooks.yaml
  hack/check_defaults.sh
  pkg/apis/hco/v1beta1/hyperconverged_webhook.go
  pkg/apis/hco/v1beta1/hyperconverged_webhook_test.go
  pkg/components/components.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/util/consts.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1385 Expose an enviromental value to virtio win image (#1222)
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.3.0/manifests/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.3.0/manifests/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/build-manifests.sh
  pkg/components/components.go
  pkg/controller/commonTestUtils/testUtils.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/operandHandler_test.go
  pkg/controller/operands/vmImport.go
  pkg/controller/operands/vmImport_test.go
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1384 Remove the default PCI host devices
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/webhooks.yaml
  docs/api.md
  docs/cluster-configuration.md
  hack/check_defaults.sh
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/hyperconverged_webhook.go
  pkg/apis/hco/v1beta1/hyperconverged_webhook_test.go
  pkg/components/components.go
  pkg/util/consts.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1388 Exit the upgrade mode only when nothing is still to be written on the HCO CR
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1390 Document certificateRotation parameters
  docs/cluster-configuration.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1396 Remove descriptions from unstored versions of CRDs
  deploy/crds/cluster-network-addons00.crd.yaml
  deploy/crds/containerized-data-importer00.crd.yaml
  deploy/crds/hostpath-provisioner00.crd.yaml
  deploy/crds/kubevirt00.crd.yaml
  deploy/crds/vm-import-operator00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/cluster-network-addons00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/containerized-data-importer00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/vm-import-operator00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/cluster-network-addons00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/vm-import-operator00.crd.yaml
  hack/build-manifests.sh
  hack/strip_old_descriptions.py
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1399 Doc tests
  docs/tests.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1406 [release-1.4] align release-1.4 versions
  deploy/cluster_role.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/names/names.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/upload/v1alpha1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/upload/v1beta1/openapi_generated.go
  vendor/modules.txt
Labels: dco-signoff: yes, release-note, size/XXL

#1405 Tune resources requests
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1401 Enable SRIOVLiveMigration feature-gate by default
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  hack/check_defaults.sh
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/components/components.go
  pkg/controller/operands/kubevirt_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1404 Migrate from openshift conditions to k8s metav1 conditions
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/hco00.crd.yaml
  docs/api.md
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/hyperconverged_types_test.go
  pkg/apis/hco/v1beta1/zz_generated.deepcopy.go
  pkg/apis/hco/v1beta1/zz_generated.openapi.go
  pkg/controller/common/hcoConditions.go
  pkg/controller/common/hcoConditions_test.go
  pkg/controller/commonTestUtils/testUtils.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cdi_test.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
  pkg/controller/operands/networkAddons.go
  pkg/controller/operands/networkAddons_test.go
  pkg/controller/operands/operand.go
  pkg/controller/operands/operandHandler.go
  pkg/controller/operands/operandHandler_test.go
  pkg/controller/operands/ssp.go
  pkg/controller/operands/vmImport.go
  vendor/github.com/openshift/custom-resource-status/testlib/matcher.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#1409 Split writing HyperConverged's status and body
  hack/generate_local_env.py
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#1410 Only update the conditions if they are actually modified
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/hco00.crd.yaml
  docs/api.md
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/zz_generated.openapi.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/operand.go
  pkg/controller/operands/operandHandler.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L
