Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2021-12, with the labels that each got.

#1629 Create ImageStreams if they defined in the dataImportCronTemplate yaml files
  assets/dataImportCronTemplates/dataImportCronTemplates.yaml
  build/Dockerfile.okd
  build/Dockerfile.wh.okd
  ci-test-files/centos8-imagestream.yaml
  ci-test-files/dataImportCronTemplatesWithImageStream.yaml
  cmd/hyperconverged-cluster-operator/main.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  hack/check_golden_images.sh
  pkg/components/components.go
  pkg/controller/commonTestUtils/testUtils.go
  pkg/controller/operands/imageStream.go
  pkg/controller/operands/imageStream_test.go
  pkg/controller/operands/operandHandler.go
  pkg/controller/operands/ssp.go
  pkg/controller/operands/ssp_test.go
  pkg/controller/operands/testFiles/dataImportCronTemplates/dataImportCronTemplatesWithImageStream.yaml
  pkg/controller/operands/testFiles/imageStreams/imageStream.yaml
  vendor/github.com/openshift/api/image/docker10/doc.go
  vendor/github.com/openshift/api/image/docker10/dockertypes.go
  vendor/github.com/openshift/api/image/docker10/register.go
  vendor/github.com/openshift/api/image/docker10/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/image/dockerpre012/deepcopy.go
  vendor/github.com/openshift/api/image/dockerpre012/doc.go
  vendor/github.com/openshift/api/image/dockerpre012/dockertypes.go
  vendor/github.com/openshift/api/image/dockerpre012/register.go
  vendor/github.com/openshift/api/image/dockerpre012/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/image/v1/consts.go
  vendor/github.com/openshift/api/image/v1/doc.go
  vendor/github.com/openshift/api/image/v1/generated.pb.go
  vendor/github.com/openshift/api/image/v1/generated.proto
  vendor/github.com/openshift/api/image/v1/legacy.go
  vendor/github.com/openshift/api/image/v1/register.go
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/api/image/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/image/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#1603 Bump HPPO to v0.11.0
  deploy/cluster_role.yaml
  deploy/crds/hostpath-provisioner00.crd.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/webhooks.yaml
  go.mod
  hack/config
  pkg/components/components.go
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#1642 Bump golang dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/klog.go
  vendor/modules.txt
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#1644 Fix the release-bumper script
  automation/release-bumper/release-bumper.sh
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#1646 Fix the call to goimports in the Makefile
  Makefile
  cmd/hyperconverged-cluster-operator/main.go
  pkg/controller/commonTestUtils/testUtils.go
  pkg/controller/operands/ssp.go
  pkg/controller/operands/ssp_test.go
  tools/digester/main.go
  tools/release-notes/github.go
  tools/release-notes/release-notes.go
  tools/release-notes/semver.go
  tools/release-notes/types.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#1648 Remove KubeVirtCmHandler
  hack/upgrade-test-index-image.sh
  hack/upgrade-test.sh
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/test-files/kubevirt-config.yaml
  pkg/controller/operands/kubevirtConfigMap.go
  pkg/controller/operands/kubevirtConfigMap_test.go
  pkg/controller/operands/operandHandler.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1635 Add constants to use as alerts labels keys and values
  pkg/controller/operands/monitoring.go
Labels: release-note-none, size/M, needs-ok-to-test, dco-signoff: yes, lgtm, approved

#1633 Fix out-of-date resource-version
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/operand.go
  pkg/controller/operands/operand_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#1652 bump opencontainers/runc in tests/
  tests/go.mod
  tests/go.sum
  tests/vendor/modules.txt
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1651 Randomize the DataImportCronTemplate cron's hour
  pkg/controller/hyperconverged/dataimportschedule.go
  pkg/controller/hyperconverged/dataimportschedule_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#1647 Provide virtio-win pullspec in dedicated ConfigMap
  hack/upgrade-test-index-image.sh
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cdi_test.go
  pkg/controller/operands/cmHandler.go
  pkg/controller/operands/dashboard.go
  pkg/controller/operands/dashboard_test.go
  pkg/controller/operands/operandHandler.go
  pkg/controller/operands/operandHandler_test.go
  pkg/controller/operands/rbac.go
  pkg/controller/operands/ssp.go
  pkg/controller/operands/virtio_win_ConfigMap.go
  pkg/controller/operands/virtio_win_ConfigMap_test.go
  tools/digester/go.mod
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#1655 Add test cases for runbook URLs
  tests/func-tests/monitoring_test.go
  tests/go.mod
  tests/go.sum
  tests/vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/LICENSE
  tests/vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/register.go
  tests/vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/doc.go
  tests/vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/register.go
  tests/vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  tests/vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/types.go
  tests/vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  tests/vendor/modules.txt
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#1654 Bug 2030660: Fix bug where imageStream are not get reconciled
  cmd/hyperconverged-cluster-operator/main.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  hack/check_golden_images.sh
  pkg/components/components.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/operands/imageStream.go
  pkg/controller/operands/imageStream_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1634 Calculate diff only between tags when generating release notes
  tools/release-notes/git.go
  tools/release-notes/release-notes.go
  tools/release-notes/semver.go
  tools/release-notes/types.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#1656 Add a workaround for uninstall on SNO
  hack/test_delete_ns.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#1658 [release-1.5] grant access for v2v-vmware config map for non-admin users
  pkg/controller/operands/cdi.go
  tests/func-tests/unprivileged_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1659 Reconcile ImageStream only if the FG is true
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  hack/check_golden_images.sh
  hack/upgrade-test-index-image.sh
  pkg/components/components.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/operands/ensure_result.go
  pkg/controller/operands/imageStream.go
  pkg/controller/operands/imageStream_test.go
  pkg/controller/operands/operandHandler.go
  pkg/util/util.go
  pkg/util/util_test.go
  pkg/webhooks/validator/validator.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1662 [release-1.5] Bump NETWORK_ADDONS to v0.58.5
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/shared/networkaddonsconfig_operators.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/names/names.go
  vendor/modules.txt
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1665 DataImportCronTemplates references quay.io/containerdisks
  assets/dataImportCronTemplates/dataImportCronTemplates.yaml
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#1668 Fix the release bumper bot
  automation/release-bumper/release-bumper.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#1671 Fetch addition HPP images by digest
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  hack/build-manifests.sh
  hack/config
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#1672 Expose a knob to tune UninstallStrategy
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  hack/check_defaults.sh
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cdi_test.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1674 docs: cluster-configuration: fix the network annotation
  docs/cluster-configuration.md
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#1676 Fix flaky test - extract the timeout of reading the DataImportCrons
  hack/check_golden_images.sh
  hack/upgrade-test-index-image.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#1677 Fix Rebase Bot
  .github/workflows/rebase-bot.yml
  automation/rebase-bot/rebase-bot.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1678 add a token for authenticated git actions in rebase bot workflow
  .github/workflows/rebase-bot.yml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1679 Reorder things in the rebase bot
  automation/rebase-bot/rebase-bot.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#1675 Add missing owner references
  pkg/controller/operands/cliDownload.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1556 [release-1.5] Revert an hack on upgrade lanes
  hack/upgrade-test-index-image.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1557 Revert an hack on upgrade lanes
  hack/upgrade-test-index-image.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved
