Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2021-08, with the labels that each got.

#1459 [release-1.3] Update .status.storedVersions on the CRD
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.3.0/manifests/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.3.0/manifests/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  hack/upgrade-test.sh
  pkg/components/components.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
Labels: dco-signoff: yes, do-not-merge/hold, release-note, size/L

#1457 Update .status.storedVersions on the CRD on upgrades
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  pkg/components/components.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1458 [release-1.4] Update .status.storedVersions on the CRD
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  pkg/components/components.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1460 Use ci go builder for functests
  build/Dockerfile.functest.ci
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1463 Add the libguestfs tools image digest to KubeVirt env vars
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/build-manifests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1464 Fix the runbook links in the alerts
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/controller/operands/monitoring.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1445 Undo workaround to reduce bundle size
  deploy/crds/cluster-network-addons00.crd.yaml
  deploy/crds/containerized-data-importer00.crd.yaml
  deploy/crds/hostpath-provisioner00.crd.yaml
  deploy/crds/kubevirt00.crd.yaml
  deploy/crds/vm-import-operator00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/cluster-network-addons00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/containerized-data-importer00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/vm-import-operator00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/cluster-network-addons00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/vm-import-operator00.crd.yaml
  hack/build-manifests.sh
  hack/strip_old_descriptions.py
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#1467 Add container for virt-artifacts-server
  Makefile
  build/Dockerfile.artifacts
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#1468 Improve virtctl-artifacts-server container
  build/Dockerfile.artifacts
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1470 Fix WORKDIR for virt-artifacts-server
  build/Dockerfile.artifacts
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1474 Dump state on functest failure
  hack/run-tests-in-container.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#1475 Consume kubevirt v0.41.3 to enable upgrades to OCP 4.9
  deploy/cluster_role.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  vendor/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  vendor/kubevirt.io/client-go/api/v1/openapi_generated.go
  vendor/kubevirt.io/client-go/api/v1/types.go
  vendor/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  vendor/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  vendor/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  vendor/kubevirt.io/client-go/kubecli/kubevirt.go
  vendor/kubevirt.io/client-go/kubecli/vm.go
  vendor/kubevirt.io/client-go/kubecli/vmi.go
  vendor/kubevirt.io/kubevirt/pkg/cloud-init/cloud-init.go
  vendor/kubevirt.io/kubevirt/pkg/virt-operator/resource/generate/components/webhooks.go
  vendor/kubevirt.io/kubevirt/pkg/virtctl/root.go
  vendor/kubevirt.io/kubevirt/pkg/virtctl/vm/vm.go
  vendor/kubevirt.io/kubevirt/tests/BUILD.bazel
  vendor/kubevirt.io/kubevirt/tests/flags/flags.go
  vendor/kubevirt.io/kubevirt/tests/io_utils.go
  vendor/kubevirt.io/kubevirt/tests/utils.go
  vendor/modules.txt
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#1480 [Release-1.4] fix KV version
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/config
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1488 Auto bump kubevirt-ci to the latest release
  cluster/kubevirtci.sh
  hack/bump-kubevirtci.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#1487 Serve virtctl binaries from cluster for disconnected environments
  cmd/hyperconverged-cluster-operator/main.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/build-manifests.sh
  hack/deploy.sh
  pkg/components/components.go
  pkg/controller/commonTestUtils/testUtils.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/cliDownload.go
  pkg/controller/operands/cliDownload_test.go
  pkg/controller/operands/operandHandler.go
  pkg/util/cluster.go
  pkg/util/consts.go
  tests/func-tests/cli_download_test.go
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
  vendor/github.com/openshift/api/route/v1/doc.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/legacy.go
  vendor/github.com/openshift/api/route/v1/register.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: release-note-none, size/XXL, dco-signoff: yes

#1495 increase the timeout of the digester to to 30 seconds
  tools/digester/main.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1490 Bump version to 1.6.0
  README.md
  deploy/index-image/Dockerfile.bundle.ci-index-image-upgrade
  deploy/index-image/bundle.Dockerfile
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/cluster-network-addons00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/containerized-data-importer00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/hco01.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/hco02.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/node-maintenance00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/vm-import-operator00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/metadata/annotations.yaml
  deploy/kustomize/base/subscription.yaml
  deploy/kustomize/deploy_kustomize.sh
  deploy/kustomize/image_registry/catalog_source.yaml
  deploy/olm-catalog/Dockerfile.bundle.ci-index-image-upgrade
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/cluster-network-addons00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/hco01.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/hco02.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/node-maintenance00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/vm-import-operator00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/metadata/annotations.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/kubevirt-hyperconverged.package.yaml
  deploy/operator.yaml
  docs/functest-container.md
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  version/version.go
Labels: size/XXL, release-note, lgtm, approved

#1497 Update digest of downloads image in index
  .github/workflows/build-push-images.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1498 [release-1.5] Update digest of downloads image in index
  .github/workflows/build-push-images.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1500 Replace PNG icon with SVG one
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  pkg/components/components.go
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#1511 Setup Go version on GitHub actions
  .github/workflows/build-push-images.yaml
  .github/workflows/publish-community-operators.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1513 Cancel 2-phase init of some reources
  cmd/cmdcommon/cmdcommon.go
  cmd/hyperconverged-cluster-operator/main.go
  cmd/hyperconverged-cluster-webhook/main.go
  pkg/controller/commonTestUtils/eventEmitterMock.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/util/cluster.go
  pkg/util/event_emmiter.go
  pkg/util/util.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved
