Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2021-01, with the labels that each got.

#1029 Adds how to run webhook from local environment
  deploy/deploy.sh
  docs/run-locally.md
  hack/local_webhook.sh
  hack/make_local.py
  hack/make_local.sh
  pkg/apis/hco/v1beta1/hyperconverged_webhook.go
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1034 Allow setting the 'HotplugVolumes' KV feature gate from HC CR
  deploy/crds/hco00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/hyperconverged_types_test.go
  pkg/apis/hco/v1beta1/zz_generated.deepcopy.go
  pkg/apis/hco/v1beta1/zz_generated.openapi.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
  pkg/util/util.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1035 Remove unused local.yaml
  hack/generate_local_env.py
  hack/make_local.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#994 Add recommended labels into operands&OLM workloads
  deploy/cluster_role.yaml
  deploy/index-image/kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/check_labels.sh
  hack/run-tests.sh
  hack/upgrade-test.sh
  pkg/apis/hco/v1alpha1/hyperconverged_resources.go
  pkg/components/components.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cliDownload.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/monitoring.go
  pkg/controller/operands/networkAddons.go
  pkg/controller/operands/operand.go
  pkg/controller/operands/quickStart.go
  pkg/controller/operands/ssp.go
  pkg/controller/operands/vmImport.go
  pkg/util/consts.go
  pkg/util/labels.go
  pkg/util/util.go
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
  tools/util/csv_with_component.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1039 test: tolerate conditions with Unknown status
  hack/check-state.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1040 Update digests of the new operator and webhook 1.3.0 images
  deploy/images.csv
  deploy/images.env
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1028 Apply unsupported feature annotations
  go.mod
  pkg/apis/hco/v1alpha1/hyperconverged_types_test.go
  pkg/apis/hco/v1beta1/hyperconverged_types_test.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cdi_test.go
  pkg/controller/operands/ensure_result_test.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
  pkg/controller/operands/monitoring.go
  pkg/controller/operands/networkAddons.go
  pkg/controller/operands/networkAddons_test.go
  pkg/controller/operands/operand.go
  pkg/controller/operands/operandHandler.go
  pkg/controller/operands/operand_test.go
  pkg/controller/operands/quickStart.go
  pkg/controller/operands/ssp.go
  pkg/controller/operands/vmImport.go
  pkg/webhooks/webhooks.go
  pkg/webhooks/webhooks_test.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1045 Bump NETWORK_ADDONS to v0.44.1
  deploy/images.csv
  deploy/images.env
  deploy/index-image/kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1alpha1/register.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1051 Bump VM_IMPORT to v0.3.0
  deploy/crds/vm-import-operator00.crd.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/index-image/kubevirt-hyperconverged/1.4.0/vm-import-operator00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/vm-import-operator00.crd.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/README.md
  vendor/github.com/emicklei/go-restful/path_processor.go
  vendor/github.com/emicklei/go-restful/response.go
  vendor/github.com/kubevirt/vm-import-operator/pkg/apis/v2v/v1beta1/register.go
  vendor/github.com/kubevirt/vm-import-operator/pkg/apis/v2v/v1beta1/resourcemapping_types.go
  vendor/github.com/kubevirt/vm-import-operator/pkg/apis/v2v/v1beta1/virtualmachineimport_types.go
  vendor/github.com/kubevirt/vm-import-operator/pkg/apis/v2v/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/scheme/scheme.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1053 Bump SSP to v0.1.1
  deploy/images.csv
  deploy/images.env
  deploy/index-image/kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1054 Change alert name
  pkg/controller/operands/monitoring.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1052 Fix webhook configuration of ssp
  deploy/operator.yaml
  deploy/webhooks.yaml
  hack/deploy.sh
  tools/manifest-templator/manifest-templator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1048 Cache operad CRs
  deploy/deploy.sh
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/operands/cdi.go
  pkg/controller/operands/cdi_test.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
  pkg/controller/operands/monitoring.go
  pkg/controller/operands/networkAddons.go
  pkg/controller/operands/networkAddons_test.go
  pkg/controller/operands/operand.go
  pkg/controller/operands/operandHandler.go
  pkg/controller/operands/quickStart.go
  pkg/controller/operands/ssp.go
  pkg/controller/operands/ssp_test.go
  pkg/controller/operands/vmImport.go
  pkg/controller/operands/vmImport_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1056 Fix security issues forcing a few dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1057 [release-1.3] Fix security issues forcing a few dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1047 Add ENABLE_SSP option to hack/deploy.sh script
  deploy/operator.yaml
  deploy/webhooks.yaml
  hack/deploy.sh
  tools/manifest-templator/manifest-templator.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1060 Change the FeatureGates implemantation
  deploy/crds/hco00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  docs/cluster-configuration.md
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/hyperconverged_types_test.go
  pkg/apis/hco/v1beta1/zz_generated.deepcopy.go
  pkg/apis/hco/v1beta1/zz_generated.openapi.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1062 [Release 1.3] Change the FeatureGates implemantation (#1060)
  deploy/crds/hco00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.3.0/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/hco00.crd.yaml
  docs/cluster-configuration.md
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/hyperconverged_types_test.go
  pkg/apis/hco/v1beta1/zz_generated.deepcopy.go
  pkg/apis/hco/v1beta1/zz_generated.openapi.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1065 [release-1.3] Rebuild Operator and Webhook Images
  .github/workflows/pr-sanity.yaml
  deploy/images.csv
  deploy/images.env
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1067 Sync deploy files with release 1.3.0
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1066 Use KubeVirt Images From quay.io
  automation/release-bumper/release-bumper.sh
  deploy/images.csv
  deploy/images.env
  deploy/index-image/kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  tools/digester/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1068 Bump golang.org/x/crypto to fix a security issue
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/sys/plan9/asm.s
  vendor/golang.org/x/sys/plan9/asm_plan9_386.s
  vendor/golang.org/x/sys/plan9/asm_plan9_amd64.s
  vendor/golang.org/x/sys/plan9/asm_plan9_arm.s
  vendor/golang.org/x/sys/plan9/const_plan9.go
  vendor/golang.org/x/sys/plan9/dir_plan9.go
  vendor/golang.org/x/sys/plan9/env_plan9.go
  vendor/golang.org/x/sys/plan9/errors_plan9.go
  vendor/golang.org/x/sys/plan9/mkall.sh
  vendor/golang.org/x/sys/plan9/mkerrors.sh
  vendor/golang.org/x/sys/plan9/mksysnum_plan9.sh
  vendor/golang.org/x/sys/plan9/pwd_go15_plan9.go
  vendor/golang.org/x/sys/plan9/pwd_plan9.go
  vendor/golang.org/x/sys/plan9/race.go
  vendor/golang.org/x/sys/plan9/race0.go
  vendor/golang.org/x/sys/plan9/str.go
  vendor/golang.org/x/sys/plan9/syscall.go
  vendor/golang.org/x/sys/plan9/syscall_plan9.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_386.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_amd64.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_arm.go
  vendor/golang.org/x/sys/plan9/zsysnum_plan9.go
  vendor/golang.org/x/term/AUTHORS
  vendor/golang.org/x/term/CONTRIBUTING.md
  vendor/golang.org/x/term/CONTRIBUTORS
  vendor/golang.org/x/term/LICENSE
  vendor/golang.org/x/term/PATENTS
  vendor/golang.org/x/term/README.md
  vendor/golang.org/x/term/go.mod
  vendor/golang.org/x/term/go.sum
  vendor/golang.org/x/term/term.go
  vendor/golang.org/x/term/term_plan9.go
  vendor/golang.org/x/term/term_solaris.go
  vendor/golang.org/x/term/term_unix.go
  vendor/golang.org/x/term/term_unix_aix.go
  vendor/golang.org/x/term/term_unix_bsd.go
  vendor/golang.org/x/term/term_unix_linux.go
  vendor/golang.org/x/term/term_unix_zos.go
  vendor/golang.org/x/term/term_unsupported.go
  vendor/golang.org/x/term/term_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1063 Add Two New Feature Gates
  deploy/crds/hco00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  docs/cluster-configuration.md
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/hyperconverged_types_test.go
  pkg/apis/hco/v1beta1/zz_generated.deepcopy.go
  pkg/apis/hco/v1beta1/zz_generated.openapi.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1071 [release-1.3] Bump golang.org/x/crypto to fix a security issue (#1068)
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/sys/plan9/asm.s
  vendor/golang.org/x/sys/plan9/asm_plan9_386.s
  vendor/golang.org/x/sys/plan9/asm_plan9_amd64.s
  vendor/golang.org/x/sys/plan9/asm_plan9_arm.s
  vendor/golang.org/x/sys/plan9/const_plan9.go
  vendor/golang.org/x/sys/plan9/dir_plan9.go
  vendor/golang.org/x/sys/plan9/env_plan9.go
  vendor/golang.org/x/sys/plan9/errors_plan9.go
  vendor/golang.org/x/sys/plan9/mkall.sh
  vendor/golang.org/x/sys/plan9/mkerrors.sh
  vendor/golang.org/x/sys/plan9/mksysnum_plan9.sh
  vendor/golang.org/x/sys/plan9/pwd_go15_plan9.go
  vendor/golang.org/x/sys/plan9/pwd_plan9.go
  vendor/golang.org/x/sys/plan9/race.go
  vendor/golang.org/x/sys/plan9/race0.go
  vendor/golang.org/x/sys/plan9/str.go
  vendor/golang.org/x/sys/plan9/syscall.go
  vendor/golang.org/x/sys/plan9/syscall_plan9.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_386.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_amd64.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_arm.go
  vendor/golang.org/x/sys/plan9/zsysnum_plan9.go
  vendor/golang.org/x/term/AUTHORS
  vendor/golang.org/x/term/CONTRIBUTING.md
  vendor/golang.org/x/term/CONTRIBUTORS
  vendor/golang.org/x/term/LICENSE
  vendor/golang.org/x/term/PATENTS
  vendor/golang.org/x/term/README.md
  vendor/golang.org/x/term/go.mod
  vendor/golang.org/x/term/go.sum
  vendor/golang.org/x/term/term.go
  vendor/golang.org/x/term/term_plan9.go
  vendor/golang.org/x/term/term_solaris.go
  vendor/golang.org/x/term/term_unix.go
  vendor/golang.org/x/term/term_unix_aix.go
  vendor/golang.org/x/term/term_unix_bsd.go
  vendor/golang.org/x/term/term_unix_linux.go
  vendor/golang.org/x/term/term_unix_zos.go
  vendor/golang.org/x/term/term_unsupported.go
  vendor/golang.org/x/term/term_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1076 Set the KUBEVIRT_CLIENT_GO_SCHEME_REGISTRATION_VERSION env var in all Dockerfiles
  build/Dockerfile
  build/Dockerfile.okd
  build/Dockerfile.webhook
  build/Dockerfile.wh.okd
  hack/generate_local_env.py
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1077 Fix SonarCloud Issues
  hack/generate_local_env.py
  pkg/components/components.go
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1078 Fix Critical SonarCloud Issues
  cmd/hyperconverged-cluster-operator/main.go
  cmd/hyperconverged-cluster-webhook/main.go
  pkg/apis/hco/v1beta1/hyperconverged_webhook.go
  pkg/controller/operands/cdi.go
  pkg/controller/operands/monitoring.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1088 [release-1.3] Bump SSP to v0.1.3
  deploy/crds/scheduling-scale-performance00.crd.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/index-image/kubevirt-hyperconverged/1.3.0/scheduling-scale-performance00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/kubevirt-hyperconverged-operator.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/scheduling-scale-performance00.crd.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/kubevirt.io/ssp-operator/api/v1beta1/ssp_types.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1090 Bump SSP to v0.1.3
  deploy/images.csv
  deploy/images.env
  deploy/index-image/kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1084 Remove hack/operator-test.sh and ancillary files
  hack/README.md
  hack/common.sh
  hack/defaults
  hack/operator-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1080 Refactor digeser to fix sonarClaud issue
  tools/csv-merger/csv-merger.go
  tools/digester/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1089 Try to fix the covaeralls issue
  .github/workflows/pr-sanity.yaml
  hack/build-tests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1091 Reduce SonarCloud Number of Warnings
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/networkAddons.go
  pkg/controller/operands/quickStart.go
  pkg/controller/operands/vmImport.go
  tests/func-tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1027 Publish updated images on every merge
  .github/workflows/build-push-images.yaml
  Makefile
  automation/digester/update_images.sh
  deploy/images.csv
  deploy/olm-catalog/kubevirt-hyperconverged/kubevirt-hyperconverged.package.yaml
  hack/build-index-image.sh
  hack/build-manifests.sh
  tools/csv-merger/csv-merger.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1097 Fix a bug where HCO is ready while there is handling one of the operand returns error
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1096 Reduce number of sonarCloud warnings
  pkg/controller/operands/ensure_result.go
  pkg/controller/operands/ensure_result_test.go
  pkg/controller/operands/operand.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1099 Add SonarCloud badge to the project README
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1101 Fix SonarCloud Issues on Override-Bot
  automation/override-bot/override-bot.py
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1100 Reduce SonarClaud number of warnings
  pkg/controller/commonTestUtils/eventEmitterMock.go
  pkg/controller/operands/quickStart.go
  pkg/controller/operands/quickStart_test.go
  pkg/controller/operands/ssp.go
  pkg/util/util.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1102 Fix various SonarCloud Issues
  pkg/components/components.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1107 Welcome Nico!
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1106 Hotfix bash array handling in hack/deploy.sh
  hack/deploy.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1108 Fix sonarCloud warnings at tools/manifest-templator/manifest-templator.go
  tools/manifest-templator/manifest-templator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#1087 Add labels to functional tests
  hack/run-tests.sh
  tests/func-tests/csv_tests.go
  tests/func-tests/dependency_objects_test.go
  tests/func-tests/node_placement_test.go
  tests/func-tests/unprivileged_test.go
  tests/func-tests/virtual_machines_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#1109 Apply default CPU model configuration for VM live migration
  deploy/crds/hco00.crd.yaml
  deploy/index-image/kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/hco00.crd.yaml
  deploy/olm-catalog/kubevirt-hyperconverged/1.4.0/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  pkg/apis/hco/v1beta1/hyperconverged_types.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1110 refactor tools/util/marshaller.go
  tools/util/marshaller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1112 Fix CSV upgrade workflow
  hack/build-index-image.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1111 Reduce sonarCloud comments
  tools/csv-merger/csv-merger.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L
