Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2021-10, with the labels that each got.

#1323 Temporary workaround to trigger upgrade
  hack/upgrade-test-index-image.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1548 Bump components to get ready for 1.4.2
  deploy/cluster_role.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.4.0/manifests/kubevirt-hyperconverged-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/build-manifests.sh
  hack/config
  hack/run-tests-in-container.sh
  hack/upgrade-test-index-image.sh
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/upload/v1alpha1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/upload/v1beta1/openapi_generated.go
  vendor/modules.txt
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#1553 Fix an issue with setting the dataImportCronTemplates field
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/hco00.crd.yaml
  pkg/components/components.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#1546 Set priority class for hyperconverged-cluster-cli-download
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/components/components.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#1558 Fix out of date resource versions of objects in relatedObjects
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/operand.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved
