Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2021-09, with the labels that each got.

#1414 Report Upgradable OperatorCondition to OLM
  cmd/cmdcommon/cmdcommon.go
  cmd/hyperconverged-cluster-operator/main.go
  cmd/hyperconverged-cluster-webhook/main.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  hack/check_operator_condition.sh
  hack/run-tests.sh
  hack/upgrade-test-index-image.sh
  pkg/components/components.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/util/cluster.go
  pkg/util/cluster_test.go
  pkg/util/error.go
  pkg/util/event_emmiter.go
  pkg/util/event_emmiter_test.go
  pkg/util/file.go
  pkg/util/file_test.go
  pkg/util/hcoping.go
  pkg/util/hcoping_test.go
  pkg/util/operatorcondition.go
  pkg/util/operatorcondition_test.go
  pkg/util/util.go
  vendor/github.com/operator-framework/api/pkg/operators/v2/doc.go
  vendor/github.com/operator-framework/api/pkg/operators/v2/groupversion_info.go
  vendor/github.com/operator-framework/api/pkg/operators/v2/operatorcondition_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v2/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/operator-lib/conditions/conditions.go
  vendor/github.com/operator-framework/operator-lib/conditions/interface.go
  vendor/github.com/operator-framework/operator-lib/internal/utils/utils.go
  vendor/k8s.io/client-go/util/retry/OWNERS
  vendor/k8s.io/client-go/util/retry/util.go
  vendor/modules.txt
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#1519 Add .gz extension into virtctl.tar
  build/Dockerfile.artifacts
  pkg/controller/operands/cliDownload.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1523 Document why we don't have a race condition removing v2v
  hack/upgrade-test-index-image.sh
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#1527 Remove unused constant
  pkg/util/consts.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1526 Remove the IMAGE_FORMAT env var from the E2E test
  hack/run-tests-in-container.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1525 Implement the data import cron feature (golden images)
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  docs/api.md
  docs/cluster-configuration.md
  hack/check_defaults.sh
  hack/run-tests-in-container.sh
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/zz_generated.deepcopy.go
  pkg/apis/hco/v1beta1/zz_generated.openapi.go
  pkg/controller/hyperconverged/dataimportschedule.go
  pkg/controller/hyperconverged/dataimportschedule_test.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/operands/ssp.go
  pkg/controller/operands/ssp_test.go
  pkg/controller/operands/testFiles/dataImportCronTemplates/dataImportCronTemplates.yaml
  pkg/controller/operands/testFiles/dataImportCronTemplates/wrongDataImportCronTemplates.yaml
  tools/digester/main.go
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#1534 Declare proxy support
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  pkg/components/components.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#1535 Rename the golden images feature gate to enableCommonBootImageImport
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  hack/check_defaults.sh
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/zz_generated.openapi.go
  pkg/controller/operands/ssp.go
  pkg/controller/operands/ssp_test.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#1533 Update dashboards path to be used by OCP UI
  .github/workflows/dashboard-updater.yml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1536 Add golden images file
  assets/dataImportCronTemplates/dataImportCronTemplates.yaml
  build/Dockerfile
  build/Dockerfile.okd
  build/Dockerfile.webhook
  build/Dockerfile.wh.okd
  hack/check_golden_images.sh
  hack/run-tests.sh
  hack/upgrade-test-index-image.sh
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#1537 Bump dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/ascii.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux_386.go
  vendor/golang.org/x/sys/unix/ztypes_linux_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mipsle.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_s390x.go
  vendor/golang.org/x/sys/unix/ztypes_linux_sparc64.go
  vendor/golang.org/x/tools/go/internal/gcimporter/bimport.go
  vendor/golang.org/x/tools/go/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/go/internal/gcimporter/support_go117.go
  vendor/golang.org/x/tools/go/internal/gcimporter/support_go118.go
  vendor/golang.org/x/tools/internal/typeparams/common.go
  vendor/golang.org/x/tools/internal/typeparams/enabled_go117.go
  vendor/golang.org/x/tools/internal/typeparams/enabled_go118.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/LICENSE
  vendor/k8s.io/apimachinery/third_party/forked/golang/PATENTS
  vendor/k8s.io/client-go/third_party/forked/golang/LICENSE
  vendor/k8s.io/client-go/third_party/forked/golang/PATENTS
  vendor/k8s.io/client-go/util/jsonpath/jsonpath.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-tools/pkg/crd/conv.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/gen.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/topology.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/validation.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/schema.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/genall.go
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#1530 Add new recording rule "cluster:vmi_request_cpu_cores:sum"
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/controller/operands/monitoring.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#1542 Avoid setting Evict workloadUpdates strategy
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  hack/check_defaults.sh
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/components/components.go
  pkg/controller/operands/kubevirt_test.go
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#1543 [release-1.5] Avoid setting Evict workloadUpdates strategy
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  hack/check_defaults.sh
  hack/run-tests-in-container.sh
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/components/components.go
  pkg/controller/operands/kubevirt_test.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved
