Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2022-04, with the labels that each got.

#1847 Remove nmstate from deployed components in networkaddonsconfig
  controllers/operands/networkAddons.go
  controllers/operands/networkAddons_test.go
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#1848 Add component graphs
  .github/workflows/graphs-updater.yml
  automation/graphs-updater/graphs-updater.sh
  docs/component.gv
  docs/component.gv.svg
  docs/hco_components.md
  docs/managed-by.gv
  docs/managed-by.gv.svg
  tools/k8s-label-visualizer/dot_graph.py
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#1856 Fix component graphs automation
  .github/workflows/graphs-updater.yml
  README.md
  docs/hco_components.md
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#1852 Remove duplicated code
  controllers/hyperconverged/testUtils_test.go
  controllers/operands/cliDownload.go
  controllers/operands/cliDownload_test.go
  controllers/operands/kubevirtConsolePlugin.go
  controllers/operands/kubevirtConsolePlugin_test.go
  controllers/operands/monitoring.go
  controllers/operands/monitoring_test.go
  controllers/operands/operandHandler.go
  controllers/operands/serviceHandler.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#1821 onboard new operator tekton-tasks-operator
  README.md
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  automation/release-bumper/release-bumper.sh
  cmd/hyperconverged-cluster-operator/main.go
  cmd/hyperconverged-cluster-webhook/main.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/commonTestUtils/testUtils.go
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/hyperconverged/testUtils_test.go
  controllers/operands/operandHandler.go
  controllers/operands/operandHandler_test.go
  controllers/operands/tto.go
  controllers/operands/tto_test.go
  deploy/cluster_role.yaml
  deploy/cluster_role_binding.yaml
  deploy/crds/hco00.crd.yaml
  deploy/crds/tekton-tasks-operator00.crd.yaml
  deploy/hco.cr.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/tekton-tasks-operator00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/tekton-tasks-operator00.crd.yaml
  deploy/operator.yaml
  deploy/service_account.yaml
  docs/api.md
  docs/cluster-configuration.md
  go.mod
  go.sum
  hack/build-manifests.sh
  hack/check_defaults.sh
  hack/clean.sh
  hack/common.sh
  hack/config
  hack/deploy.sh
  pkg/components/components.go
  pkg/util/consts.go
  pkg/webhooks/validator/validator.go
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
  tools/release-notes/types.go
  vendor/github.com/kubevirt/tekton-tasks-operator/api/v1alpha1/groupversion_info.go
  vendor/github.com/kubevirt/tekton-tasks-operator/api/v1alpha1/tektontasks_types.go
  vendor/github.com/kubevirt/tekton-tasks-operator/api/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#1857 Fix again component graphs automation
  .github/workflows/graphs-updater.yml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1846 Enable NonRoot feature gate by default
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#1860 daily check for component graph updates
  .github/workflows/graphs-updater.yml
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#1859 Allow setting all the fields of a common DICT spec
  controllers/operands/ssp.go
  controllers/operands/ssp_test.go
  docs/cluster-configuration.md
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1851 Allow controlling filesystem overhead
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/cdi.go
  controllers/operands/cdi_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1869 graphs updater: abort when fetching wrong data
  automation/graphs-updater/graphs-updater.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1874 Also run build-push-images action on changes in tests/
  .github/workflows/build-push-images.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1870 Fix deploy/deploy.sh on plain k8s
  deploy/deploy.sh
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#1876 sanity: check for unvedored code
  Makefile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1854 Manually Bump SSP to v0.14.0
  automation/release-bumper/release-bumper.sh
  deploy/cluster_role.yaml
  deploy/crds/scheduling-scale-performance00.crd.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/kubevirt.io/ssp-operator/api/LICENSE
  vendor/kubevirt.io/ssp-operator/api/v1beta1/constants.go
  vendor/kubevirt.io/ssp-operator/api/v1beta1/ssp_types.go
  vendor/kubevirt.io/ssp-operator/api/v1beta1/ssp_webhook.go
  vendor/kubevirt.io/ssp-operator/api/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#1879 bump kubevirt.io/controller-lifecycle-operator-sdk
  api/v1beta1/hyperconverged_types.go
  controllers/commonTestUtils/testUtils.go
  controllers/operands/cdi.go
  controllers/operands/networkAddons.go
  controllers/operands/networkAddons_test.go
  controllers/operands/ssp.go
  controllers/operands/ssp_test.go
  go.mod
  go.sum
  pkg/webhooks/validator/validator_test.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/api/LICENSE
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/api/types.go
  vendor/modules.txt
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1881 set supported labels on the CSV
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#1885 set supported labels on the CSV (#1881)
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  tools/csv-merger/csv-merger.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#1830 Add metrics types to HCO metrics documentation
  docs/metrics.md
  pkg/metrics/metrics.go
  tools/metricsdocs/metricsdocs.go
Labels: size/S, release-note-none, needs-ok-to-test, dco-signoff: yes, lgtm, approved

#1889 Avoid an explicit cast in operands/cdi.go
  controllers/operands/cdi.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1896 [release-1.6] Make the removal of relatedObjects more robust
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#1895 onboard new operator tekton-tasks-operator
  README.md
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  automation/release-bumper/release-bumper.sh
  cmd/hyperconverged-cluster-operator/main.go
  cmd/hyperconverged-cluster-webhook/main.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/commonTestUtils/testUtils.go
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/hyperconverged/testUtils_test.go
  controllers/operands/operandHandler.go
  controllers/operands/operandHandler_test.go
  controllers/operands/tto.go
  controllers/operands/tto_test.go
  deploy/cluster_role.yaml
  deploy/cluster_role_binding.yaml
  deploy/crds/hco00.crd.yaml
  deploy/crds/tekton-tasks-operator00.crd.yaml
  deploy/hco.cr.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/tekton-tasks-operator00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/tekton-tasks-operator00.crd.yaml
  deploy/operator.yaml
  deploy/service_account.yaml
  docs/api.md
  docs/cluster-configuration.md
  go.mod
  go.sum
  hack/build-manifests.sh
  hack/check_defaults.sh
  hack/clean.sh
  hack/common.sh
  hack/config
  hack/deploy.sh
  pkg/components/components.go
  pkg/util/consts.go
  pkg/webhooks/validator/validator.go
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
  tools/release-notes/types.go
  vendor/github.com/kubevirt/tekton-tasks-operator/api/v1alpha1/groupversion_info.go
  vendor/github.com/kubevirt/tekton-tasks-operator/api/v1alpha1/tektontasks_types.go
  vendor/github.com/kubevirt/tekton-tasks-operator/api/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#1893 Configure the client cache for corev1.Endpoints
  cmd/hyperconverged-cluster-operator/main.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1901 Enable kubevirt console plugin integration
  automation/release-bumper/release-bumper.sh
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  hack/build-manifests.sh
  hack/config
  hack/patch_og.sh
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#1902 Bump github.com/kubernetes-csi/external-snapshotter/v2 in tests
  tests/go.mod
  tests/go.sum
  tests/vendor/modules.txt
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#1904 fix service port string replacement for the kubevirt console plugin nginx configuration
  controllers/operands/kubevirtConsolePlugin.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#1907 Add a deprecation notice for `localStorageClassName` field at HyperConvergedSpec
  api/v1beta1/hyperconverged_types.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  docs/api.md
  docs/cluster-configuration.md
  docs/conditions.md
  docs/config.md
  docs/dev-tools.md
  docs/kni.md
  docs/operator_description.md
  docs/status.md
  docs/tests.md
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1909 [release-1.6] Avoid special handling for liveMigration FG on SNO
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1908 Avoid special handling for liveMigration FG on SNO
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1913 Fix unit test that fails in github action
  pkg/util/operatorcondition_test.go
  pkg/webhooks/mutator/mutator_test.go
  pkg/webhooks/setup_test.go
  pkg/webhooks/validator/validator_test.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved
