Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2022-03, with the labels that each got.

#1791 Add kube-rbac-proxy image by digest for CNAO
  deploy/images.csv
  deploy/images.env
  hack/build-manifests.sh
  hack/config
Labels: size/XS, dco-signoff: yes, lgtm, approved

#1805 Rollback CNAO to v0.67.0 and update NMO digests
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/modules.txt
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1717 Enhancement proposal for a cluster-wide Crypto Policy Setting
  docs/enhancements/crypto-api.md
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#1799 Opt-out from cluster-wide default node selector
  cmd/hyperconverged-cluster-operator/main.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  pkg/components/components.go
  pkg/controller/commonTestUtils/testUtils.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/imageStream_test.go
  pkg/controller/operands/namespace.go
  pkg/controller/operands/namespace_test.go
  pkg/controller/operands/operandHandler.go
  pkg/controller/operands/operandHandler_test.go
  pkg/util/consts.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1816 [release-1.6] Opt-out from cluster-wide default node selector (#1799)
  cmd/hyperconverged-cluster-operator/main.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  pkg/components/components.go
  pkg/controller/commonTestUtils/testUtils.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/testUtils_test.go
  pkg/controller/operands/imageStream_test.go
  pkg/controller/operands/namespace.go
  pkg/controller/operands/namespace_test.go
  pkg/controller/operands/operandHandler.go
  pkg/controller/operands/operandHandler_test.go
  pkg/util/consts.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1813 Fix cache miss hit on resource recreation
  hack/run-tests.sh
  pkg/controller/operands/operand.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#1819 Ignore sriovLiveMigration FG on SNO
  api/v1beta1/hyperconverged_types.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1823 Filter out LiveMigrate workloadUpdateMethod on SNO
  api/v1beta1/hyperconverged_types.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1788 Visualize k8s labels
  build/Dockerfile.functest
  build/Dockerfile.functest.ci
  hack/kubevirt-nightly-test.sh
  tools/k8s-label-visualizer/.gitignore
  tools/k8s-label-visualizer/README.md
  tools/k8s-label-visualizer/conf.json
  tools/k8s-label-visualizer/configuration.py
  tools/k8s-label-visualizer/dot_graph.py
  tools/k8s-label-visualizer/k8s_fetcher.py
  tools/k8s-label-visualizer/main.py
  tools/k8s-label-visualizer/metrics.py
  tools/k8s-label-visualizer/requirements.txt
  tools/k8s-label-visualizer/run.sh
Labels: size/XL, release-note-none, dco-signoff: yes, lgtm, approved

#1824 Remove leftovers during upgrades
  assets/upgradePatches.json
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/hyperconverged/test-files/upgradePatches/badObject1.json
  controllers/hyperconverged/test-files/upgradePatches/badObject1m.json
  controllers/hyperconverged/test-files/upgradePatches/badObject2.json
  controllers/hyperconverged/test-files/upgradePatches/badObject2m.json
  controllers/hyperconverged/test-files/upgradePatches/badObject3.json
  controllers/hyperconverged/test-files/upgradePatches/badObject3m.json
  controllers/hyperconverged/test-files/upgradePatches/badSemverRangeOR.json
  controllers/hyperconverged/test-files/upgradePatches/upgradePatches.json
  controllers/hyperconverged/upgradePatches.go
  controllers/hyperconverged/upgradePatches_test.go
  controllers/operands/imageStream.go
  controllers/operands/operandHandler.go
  pkg/util/util.go
  pkg/util/util_test.go
  pkg/webhooks/validator/validator.go
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#1836 [release-1.6] Remove leftovers during upgrades (#1824)
  assets/upgradePatches.json
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/hyperconverged/test-files/upgradePatches/badObject1.json
  pkg/controller/hyperconverged/test-files/upgradePatches/badObject1m.json
  pkg/controller/hyperconverged/test-files/upgradePatches/badObject2.json
  pkg/controller/hyperconverged/test-files/upgradePatches/badObject2m.json
  pkg/controller/hyperconverged/test-files/upgradePatches/badObject3.json
  pkg/controller/hyperconverged/test-files/upgradePatches/badObject3m.json
  pkg/controller/hyperconverged/test-files/upgradePatches/badSemverRangeOR.json
  pkg/controller/hyperconverged/upgradePatches.go
  pkg/controller/hyperconverged/upgradePatches_test.go
  pkg/controller/operands/imageStream.go
  pkg/controller/operands/operandHandler.go
  pkg/util/util.go
  pkg/util/util_test.go
  pkg/webhooks/validator/validator.go
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#1832 Allow editing and disabling common DataImportCronTemplates
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/hyperconverged/testUtils_test.go
  controllers/operands/cdi.go
  controllers/operands/cliDownload.go
  controllers/operands/cmHandler.go
  controllers/operands/imageStream.go
  controllers/operands/kubevirt.go
  controllers/operands/monitoring.go
  controllers/operands/networkAddons.go
  controllers/operands/operand.go
  controllers/operands/quickStart.go
  controllers/operands/rbac.go
  controllers/operands/ssp.go
  controllers/operands/ssp_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  go.mod
  pkg/webhooks/validator/validator.go
  pkg/webhooks/validator/validator_test.go
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#1835 Fix a race condition on object recreation
  controllers/operands/operand.go
  controllers/operands/operand_test.go
Labels: size/L, dco-signoff: yes, lgtm, approved

#1839 [release-1.6] Fix a race condition on object recreation (#1835)
  pkg/controller/operands/operand.go
  pkg/controller/operands/operand_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1833 Update version filtering in 'check_operator_condition'
  hack/check_operator_condition.sh
  hack/run-tests.sh
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#1842 Code cleanup: change Expect(err).To(BeNil()) to Expect(err).ToNot(HaveOccurred())
  controllers/commonTestUtils/testUtils.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/hyperconverged/testUtils_test.go
  controllers/operands/cdi_test.go
  controllers/operands/cliDownload_test.go
  controllers/operands/ensure_result_test.go
  controllers/operands/imageStream_test.go
  controllers/operands/kubevirt_test.go
  controllers/operands/monitoring_test.go
  controllers/operands/namespace_test.go
  controllers/operands/networkAddons_test.go
  controllers/operands/quickStart_test.go
  controllers/operands/ssp_test.go
  controllers/operands/virtio_win_ConfigMap_test.go
  pkg/util/operatorcondition_test.go
  pkg/webhooks/validator/validator_test.go
  tests/func-tests/cli_download_test.go
  tests/func-tests/quickstart_test.go
Labels: size/XL, release-note-none, dco-signoff: yes, lgtm, approved

#1844 k8s-label-visualizer: try KUBECONFIG first
  tools/k8s-label-visualizer/k8s_fetcher.py
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1837 bump golang dependencies
  go.mod
  go.sum
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/RELEASING.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/github.com/onsi/gomega/matchers/contain_element_matcher.go
  vendor/github.com/onsi/gomega/matchers/have_each_matcher.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/golang.org/x/mod/semver/semver.go
  vendor/golang.org/x/net/http2/go118.go
  vendor/golang.org/x/net/http2/not_go118.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/tools/go/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/gocommand/vendor.go
  vendor/golang.org/x/tools/internal/typeparams/common.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  vendor/golang.org/x/tools/internal/typesinternal/errorcode.go
  vendor/golang.org/x/tools/internal/typesinternal/errorcode_string.go
  vendor/golang.org/x/tools/internal/typesinternal/types.go
  vendor/golang.org/x/tools/internal/typesinternal/types_118.go
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/k8s.io/utils/clock/clock.go
  vendor/k8s.io/utils/clock/testing/fake_clock.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/modules.txt
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved
