Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2022-08, with the labels that each got.

#2046 digester: retry on docker.GetDigest failures
  tools/digester/main.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2045 Apply the ginkgolinter linter
  Makefile
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/kubevirt_test.go
  controllers/operands/operand_test.go
  pkg/webhooks/mutator/mutator_test.go
  tests/func-tests/cli_download_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2050 [bump-bot] update modules also in `tests/go.mod`
  automation/release-bumper/release-bumper.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2054 Migrate index generation process to File-Based Catalog
  .github/workflows/build-push-images.yaml
  hack/build-index-image.sh
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#2058 [FBC] add missing _out dir
  hack/build-index-image.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2043 Remove live migration feature gate since it's deprecated
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#2060 Keep using SQLite-based catalog for unstable tags
  hack/build-index-image.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2032 Fix Dependabot Alert - runc
  tests/go.mod
  tests/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/error.go
  tests/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/paths.go
  tests/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/rdma.go
  tests/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fscommon/rdma.go
  tests/vendor/github.com/opencontainers/runc/libcontainer/cgroups/getallpids.go
  tests/vendor/github.com/opencontainers/runc/libcontainer/configs/rdma.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2059 Enable VMExport feature gate by default
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/kubevirt.go
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.8.0/manifests/kubevirt-hyperconverged-operator.v1.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.8.0/manifests/kubevirt-hyperconverged-operator.v1.8.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/build-manifests.sh
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#2057 [bump-bot] Add module paths for kubevirt in `go.mod` to be updated
  automation/release-bumper/release-bumper.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2069 Removed unnecessary maintenance line in deploy.sh
  deploy/deploy.sh
Labels: release-note, size/XS, ok-to-test, dco-signoff: yes, lgtm, approved
