Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2022-02, with the labels that each got.

#1763 Remove workaround for bug #2031919
  hack/test_delete_ns.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#1768 add DataImportCron reference link to the cluster configuration document
  docs/cluster-configuration.md
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#1771 Start replacing Docker with Podman
  Makefile
  automation/nightly/test-nightly-build.sh
  cluster/sync.sh
  hack/build-in-docker.sh
  hack/build-index-image.sh
  hack/build-manifests.sh
  hack/cri-bin.sh
  hack/in-docker.sh
  hack/kubevirt-nightly-build-images.sh
  hack/prom-rule-ci/verify-rules.sh
  hack/upgrade-test-build-images.sh
  hack/upgrade-test-clusterserviceversion.sh
  tools/operator-courier/push.sh
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1711 Remove old HCO metrics services and endpoints when upgrading
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  pkg/components/components.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1775 Set 'console.openshift.io/disable-operand-delete' on the CSV to opt-out from operand removal from the console
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  pkg/components/components.go
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#1781 Add DataImportCron Source for CentOS7
  assets/dataImportCronTemplates/dataImportCronTemplates.yaml
  hack/check_golden_images.sh
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#1786 [Release 1.6] Set the CDI version to v1.43.2
  deploy/cluster_role.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/modules.txt
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1782 Fix Dependabot Alert in github.com/docker/distribution
  tools/digester/go.mod
  tools/digester/go.sum
  tools/digester/vendor/github.com/docker/distribution/.golangci.yml
  tools/digester/vendor/github.com/docker/distribution/.gometalinter.json
  tools/digester/vendor/github.com/docker/distribution/.mailmap
  tools/digester/vendor/github.com/docker/distribution/.travis.yml
  tools/digester/vendor/github.com/docker/distribution/Dockerfile
  tools/digester/vendor/github.com/docker/distribution/Makefile
  tools/digester/vendor/github.com/docker/distribution/blobs.go
  tools/digester/vendor/github.com/docker/distribution/docker-bake.hcl
  tools/digester/vendor/github.com/docker/distribution/manifests.go
  tools/digester/vendor/github.com/docker/distribution/reference/normalize.go
  tools/digester/vendor/github.com/docker/distribution/reference/reference.go
  tools/digester/vendor/github.com/docker/distribution/registry/api/errcode/errors.go
  tools/digester/vendor/github.com/docker/distribution/registry/api/v2/urls.go
  tools/digester/vendor/github.com/docker/distribution/registry/client/auth/challenge/authchallenge.go
  tools/digester/vendor/github.com/docker/distribution/registry/client/repository.go
  tools/digester/vendor/github.com/docker/distribution/vendor.conf
  tools/digester/vendor/modules.txt
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#1793 Add support for SNO with HPP on AWS
  hack/hpp/configure_hpp_pool.sh
Labels: size/XS, dco-signoff: yes, lgtm, approved

#1790 Manually Bump NETWORK_ADDONS to version v0.67.0
  cmd/hyperconverged-cluster-operator/main.go
  cmd/hyperconverged-cluster-webhook/main.go
  deploy/crds/cluster-network-addons00.crd.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/cluster-network-addons00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/cluster-network-addons00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  pkg/controller/commonTestUtils/testUtils.go
  pkg/webhooks/mutator/mutator_test.go
  pkg/webhooks/validator/validator_test.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/addtoscheme_networkaddonsoperator_v1.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/addtoscheme_networkaddonsoperator_v1alpha1.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/apis.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/shared/doc.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/shared/networkaddonsconfig_types.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/shared/zz_generated.deepcopy.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1/doc.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1/group_info.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1/networkaddonsconfig_types.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1/register.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1/zz_generated.deepcopy.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1alpha1/doc.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1alpha1/register.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/v1alpha1/zz_generated.defaults.go
  vendor/modules.txt
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#1792 Fix make cluster-sync
  Makefile
  hack/cri-bin.sh
Labels: size/XS, dco-signoff: yes, lgtm, approved
