Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2022-05, with the labels that each got.

#1915 Fix the unit test in Makefile
  hack/build-tests.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1919 Another try to fix unit test in CI
  hack/build-tests.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1920 Prevent upgrade if one of the operand is not upgradeable
  controllers/common/hcoConditions.go
  controllers/common/hcoRequest.go
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/networkAddons_test.go
  controllers/operands/operand.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1921 [release-1.6] Prevent upgrade if one of the operand is not upgradeable
  pkg/controller/common/hcoConditions.go
  pkg/controller/common/hcoRequest.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/networkAddons_test.go
  pkg/controller/operands/operand.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1923 csv-merger: handle skips and olm.skipRange as parameters
  tools/csv-merger/csv-merger.go
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#1922 Allow modifiying runbook URL on build time
  controllers/operands/monitoring.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1914 Add a new metric and a new alert for not completed installation
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/monitoring.go
  docs/metrics.md
  hack/build-tests.sh
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/metrics/metrics.go
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#1925 Fix new bug found by the go linter
  pkg/util/file_test.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#1932 Fix CSV retrieval command in upgrade test to get only HCO CSV
  build/Dockerfile.functest.ci
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  hack/upgrade-test-index-image.sh
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#1930 Allow modifiying the -ldflags on make builds
  Makefile
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#1911 Bump Go Dependencies to 1.18.1
  .github/workflows/build-push-images.yaml
  .github/workflows/digester_bot.yml
  .github/workflows/pr-sanity.yaml
  .github/workflows/publish-community-operators.yaml
  .github/workflows/rebase-bot.yml
  .github/workflows/release-bumper.yml
  automation/nightly/test-nightly-build.sh
  build/Dockerfile
  build/Dockerfile.functest
  build/Dockerfile.functest.ci
  build/Dockerfile.webhook
  go.mod
  go.sum
  hack/build-tests.sh
  hack/in-docker.sh
  tests/build/Dockerfile
  tests/go.mod
  tools/digester/go.mod
  tools/release-notes/go.mod
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#1937 Remove label protection when removing old metrics objects
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#1941 Limit the "Update Components Graph" github action
  .github/workflows/graphs-updater.yml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1950 full base image name in Dockerfiles
  build/Dockerfile
  build/Dockerfile.functest
  build/Dockerfile.webhook
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1944 reconcile ConsoleCLIDownload and ConsoleQuickStart
  cmd/hyperconverged-cluster-operator/main.go
  controllers/hyperconverged/hyperconverged_controller.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#1952 graph: avoid looking for NMO objects
  tools/k8s-label-visualizer/conf.json
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1954 [release-1.6] reconcile ConsoleCLIDownload and ConsoleQuickStart (#1944)
  cmd/hyperconverged-cluster-operator/main.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#1951 fix go mod for nigtly builds
  automation/nightly/test-nightly-build.sh
  hack/kubevirt-nightly-build-images.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1942 Revert NMO handling in main
  cmd/hyperconverged-cluster-operator/main.go
  controllers/commonTestUtils/testUtils.go
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/metadata/dependencies.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/metadata/dependencies.yaml
  go.mod
  go.sum
  hack/build-manifests.sh
  hack/upgrade-test-index-image.sh
  pkg/components/components.go
  pkg/util/consts.go
  vendor/github.com/medik8s/node-maintenance-operator/LICENSE
  vendor/github.com/medik8s/node-maintenance-operator/api/v1beta1/groupversion_info.go
  vendor/github.com/medik8s/node-maintenance-operator/api/v1beta1/nodemaintenance_types.go
  vendor/github.com/medik8s/node-maintenance-operator/api/v1beta1/nodemaintenance_webhook.go
  vendor/github.com/medik8s/node-maintenance-operator/api/v1beta1/zz_generated.deepcopy.go
  vendor/kubevirt.io/node-maintenance-operator/LICENSE
  vendor/kubevirt.io/node-maintenance-operator/api/v1beta1/groupversion_info.go
  vendor/kubevirt.io/node-maintenance-operator/api/v1beta1/nodemaintenance_types.go
  vendor/kubevirt.io/node-maintenance-operator/api/v1beta1/nodemaintenance_webhook.go
  vendor/kubevirt.io/node-maintenance-operator/api/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#1957 Fix release-notes tekton-tasks-operator name
  tools/release-notes/types.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1960 Add Action URL for Rebase Bot Failures
  .github/workflows/rebase-bot.yml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1891 Run unit tests with a symlink to actual upgradePatches.json
  assets/upgradePatches.json
  controllers/hyperconverged/test-files/upgradePatches/upgradePatches.json
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#1965 ConsolePlugin bugfix: Reconcile CR if labels were modified
  controllers/operands/kubevirtConsolePlugin.go
  controllers/operands/kubevirtConsolePlugin_test.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#1962 Add CPU and memory requests to console plugin deployment
  controllers/operands/kubevirtConsolePlugin.go
  controllers/operands/kubevirtConsolePlugin_test.go
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#1953 Fix alert bug
  Makefile
  cmd/hyperconverged-cluster-operator/main.go
  cmd/hyperconverged-cluster-webhook/main.go
  controllers/alerts/alerts.go
  controllers/alerts/alerts_test.go
  controllers/commonTestUtils/eventEmitterMock.go
  controllers/commonTestUtils/testUtils.go
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/hyperconverged/testUtils_test.go
  controllers/operands/monitoring.go
  controllers/operands/monitoring_test.go
  controllers/operands/operand.go
  controllers/operands/operandHandler.go
  controllers/operands/operandHandler_test.go
  hack/prom-rule-ci/rule-spec-dumper.go
  pkg/util/cluster.go
  pkg/util/consts.go
  pkg/util/event_emmiter.go
  pkg/util/event_emmiter_test.go
  pkg/util/own_resources.go
  pkg/util/own_resources_test.go
  pkg/util/util.go
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#1971 Activate the sanity test in release 1.7
  .github/workflows/pr-sanity.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1973 [release-1.6] Add a metric and Alert indicating that integrated NMO is in use and upgrade is denied
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/kubevirt-hyperconverged-operator.v1.6.0.clusterserviceversion.yaml
  docs/metrics.md
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/components/components.go
  pkg/controller/hyperconverged/hyperconverged_controller.go
  pkg/controller/hyperconverged/hyperconverged_controller_test.go
  pkg/controller/operands/monitoring.go
  pkg/metrics/metrics.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved
