Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2022-06, with the labels that each got.

#1980 [release-1.7] test: get authorization token with TokenRequest API
  tests/func-tests/monitoring_test.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#1968 Bump version to 1.8.0
  README.md
  controllers/hyperconverged/hyperconverged_controller_test.go
  deploy/index-image/Dockerfile.bundle.ci-index-image-upgrade
  deploy/index-image/bundle.Dockerfile
  deploy/index-image/community-kubevirt-hyperconverged/1.8.0/manifests/cluster-network-addons00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.8.0/manifests/containerized-data-importer00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.8.0/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.8.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.8.0/manifests/kubevirt-hyperconverged-operator.v1.8.0.clusterserviceversion.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.8.0/manifests/kubevirt00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.8.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.8.0/manifests/tekton-tasks-operator00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.8.0/metadata/annotations.yaml
  deploy/kustomize/base/subscription.yaml
  deploy/kustomize/deploy_kustomize.sh
  deploy/kustomize/image_registry/catalog_source.yaml
  deploy/olm-catalog/Dockerfile.bundle.ci-index-image-upgrade
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.8.0/manifests/cluster-network-addons00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.8.0/manifests/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.8.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.8.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.8.0/manifests/kubevirt-hyperconverged-operator.v1.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.8.0/manifests/kubevirt00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.8.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.8.0/manifests/tekton-tasks-operator00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.8.0/metadata/annotations.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/kubevirt-hyperconverged.package.yaml
  deploy/operator.yaml
  docs/functest-container.md
  tests/func-tests/monitoring_test.go
  version/version.go
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#1984 Fix bug where HCO does not reconcile PrometheusRule
  controllers/alerts/alerts.go
  controllers/alerts/alerts_test.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#1983 Build unstable index image from prev unstable index image
  .github/workflows/build-push-images.yaml
  hack/build-index-image.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1969 Remove the KubevirtHyperconvergedClusterOperatorInstallationNotCompletedAlert alert
  controllers/alerts/alerts.go
  controllers/alerts/alerts_test.go
  hack/prom-rule-ci/prom-rules-tests.yaml
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#1989 Fix StorageClass name for HPP backend in Azure SNO
  hack/hpp/configure_hpp_pool.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1993 Fix metric reading bug
  controllers/alerts/metrics_test.go
  controllers/alerts/namespace.go
  controllers/alerts/reconciler.go
  controllers/operands/namespace.go
  controllers/operands/namespace_test.go
  controllers/operands/operandHandler.go
  pkg/util/consts.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#1994 Clean old code
  controllers/operands/cdi.go
  controllers/operands/cliDownload.go
  controllers/operands/cmHandler.go
  controllers/operands/deploymentHandler.go
  controllers/operands/imageStream.go
  controllers/operands/kubevirt.go
  controllers/operands/kubevirtConsolePlugin.go
  controllers/operands/networkAddons.go
  controllers/operands/operand.go
  controllers/operands/quickStart.go
  controllers/operands/rbac.go
  controllers/operands/serviceHandler.go
  controllers/operands/ssp.go
  controllers/operands/tto.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#1995 Fix BZ-2080547: mis-read the priority class after update
  controllers/operands/kubevirt.go
  hack/check_update_priority_class.sh
  hack/run-tests.sh
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#2004 Expose a knob to let the user tune default CPU model
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.8.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.8.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2006 [release-1.6] Expose a knob to let the user tune default CPU model (#…
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.6.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.6.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  go.mod
  pkg/apis/hco/v1beta1/hyperconverged_types.go
  pkg/apis/hco/v1beta1/zz_generated.deepcopy.go
  pkg/apis/hco/v1beta1/zz_generated.openapi.go
  pkg/controller/operands/kubevirt.go
  pkg/controller/operands/kubevirt_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2008 Fix BZ 2097465: metric related resource overrides are not counted
  controllers/alerts/metrics_test.go
  controllers/alerts/reconciler.go
  controllers/hyperconverged/hyperconverged_controller.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2009 [Release-1.7] Fix BZ 2097465 - PrometheusRule modifications are not count
  controllers/alerts/alerts.go
  controllers/alerts/alerts_test.go
  controllers/hyperconverged/hyperconverged_controller.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2011 Fix panic: "nil pointer dereference"
  controllers/alerts/reconciler.go
  pkg/util/event_emmiter.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#2012 [release-1.7] Fix panic: "nil pointer dereference"
  controllers/alerts/alerts.go
  pkg/util/event_emmiter.go
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#2013 [release-1.7] Cosmetic: match main code
  pkg/util/event_emmiter.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2015 [release-1.7] Fix warning in event emitter
  pkg/util/event_emmiter.go
  pkg/util/event_emmiter_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2018 Revert infra_label for HCO alerts
  controllers/alerts/alerts.go
  hack/prom-rule-ci/prom-rules-tests.yaml
Labels: size/S, release-note-none, ok-to-test, dco-signoff: yes, lgtm, approved

#2014 Fix warning in event emitter
  pkg/util/event_emitter.go
  pkg/util/event_emitter_test.go
  pkg/util/util_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved
