Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2022-12, with the labels that each got.

#2164 Make caches for TlsSecurityProfile on HCO and APIServer independent
  cmd/hyperconverged-cluster-webhook/main.go
  pkg/webhooks/setup.go
  pkg/webhooks/validator/validator.go
  pkg/webhooks/validator/validator_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2175 [release-1.8] Fix the sanity test to run also here
  .github/workflows/pr-sanity.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2176 Fix release bumper
  .github/workflows/build-push-images.yaml
  .github/workflows/dashboard-updater.yml
  .github/workflows/digester_bot.yml
  .github/workflows/graphs-updater.yml
  .github/workflows/override-bot.yaml
  .github/workflows/pr-sanity.yaml
  .github/workflows/publish-community-operators.yaml
  .github/workflows/rebase-bot.yml
  .github/workflows/release-bumper.yml
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2180 Avoid omitempty on WorkloadUpdateMethods
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.9.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.9.0/manifests/hco00.crd.yaml
  docs/api.md
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#2182 [release-1.7] Avoid omitempty on WorkloadUpdateMethods (#2180)
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/hco00.crd.yaml
  docs/api.md
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#2181 [release-1.8] Avoid omitempty on WorkloadUpdateMethods (#2180)
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.8.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.8.0/manifests/hco00.crd.yaml
  docs/api.md
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#2183 Fix Release Bumper - matrix output
  .github/workflows/release-bumper.yml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2188 Don't publish to community operators for unstable tags
  .github/workflows/publish-community-operators.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2189 cluster-up: Fix tag updating
  cluster/kubevirtci.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2191 Fix the "when reconciling ovs-cni" unit test
  controllers/operands/networkAddons_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved
