Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2023-08, with the labels that each got.

#2453 Bump the version to 1.11.0
  README.md
  assets/upgradePatches.json
  controllers/hyperconverged/hyperconverged_controller_test.go
  deploy/index-image/Dockerfile.bundle.ci-index-image-upgrade
  deploy/index-image/bundle.Dockerfile
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/cluster-network-addons00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/containerized-data-importer00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/kubevirt-hyperconverged-operator.v1.11.0.clusterserviceversion.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/kubevirt00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/metadata/annotations.yaml
  deploy/kustomize/base/subscription.yaml
  deploy/kustomize/deploy_kustomize.sh
  deploy/kustomize/image_registry/catalog_source.yaml
  deploy/olm-catalog/Dockerfile.bundle.ci-index-image-upgrade
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/cluster-network-addons00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/kubevirt-hyperconverged-operator.v1.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/kubevirt00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/metadata/annotations.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/kubevirt-hyperconverged.package.yaml
  deploy/operator.yaml
  docs/functest-container.md
  version/version.go
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#2460 [release-1.10] Bump NETWORK_ADDONS to v0.89.0
  deploy/cluster_role.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  tests/go.mod
  tests/go.sum
  tests/vendor/modules.txt
  vendor/modules.txt
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#2462 Force runbooks names to include alerts names
  tests/func-tests/monitoring_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2461 Add Managed-Tenant-Quota (MTQ) operator to the bundle
  automation/release-bumper/release-bumper.sh
  deploy/cluster_role.yaml
  deploy/cluster_role_binding.yaml
  deploy/crds/managed-tenant-quota00.crd.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/kubevirt-hyperconverged-operator.v1.11.0.clusterserviceversion.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/managed-tenant-quota00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/kubevirt-hyperconverged-operator.v1.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/managed-tenant-quota00.crd.yaml
  deploy/operator.yaml
  deploy/service_account.yaml
  hack/build-manifests.sh
  hack/config
  pkg/components/components.go
  pkg/util/consts.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/util/consts.go
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#2465 [release-1.10] Add Managed-Tenant-Quota (MTQ) operator to the bundle
  automation/release-bumper/release-bumper.sh
  deploy/cluster_role.yaml
  deploy/cluster_role_binding.yaml
  deploy/crds/managed-tenant-quota00.crd.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/managed-tenant-quota00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/managed-tenant-quota00.crd.yaml
  deploy/operator.yaml
  deploy/service_account.yaml
  hack/build-manifests.sh
  hack/config
  pkg/components/components.go
  pkg/util/consts.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/util/consts.go
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#2463 Add support for automatic CPU limits
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  tests/func-tests/defaults_test.go
  tests/func-tests/utils.go
  tests/func-tests/validation_test.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2468 CSV-Merger: Fix wrong component name
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
  tools/util/csv_with_component.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2466 Fix runbook URL test
  tests/func-tests/monitoring_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2473 Reconcile MTQ CR according to an HCO FeatureGate
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  cmd/hyperconverged-cluster-operator/main.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/commontestutils/testUtils.go
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/kubevirt.go
  controllers/operands/kubevirtConsolePlugin.go
  controllers/operands/kubevirt_test.go
  controllers/operands/mtq.go
  controllers/operands/mtq_test.go
  controllers/operands/operandHandler.go
  deploy/cluster_role.yaml
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/kubevirt-hyperconverged-operator.v1.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/kubevirt-hyperconverged-operator.v1.11.0.clusterserviceversion.yaml
  deploy/operator.yaml
  docs/api.md
  docs/cluster-configuration.md
  go.mod
  go.sum
  hack/build-manifests.sh
  pkg/components/components.go
  pkg/util/consts.go
  tests/func-tests/defaults_test.go
  tests/func-tests/dependency_objects_test.go
  tests/func-tests/mtq_test.go
  tests/go.mod
  tests/go.sum
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.defaults.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/util/consts.go
  tests/vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/register.go
  tests/vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/doc.go
  tests/vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/register.go
  tests/vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/types.go
  tests/vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  tests/vendor/modules.txt
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
  vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/register.go
  vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/doc.go
  vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/register.go
  vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/types.go
  vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#2476 [release-1.10] Reconcile MTQ CR according to an HCO FeatureGate (#2473)
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  cmd/hyperconverged-cluster-operator/main.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/commontestutils/testUtils.go
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/kubevirt.go
  controllers/operands/kubevirtConsolePlugin.go
  controllers/operands/kubevirt_test.go
  controllers/operands/mtq.go
  controllers/operands/mtq_test.go
  controllers/operands/operandHandler.go
  deploy/cluster_role.yaml
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/operator.yaml
  docs/api.md
  docs/cluster-configuration.md
  go.mod
  go.sum
  hack/build-manifests.sh
  pkg/components/components.go
  pkg/util/consts.go
  tests/func-tests/defaults_test.go
  tests/func-tests/dependency_objects_test.go
  tests/func-tests/mtq_test.go
  tests/go.mod
  tests/go.sum
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.defaults.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/util/consts.go
  tests/vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/register.go
  tests/vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/doc.go
  tests/vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/register.go
  tests/vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/types.go
  tests/vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  tests/vendor/modules.txt
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
  vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/register.go
  vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/doc.go
  vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/register.go
  vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/types.go
  vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#2475 Fix MTQ
  controllers/operands/operandHandler.go
  tests/func-tests/mtq_test.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2478 Improve e2e test stabilization
  tests/func-tests/cluster_eviction_strategy_test.go
  tests/func-tests/golden_image_test.go
  tests/func-tests/monitoring_test.go
  tests/func-tests/node_placement_test.go
  tests/func-tests/update_priority_class_test.go
  tests/func-tests/validation_test.go
  tests/func-tests/virtual_machines_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2483 fix the MTQ links in the release bumper
  automation/release-bumper/release-bumper.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2485 [release-1.10] Manually upgrade components
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  tests/go.mod
  tests/go.sum
  tests/vendor/modules.txt
  vendor/modules.txt
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2484 Manually upgrade components
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/kubevirt-hyperconverged-operator.v1.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/kubevirt-hyperconverged-operator.v1.11.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  tests/go.mod
  tests/go.sum
  tests/vendor/modules.txt
  vendor/modules.txt
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2472 Remove prom-linter container after test
  hack/prom_metric_linter.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2480 E2E: Add the junit reporter
  hack/run-tests.sh
  tests/func-tests/cluster_eviction_strategy_test.go
  tests/func-tests/main_test.go
  tests/func-tests/monitoring_test.go
  tests/func-tests/node_placement_test.go
  tests/func-tests/utils.go
  tests/go.mod
  tests/go.sum
  tests/vendor/kubevirt.io/qe-tools/LICENSE
  tests/vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
  tests/vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go
  tests/vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
  tests/vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go
  tests/vendor/modules.txt
Labels: size/XL, release-note-none, dco-signoff: yes, lgtm, approved

#2487 Bump golangci-lint to v1.54.2
  .github/workflows/pr-sanity.yaml
  .golangci.yml
  Makefile
  tests/.golangci.yml
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2490 Dynamically configure CSV disable-operand-delete annotation
  controllers/commontestutils/testUtils.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/hyperconverged/testUtils_test.go
  controllers/operands/csv.go
  controllers/operands/csv_test.go
  controllers/operands/imageStream_test.go
  controllers/operands/operandHandler.go
  controllers/operands/operandHandler_test.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/kubevirt-hyperconverged-operator.v1.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/kubevirt-hyperconverged-operator.v1.11.0.clusterserviceversion.yaml
  pkg/components/components.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2495 Simplify the linter github action
  .github/workflows/pr-sanity.yaml
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved
