Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2023-11, with the labels that each got.

#2590 [release-1.10] Fix the golden image e2e test to use configurations (#2589)
  tests/func-tests/config.go
  tests/func-tests/golden_image_test.go
  tests/go.mod
  tests/go.sum
  tests/vendor/github.com/google/go-cmp/cmp/compare.go
  tests/vendor/github.com/google/go-cmp/cmp/export.go
  tests/vendor/github.com/google/go-cmp/cmp/export_panic.go
  tests/vendor/github.com/google/go-cmp/cmp/internal/value/pointer.go
  tests/vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  tests/vendor/github.com/google/go-cmp/cmp/options.go
  tests/vendor/github.com/google/go-cmp/cmp/path.go
  tests/vendor/github.com/google/go-cmp/cmp/report_reflect.go
  tests/vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  tests/vendor/github.com/onsi/ginkgo/v2/README.md
  tests/vendor/github.com/onsi/ginkgo/v2/core_dsl.go
  tests/vendor/github.com/onsi/ginkgo/v2/ginkgo/outline/ginkgo.go
  tests/vendor/github.com/onsi/ginkgo/v2/internal/global/init.go
  tests/vendor/github.com/onsi/ginkgo/v2/internal/group.go
  tests/vendor/github.com/onsi/ginkgo/v2/internal/node.go
  tests/vendor/github.com/onsi/ginkgo/v2/internal/suite.go
  tests/vendor/github.com/onsi/ginkgo/v2/internal/writer.go
  tests/vendor/github.com/onsi/ginkgo/v2/types/config.go
  tests/vendor/github.com/onsi/ginkgo/v2/types/errors.go
  tests/vendor/github.com/onsi/ginkgo/v2/types/types.go
  tests/vendor/github.com/onsi/ginkgo/v2/types/version.go
  tests/vendor/github.com/onsi/gomega/CHANGELOG.md
  tests/vendor/github.com/onsi/gomega/format/format.go
  tests/vendor/github.com/onsi/gomega/gomega_dsl.go
  tests/vendor/github.com/onsi/gomega/matchers.go
  tests/vendor/github.com/onsi/gomega/matchers/be_a_directory.go
  tests/vendor/github.com/onsi/gomega/matchers/be_a_regular_file.go
  tests/vendor/github.com/onsi/gomega/matchers/be_an_existing_file.go
  tests/vendor/github.com/onsi/gomega/matchers/have_http_body_matcher.go
  tests/vendor/github.com/onsi/gomega/matchers/match_error_matcher.go
  tests/vendor/golang.org/x/tools/internal/typeparams/common.go
  tests/vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  tests/vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  tests/vendor/modules.txt
Labels: size/XL, release-note-none, dco-signoff: yes, lgtm, approved

#2595 Bump dependencies in tools/release-notes
  tools/release-notes/go.mod
  tools/release-notes/go.sum
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2593 Fix the golden image test
  tests/func-tests/golden_image_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2606 [release-1.10] Refresh NETWORK_ADDONS v0.89.1
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#2603 kubevirt: Network binding plugin
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2602 Expose VirtualMachineOptions.DisableSerialConsoleLog API
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  assets/upgradePatches.json
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  tests/func-tests/defaults_test.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.defaults.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2616 Enable KubeVirt CPUManager Policy BetaOptions feature gate
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/kubevirt.go
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#2625 Renovate - disable automerge
  renovate.json
Labels: release-note-none, size/XS, ok-to-test, dco-signoff: yes, lgtm, approved

#2628 bump CDI using renovate
  renovate.json
Labels: size/S, release-note-none, dco-signoff: yes

#2629 fix renovate config
  renovate.json
Labels: release-note-none, size/XS, dco-signoff: yes

#2630 Update renovate.json
  renovate.json
Labels: do-not-merge/release-note-label-needed, size/XS, needs-ok-to-test, dco-signoff: yes, lgtm

#2631 Update renovate.json
  renovate.json
Labels: release-note-none, size/XS, ok-to-test, dco-signoff: yes, lgtm, approved

#2623 [release-1.9]feat: add .snyk file
  .snyk
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2624 [release-1.8]feat: add .snyk file
  .snyk
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2621 [main]feat: add .snyk file
  .snyk
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2638 Improve evictionStrategy docs
  docs/cluster-configuration.md
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2640 Renovate - Group GitHub Actions dependencies and disable digest pinning
  renovate.json
Labels: release-note-none, size/XS, ok-to-test, dco-signoff: yes, lgtm, approved

#2646 Update renovate.json
  renovate.json
Labels: release-note, size/XS, ok-to-test, dco-signoff: yes, lgtm, approved

#2648 Update renovate.json
  renovate.json
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#2600 Set DeployCommonInstancetypes feature gate on SSP
  controllers/operands/ssp.go
  controllers/operands/ssp_test.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved
