Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2023-02, with the labels that each got.

#2219 Consume Kubevirt v0.59.0-rc.0
  build/Dockerfile.artifacts
  deploy/cluster_role.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.9.0/manifests/kubevirt-hyperconverged-operator.v1.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.9.0/manifests/kubevirt-hyperconverged-operator.v1.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  hack/kv-smoke-tests.sh
  vendor/kubevirt.io/api/core/v1/schema.go
  vendor/kubevirt.io/api/core/v1/schema_swagger_generated.go
  vendor/kubevirt.io/api/core/v1/types.go
  vendor/modules.txt
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2228 use the ginkgo linter in CI
  .github/workflows/pr-sanity.yaml
  .golangci.yml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2204 Add HCO health metric
  api/v1beta1/hyperconverged_types.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/common/hcoConditions.go
  controllers/common/hcoConditions_test.go
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.9.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.9.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/metrics.md
  pkg/metrics/metrics.go
Labels: release-note, size/L, ok-to-test, dco-signoff: yes, lgtm, approved

#2224 Fix an issue in DataImportCron templates
  assets/dataImportCronTemplates/dataImportCronTemplates.yaml
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#2233 Bump fedora image
  deploy/Dockerfile.registry.upgrade
  deploy/Dockerfile.registry.upgrade-prev
  deploy/index-image/Dockerfile.bundle.ci-index-image-upgrade
  deploy/olm-catalog/Dockerfile.bundle.ci-index-image-upgrade
  tests/build/Dockerfile
  tools/operator-sdk-validate/Dockerfile
Labels: size/S, release-note-none, dco-signoff: yes, approved

#2230 [test] Consume fresh prometheus image
  hack/prom-rule-ci/verify-rules.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2229 Introduce a new jsonpatch annotation for SSP
  controllers/common/consts.go
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/ssp.go
  controllers/operands/ssp_test.go
  docs/cluster-configuration.md
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/webhooks/validator/validator.go
  pkg/webhooks/validator/validator_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2237 [release-1.7] Bump fedora image (#2233)
  deploy/Dockerfile.registry.upgrade
  deploy/Dockerfile.registry.upgrade-prev
  deploy/index-image/Dockerfile.bundle.ci-index-image-upgrade
  deploy/olm-catalog/Dockerfile.bundle.ci-index-image-upgrade
  tests/build/Dockerfile
  tools/operator-sdk-validate/Dockerfile
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2232 Fix kubevirt console plugin deployment name
  controllers/operands/kubevirtConsolePlugin.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#2236 [release-1.8] Bump fedora image (#2233)
  deploy/Dockerfile.registry.upgrade
  deploy/Dockerfile.registry.upgrade-prev
  deploy/index-image/Dockerfile.bundle.ci-index-image-upgrade
  deploy/olm-catalog/Dockerfile.bundle.ci-index-image-upgrade
  tests/build/Dockerfile
  tools/operator-sdk-validate/Dockerfile
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2238 [release-1.6] Bump fedora image (#2233)
  deploy/Dockerfile.registry.upgrade
  deploy/Dockerfile.registry.upgrade-prev
  deploy/index-image/Dockerfile.bundle.ci-index-image-upgrade
  deploy/olm-catalog/Dockerfile.bundle.ci-index-image-upgrade
  tests/build/Dockerfile
  tools/operator-sdk-validate/Dockerfile
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2240 [release-1.8] Introduce a new jsonpatch annotation for SSP (#2229)
  controllers/common/consts.go
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/ssp.go
  controllers/operands/ssp_test.go
  docs/cluster-configuration.md
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/webhooks/validator/validator.go
  pkg/webhooks/validator/validator_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2246 Fix upgrade bug related to the console plugin rename
  assets/upgradePatches.json
  controllers/operands/kubevirtConsolePlugin.go
  hack/check_upgrade_console_plugin.sh
  hack/upgrade-test-index-image.sh
  hack/upgrade-test.sh
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#2247 Replace `HaveLen(0)` with `BeEmpty()`
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/hyperconverged/hyperconverged_suite_test.go
  controllers/hyperconverged/upgradePatches_test.go
  controllers/operands/dashboard_test.go
  controllers/operands/imageStream_test.go
  controllers/operands/operand_test.go
  controllers/operands/quickStart_test.go
  controllers/operands/ssp_test.go
  controllers/webhooks/controller_test.go
  pkg/webhooks/mutator/virt-launcher-mutator_test.go
  pkg/webhooks/validator/validator_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2253 feat: add virtio-image flag to TTO csv manifest generator
  deploy/index-image/community-kubevirt-hyperconverged/1.9.0/manifests/kubevirt-hyperconverged-operator.v1.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.9.0/manifests/kubevirt-hyperconverged-operator.v1.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/build-manifests.sh
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#2260 Consume KV nightly
  build/Dockerfile.artifacts
  deploy/cluster_role.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.9.0/manifests/kubevirt-hyperconverged-operator.v1.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.9.0/manifests/kubevirt-hyperconverged-operator.v1.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/config
  hack/kv-smoke-tests.sh
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2254 Add `kubevirt_hyperconverged_operator_health_status` recording rule
  controllers/alerts/alerts.go
  docs/metrics.md
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/metrics/metrics.go
Labels: release-note, size/L, ok-to-test, dco-signoff: yes, lgtm, approved

#2257 Build also functest image for kubevirtci
  Makefile
  cluster/sync.sh
  tests/func-tests/dashboard_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2222 Add an alert when pod scheduling might be imbalanced across nodes duo to too much images
  cmd/hyperconverged-cluster-operator/main.go
  controllers/alerts/alerts.go
  controllers/nodeconfig/kubelet_config.go
  controllers/nodeconfig/nodeconfig_controller.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.9.0/manifests/kubevirt-hyperconverged-operator.v1.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.9.0/manifests/kubevirt-hyperconverged-operator.v1.9.0.clusterserviceversion.yaml
  docs/metrics.md
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/components/components.go
  pkg/metrics/metrics.go
  pkg/util/util.go
  tests/func-tests/monitoring_test.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/util/util.go
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#2267 Prepare for the new version of the ginkgolinter
  .github/workflows/pr-sanity.yaml
  Makefile
  controllers/operands/cdi_test.go
  controllers/operands/kubevirt_test.go
  controllers/operands/networkAddons_test.go
  controllers/operands/ssp_test.go
  controllers/operands/tto_test.go
  tests/.golangci.yml
  tests/func-tests/monitoring_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2202 dataImportCronTemplates: Add default instance type labels
  assets/dataImportCronTemplates/dataImportCronTemplates.yaml
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved
