Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2023-12, with the labels that each got.

#2650 Update renovate.json
  renovate.json
Labels: release-note, size/XS, ok-to-test, dco-signoff: yes, lgtm, approved

#2637 Add two more linters and fix findings
  .golangci.yml
  controllers/alerts/reconciler.go
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  tools/csv-merger/csv-merger.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2662 Update renovate.json
  renovate.json
Labels: size/S, release-note, ok-to-test, dco-signoff: yes, lgtm, approved

#2658 Revert "Enable KubeVirt CPUManager Policy BetaOptions feature gate (#2616)"
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/kubevirt.go
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#2660 fix: rule in .snyk file
  .snyk
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2673 Fix bug in the deploy/deploy.sh script
  cluster/sync.sh
  deploy/deploy.sh
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#2677 fix deploy/deploy.sh with the updated format of dry-run client mode
  deploy/deploy.sh
Labels: release-note-none, size/XS, ok-to-test, dco-signoff: yes, lgtm, approved

#2682 [release-1.10] Fix release index build
  hack/build-index-image.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2683 Fix release index build (#2682)
  hack/build-index-image.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2681 [doc] fix bandwidthPerMigration documentation
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2686 Tiny cleanup of go.mod
  go.mod
  vendor/modules.txt
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2688 [k8s-label-visualiz] bump client-python pip3 dep
  tools/k8s-label-visualizer/requirements.txt
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2690 Exclude rhel-9-golang from renovate's checks
  renovate.json
Labels: release-note-none, size/XS, ok-to-test, dco-signoff: yes, lgtm, approved

#2443 Makefile target for consecutive updates
  Makefile
  hack/consecutive-upgrades-test.sh
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2700 Renovate: process components
  renovate.json
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#2695 Add the AlignCPUs enabler
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  tests/func-tests/defaults_test.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.defaults.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2702 Don't trigger build-push-images workflow if renovate.json file updated
  .github/workflows/build-push-images.yaml
  .github/workflows/pr-sanity.yaml
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#2704 Fix bug where installing HCO on kubernetes+OLM, fails
  pkg/util/own_resources.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/util/own_resources.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved
