Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2023-10, with the labels that each got.

#2533 fix some gomega errors
  controllers/operands/kubevirt_test.go
  tests/func-tests/update_priority_class_test.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2434 Adds notes to Developer Workflow docs
  Makefile
  README.md
  docs/functest-container.md
  hack/build-registry-bundle.sh
  hack/upgrade-test-operator-sdk.sh
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2537 [release-1.10] Do not require nodemediatedDeviceTypes to prevent broken upgrades (#2534)
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#2535 Support ApplyOptions on upgradePatches
  assets/upgradePatches.json
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/test-files/upgradePatches/badPatches4.json
  controllers/hyperconverged/test-files/upgradePatches/badPatches5.json
  controllers/hyperconverged/test-files/upgradePatches/badPatches6.json
  controllers/hyperconverged/test-files/upgradePatches/badPatches7.json
  controllers/hyperconverged/upgradePatches.go
  controllers/hyperconverged/upgradePatches_test.go
  controllers/operands/operand.go
  go.mod
  go.sum
  tests/go.sum
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/modules.txt
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2508 kubevirt CR: GA for the free page reporting feature
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  assets/upgradePatches.json
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  tests/func-tests/defaults_test.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.defaults.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2544 Allow overriding the default golden image namespace
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/imageStream.go
  controllers/operands/imageStream_test.go
  controllers/operands/operand.go
  controllers/operands/ssp.go
  controllers/operands/ssp_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#2550 Declare supported features also with the new annotation schema
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/kubevirt-hyperconverged-operator.v1.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/kubevirt-hyperconverged-operator.v1.11.0.clusterserviceversion.yaml
  pkg/components/components.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#2557 Introduce ksmConfiguration to hco CR
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2559 Bump dependencies for CVE-2023-44487
  automation/nightly/test-nightly-build.sh
  build/Dockerfile
  build/Dockerfile.functest
  build/Dockerfile.webhook
  go.mod
  go.sum
  tests/build/Dockerfile
  tests/go.mod
  tests/vendor/modules.txt
  vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2554 Be stricter validating custom TLSSecurityProfiles
  pkg/webhooks/validator/validator.go
  pkg/webhooks/validator/validator_test.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#2543 Expose auto resource limits FG
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/kubevirt-hyperconverged-operator.v1.11.0.clusterserviceversion.yaml
  docs/api.md
  docs/cluster-configuration.md
  tests/func-tests/defaults_test.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.defaults.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2578 Simplify error handling in tests
  controllers/alerts/metrics_test.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/hyperconverged/upgradePatches_test.go
  controllers/operands/cdi_test.go
  controllers/operands/kubevirt_test.go
  controllers/operands/mtq_test.go
  controllers/operands/networkAddons_test.go
  controllers/operands/operandHandler_test.go
  controllers/operands/operand_test.go
  controllers/operands/ssp_test.go
  go.mod
  go.sum
  pkg/util/file_test.go
  pkg/webhooks/validator/validator_test.go
  tests/func-tests/golden_image_test.go
  tests/func-tests/mtq_test.go
  tests/go.mod
  tests/go.sum
  tests/vendor/github.com/google/go-cmp/cmp/compare.go
  tests/vendor/github.com/google/go-cmp/cmp/export.go
  tests/vendor/github.com/google/go-cmp/cmp/export_panic.go
  tests/vendor/github.com/google/go-cmp/cmp/internal/value/pointer.go
  tests/vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  tests/vendor/github.com/google/go-cmp/cmp/options.go
  tests/vendor/github.com/google/go-cmp/cmp/path.go
  tests/vendor/github.com/google/go-cmp/cmp/report_reflect.go
  tests/vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  tests/vendor/github.com/onsi/ginkgo/v2/core_dsl.go
  tests/vendor/github.com/onsi/ginkgo/v2/internal/global/init.go
  tests/vendor/github.com/onsi/ginkgo/v2/internal/node.go
  tests/vendor/github.com/onsi/ginkgo/v2/internal/suite.go
  tests/vendor/github.com/onsi/ginkgo/v2/types/version.go
  tests/vendor/github.com/onsi/gomega/CHANGELOG.md
  tests/vendor/github.com/onsi/gomega/gomega_dsl.go
  tests/vendor/github.com/onsi/gomega/matchers.go
  tests/vendor/github.com/onsi/gomega/matchers/match_error_matcher.go
  tests/vendor/modules.txt
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/core_dsl.go
  vendor/github.com/onsi/ginkgo/v2/internal/global/init.go
  vendor/github.com/onsi/ginkgo/v2/internal/node.go
  vendor/github.com/onsi/ginkgo/v2/internal/suite.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/github.com/onsi/gomega/matchers/match_error_matcher.go
  vendor/modules.txt
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#2582 Fix the golangci-lint configuration
  .golangci.yml
  tests/.golangci.yml
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2584 [release-1.8] Bump dependencies for CVE-2023-44487
  go.mod
  go.sum
  vendor/modules.txt
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2585 [release-1.9] Bump dependencies for CVE-2023-44487
  go.mod
  go.sum
  tests/go.mod
  tests/vendor/modules.txt
  vendor/modules.txt
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2586 [release-1.10] Bump dependencies for CVE-2023-44487
  go.mod
  go.sum
  tests/go.mod
  tests/go.sum
  tests/vendor/k8s.io/api/apidiscovery/v2beta1/generated.proto
  tests/vendor/k8s.io/api/apidiscovery/v2beta1/types.go
  tests/vendor/k8s.io/api/batch/v1/generated.proto
  tests/vendor/k8s.io/api/batch/v1/types.go
  tests/vendor/k8s.io/api/batch/v1/types_swagger_doc_generated.go
  tests/vendor/k8s.io/api/core/v1/generated.proto
  tests/vendor/k8s.io/api/core/v1/types.go
  tests/vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  tests/vendor/k8s.io/apimachinery/pkg/runtime/converter.go
  tests/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go
  tests/vendor/k8s.io/client-go/discovery/aggregated_discovery.go
  tests/vendor/k8s.io/client-go/discovery/discovery_client.go
  tests/vendor/k8s.io/client-go/openapi/client.go
  tests/vendor/k8s.io/client-go/openapi/groupversion.go
  tests/vendor/k8s.io/client-go/tools/cache/controller.go
  tests/vendor/k8s.io/client-go/tools/cache/delta_fifo.go
  tests/vendor/k8s.io/client-go/tools/cache/shared_informer.go
  tests/vendor/k8s.io/client-go/tools/record/event.go
  tests/vendor/k8s.io/client-go/util/cert/cert.go
  tests/vendor/modules.txt
  vendor/modules.txt
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#2503 Expose CDI log verbosity to HCO CR
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/cdi.go
  controllers/operands/cdi_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  deploy/kustomize/image_registry/catalog_source.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved
