Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2023-04, with the labels that each got.

#2312 [release-1.9] Revert "Add KubeVirtHyperconvergedClusterOperatorPodSchedulingMightBe…
  cmd/hyperconverged-cluster-operator/main.go
  controllers/alerts/alerts.go
  controllers/nodeconfig/kubelet_config.go
  controllers/nodeconfig/nodeconfig_controller.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.9.0/manifests/kubevirt-hyperconverged-operator.v1.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.9.0/manifests/kubevirt-hyperconverged-operator.v1.9.0.clusterserviceversion.yaml
  docs/metrics.md
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/components/components.go
  pkg/metrics/metrics.go
  pkg/util/util.go
  tests/func-tests/monitoring_test.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/util/util.go
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#2311 Revert NodeStatusMaxImagesExceeded alert
  cmd/hyperconverged-cluster-operator/main.go
  controllers/alerts/alerts.go
  controllers/nodeconfig/kubelet_config.go
  controllers/nodeconfig/nodeconfig_controller.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.9.0/manifests/kubevirt-hyperconverged-operator.v1.9.0.clusterserviceversion.yaml
  docs/metrics.md
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/components/components.go
  pkg/metrics/metrics.go
  pkg/util/util.go
  tests/func-tests/monitoring_test.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/util/util.go
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#2284 Revert "Disable PSA for upgrades with kv v0.58 on OCP/OKD (#2281)"
  hack/upgrade-test-index-image.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2314 [release-1.9] Revert "Disable PSA for upgrades with kv v0.58 on OCP/O…
  hack/upgrade-test-index-image.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2321 fix sanity test
  .github/workflows/pr-sanity.yaml
  hack/generate.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2285 Use env `RUNBOOK_URL_TEMPLATE` for the runbooks URL template
  controllers/alerts/alerts.go
  controllers/alerts/metrics_test.go
  tests/func-tests/monitoring_test.go
Labels: release-note, size/L, ok-to-test, dco-signoff: yes, lgtm, approved

#2322 dataImportCronTemplates: Move default-instancetype to n.medium
  assets/dataImportCronTemplates/dataImportCronTemplates.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2320 Expose DisableMDEVConfiguration feature gate on HCO API
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  docs/api.md
  hack/check_defaults.sh
  hack/generate.sh
  tests/func-tests/node_placement_test.go
  tests/func-tests/virtual_machines_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved
