Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2023-07, with the labels that each got.

#2412 fix wrong mkdir flag in upgrade-test-operator-sdk.sh
  hack/compare_scc.sh
  hack/upgrade-test-operator-sdk.sh
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2375 Effectively download and test arm64 virtctl binaries
  build/Dockerfile.artifacts
  tests/func-tests/cli_download_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2415 Remove root FG
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  hack/check_defaults.sh
  pkg/webhooks/mutator/hyperConvergedMutator.go
  pkg/webhooks/mutator/hyperConvergedMutator_test.go
  tests/func-tests/defaults_test.go
  tests/func-tests/nonroot_root_test.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.defaults.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2416 Fix a few examples in the doc
  docs/cluster-configuration.md
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2419 [release-1.9] fix sanity test
  .github/workflows/pr-sanity.yaml
  hack/generate.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2414 [release-1.9] Adds labels to kubevirt-console-plugin pod
  controllers/operands/deploymentHandler.go
  controllers/operands/deploymentHandler_test.go
  controllers/operands/kubevirtConsolePlugin.go
  controllers/operands/kubevirtConsolePlugin_test.go
  controllers/operands/operand.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2411 Add new label_test functional test
  hack/check_labels.sh
  hack/run-tests.sh
  hack/upgrade-test-index-image.sh
  hack/upgrade-test-operator-sdk.sh
  hack/upgrade-test.sh
  tests/func-tests/cluster_eviction_strategy_test.go
  tests/func-tests/dict_test.go
  tests/func-tests/labels_test.go
  tests/func-tests/mediateddevices_mediateddevice_test.go
  tests/func-tests/node_placement_test.go
  tests/func-tests/virtual_machines_test.go
  tests/go.mod
  tests/go.sum
  tests/vendor/github.com/gertd/go-pluralize/.gitignore
  tests/vendor/github.com/gertd/go-pluralize/.travis.yml
  tests/vendor/github.com/gertd/go-pluralize/LICENSE
  tests/vendor/github.com/gertd/go-pluralize/Makefile
  tests/vendor/github.com/gertd/go-pluralize/README.md
  tests/vendor/github.com/gertd/go-pluralize/pluralize.go
  tests/vendor/modules.txt
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#2413 [release 1.9] Propagate nodeplacement to kubevirt-console-plugin deployment
  controllers/operands/deploymentHandler.go
  controllers/operands/kubevirtConsolePlugin.go
  controllers/operands/kubevirtConsolePlugin_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2421 [func-test] simplify vmi test
  tests/func-tests/virtual_machines_test.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2356 Introduce virtualMachineOptions to hco cr
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  tests/func-tests/defaults_test.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.defaults.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2423 Add LiveMigrateIfPossible to cluster level EvictionStrategy
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#2427 Move golden image test to golang
  hack/check_golden_images.sh
  hack/run-tests.sh
  hack/upgrade-test-index-image.sh
  hack/upgrade-test-operator-sdk.sh
  tests/func-tests/config.go
  tests/func-tests/dict_test.go
  tests/func-tests/golden_image_test.go
  tests/go.mod
  tests/go.sum
  tests/vendor/github.com/openshift/api/image/docker10/doc.go
  tests/vendor/github.com/openshift/api/image/docker10/dockertypes.go
  tests/vendor/github.com/openshift/api/image/docker10/register.go
  tests/vendor/github.com/openshift/api/image/docker10/zz_generated.deepcopy.go
  tests/vendor/github.com/openshift/api/image/dockerpre012/deepcopy.go
  tests/vendor/github.com/openshift/api/image/dockerpre012/doc.go
  tests/vendor/github.com/openshift/api/image/dockerpre012/dockertypes.go
  tests/vendor/github.com/openshift/api/image/dockerpre012/register.go
  tests/vendor/github.com/openshift/api/image/dockerpre012/zz_generated.deepcopy.go
  tests/vendor/github.com/openshift/api/image/v1/consts.go
  tests/vendor/github.com/openshift/api/image/v1/doc.go
  tests/vendor/github.com/openshift/api/image/v1/generated.pb.go
  tests/vendor/github.com/openshift/api/image/v1/generated.proto
  tests/vendor/github.com/openshift/api/image/v1/legacy.go
  tests/vendor/github.com/openshift/api/image/v1/register.go
  tests/vendor/github.com/openshift/api/image/v1/types.go
  tests/vendor/github.com/openshift/api/image/v1/zz_generated.deepcopy.go
  tests/vendor/github.com/openshift/api/image/v1/zz_generated.swagger_doc_generated.go
  tests/vendor/kubevirt.io/ssp-operator/api/LICENSE
  tests/vendor/kubevirt.io/ssp-operator/api/v1beta2/groupversion_info.go
  tests/vendor/kubevirt.io/ssp-operator/api/v1beta2/ssp_types.go
  tests/vendor/kubevirt.io/ssp-operator/api/v1beta2/zz_generated.deepcopy.go
  tests/vendor/modules.txt
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#2428 [test] Force --security-context-config=restricted on upgrade
  hack/upgrade-test-operator-sdk.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2420 Expose vmiCPUAllocationRatio
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  tests/func-tests/defaults_test.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.defaults.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2430 Better error handling with ErrGroup
  controllers/commontestutils/testClient.go
  controllers/operands/operandHandler.go
  go.mod
  go.sum
  pkg/webhooks/validator/validator.go
  vendor/golang.org/x/sync/LICENSE
  vendor/golang.org/x/sync/PATENTS
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/modules.txt
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2433 silence confusing warning in the functest log
  tests/func-tests/utils.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2436 Properly consume kubevirt test binaries
  hack/kv-smoke-tests.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2431 Move the check_update_priority_class bash test to golang
  hack/check_update_priority_class.sh
  hack/run-tests.sh
  tests/func-tests/update_priority_class_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2438 [release-1.9] Fix labels for console plugin resources
  cluster/kubevirtci.sh
  controllers/hyperconverged/testUtils_test.go
  controllers/operands/kubevirtConsolePlugin.go
  controllers/operands/kubevirtConsolePlugin_test.go
  controllers/operands/operandHandler.go
  pkg/components/components.go
  pkg/util/cluster.go
  pkg/util/consts.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/util/cluster.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/util/consts.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2437 Fix cluster-wide MachineType
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#2358 Update metrics names to meet naming conventions
  controllers/alerts/alerts.go
  docs/cluster-configuration.md
  docs/metrics.md
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/metrics/metrics.go
  tools/prom-metrics-collector/metrics_collector.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#2440 feat: add deploy vm-console-proxy feature gate
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/ssp.go
  controllers/operands/ssp_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  tests/func-tests/defaults_test.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.defaults.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#2446 Consume nmap-7.94 in check_tlsprofile.sh
  hack/check_tlsprofile.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2450 Fix node placement for kubevirt-console-plugin
  controllers/operands/kubevirtConsolePlugin.go
  controllers/operands/kubevirtConsolePlugin_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2444 Rename HCO alert names
  controllers/alerts/alerts.go
  docs/cluster-configuration.md
  hack/prom-rule-ci/prom-rules-tests.yaml
  tests/func-tests/monitoring_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2452 [release-1.9] Fix node placement for kubevirt-console-plugin (#2450)
  controllers/operands/kubevirtConsolePlugin.go
  controllers/operands/kubevirtConsolePlugin_test.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved
