Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2023-06, with the labels that each got.

#2360 Fix self vendored code for tests
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/util/own_resources.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2362 Enable KubeVirt Hotplug NIC feature gate
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/kubevirt.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#2368 upgrade golangci-lint to v1.53.2
  .github/workflows/pr-sanity.yaml
  Makefile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2371 Extend ConsoleCLIDownload to contain also links for arm64 binaries
  build/Dockerfile.artifacts
  controllers/operands/cliDownload.go
  controllers/operands/cliDownload_test.go
  tests/func-tests/cli_download_test.go
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#2366 [release-1.8] Expose DisableMDEVConfiguration feature gate on HCO API…
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.8.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.8.0/manifests/hco00.crd.yaml
  docs/api.md
  hack/check_defaults.sh
  tests/func-tests/node_placement_test.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#2369 Expose SCSI persistent reservation FG
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  hack/check_defaults.sh
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.defaults.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2372 Add CR option to specify which storage class to use for VM persistent state
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2377 Enable KubeVirt VM Persistent State feature gate
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/kubevirt.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2370 Expose defaultRuntimeClass
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2365 Run locally updates
  hack/generate_local_env.py
  hack/make_local.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2327 Adds labels to kubevirt-console-plugin pod
  controllers/operands/deploymentHandler.go
  controllers/operands/deploymentHandler_test.go
  controllers/operands/kubevirtConsolePlugin.go
  controllers/operands/kubevirtConsolePlugin_test.go
  controllers/operands/operand.go
Labels: release-note, size/L, ok-to-test, dco-signoff: yes, lgtm, approved

#2376 Handle cluster level eviction strategy on SNO as a special case
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  hack/check_defaults.sh
  pkg/webhooks/mutator/hyperConvergedMutator.go
  pkg/webhooks/mutator/hyperConvergedMutator_test.go
  tests/func-tests/cluster_eviction_strategy_test.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2379 Fix `verifyOperatorHealthMetricValue()`
  tests/func-tests/monitoring_test.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2382 [release-1.9] Fix `verifyOperatorHealthMetricValue()`
  tests/func-tests/monitoring_test.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2383 Fix the check_tlsprofile.sh flaky test
  hack/check_tlsprofile.sh
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2384 Propagate nodeplacement to kubevirt-console-plugin deployment
  controllers/operands/deploymentHandler.go
  controllers/operands/kubevirtConsolePlugin.go
  controllers/operands/kubevirtConsolePlugin_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2389 Fix BZ 2215756: Failed kubevirt-plugin
  controllers/operands/kubevirtConsolePlugin.go
  controllers/operands/kubevirtConsolePlugin_test.go
  pkg/util/consts.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/util/consts.go
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#2387 Move the default values test to golang
  hack/check_defaults.sh
  hack/check_tlsprofile.sh
  hack/run-tests.sh
  tests/func-tests/defaults_test.go
  tests/func-tests/utils.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2367 [release-1.9] Expose DisableMDEVConfiguration feature gate on HCO API
  Makefile
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.9.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.9.0/manifests/hco00.crd.yaml
  docs/api.md
  hack/check_defaults.sh
  tests/func-tests/node_placement_test.go
  tests/func-tests/virtual_machines_test.go
  tests/go.sum
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.defaults.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2395 Bump NETWORK_ADDONS to v0.86.1
  deploy/cluster_role.yaml
  deploy/crds/cluster-network-addons00.crd.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/cluster-network-addons00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/cluster-network-addons00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  tests/go.mod
  tests/vendor/modules.txt
  vendor/github.com/kubevirt/cluster-network-addons-operator/pkg/apis/networkaddonsoperator/shared/networkaddonsconfig_types.go
  vendor/modules.txt
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#2398 Bump SSP to v0.18.1
  cmd/hyperconverged-cluster-operator/main.go
  cmd/hyperconverged-cluster-webhook/main.go
  controllers/commontestutils/testUtils.go
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/hyperconverged/testUtils_test.go
  controllers/operands/ssp.go
  controllers/operands/ssp_test.go
  deploy/cluster_role.yaml
  deploy/crds/scheduling-scale-performance00.crd.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  pkg/webhooks/mutator/namespace_mutator_test.go
  pkg/webhooks/validator/validator.go
  pkg/webhooks/validator/validator_test.go
  vendor/kubevirt.io/ssp-operator/api/v1beta2/groupversion_info.go
  vendor/kubevirt.io/ssp-operator/api/v1beta2/ssp_types.go
  vendor/kubevirt.io/ssp-operator/api/v1beta2/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#2399 Preparation for running functional test after upgrade
  hack/run-tests-in-container.sh
  hack/run-tests.sh
  hack/upgrade-test-index-image.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2396 move the tuningpolicy_test.sh to golang
  hack/check_tuningPolicy.sh
  hack/run-tests.sh
  tests/func-tests/tuningpolicy_test.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/controllers/common/consts.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/controllers/common/hcoConditions.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/controllers/common/hcoRequest.go
  tests/vendor/modules.txt
  tests/vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/doc.go
  tests/vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2397 dataImportCronTemplates: Move default-instancetype to u1.medium
  assets/dataImportCronTemplates/dataImportCronTemplates.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2404 [release-1.8] Expose defaultRuntimeClass
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.8.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.8.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#2403 [release-1.9] Expose defaultRuntimeClass
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.9.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.9.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2393 Expose HCO monitoring on plain k8s
  controllers/alerts/metrics_test.go
  controllers/alerts/rbac.go
  controllers/alerts/reconciler.go
  controllers/commontestutils/testUtils.go
  controllers/hyperconverged/hyperconverged_controller.go
  pkg/util/cluster.go
  pkg/util/consts.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/util/cluster.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/util/consts.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2402 Deprecate mediatedDevicesTypes in favor of mediatedDeviceTypes
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  docs/api.md
  pkg/webhooks/mutator/hyperConvergedMutator.go
  pkg/webhooks/mutator/hyperConvergedMutator_test.go
  pkg/webhooks/validator/validator.go
  pkg/webhooks/validator/validator_test.go
  tests/func-tests/mediateddevices_mediateddevice_test.go
  tests/go.mod
  tests/go.sum
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
  tests/vendor/k8s.io/apiserver/LICENSE
  tests/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/errors/doc.go
  tests/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/errors/statuserror.go
  tests/vendor/modules.txt
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#2401 Add apiserver-proxy for KubeVirt UI Plugin
  automation/release-bumper/release-bumper.sh
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/hyperconverged/testUtils_test.go
  controllers/operands/kubevirtConsolePlugin.go
  controllers/operands/kubevirtConsolePlugin_test.go
  controllers/operands/operandHandler.go
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/build-manifests.sh
  hack/config
  pkg/components/components.go
  pkg/util/cluster.go
  pkg/util/consts.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/util/cluster.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/util/consts.go
  tools/csv-merger/csv-merger.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2405 Fix link text for virtctl ARM 64 binaries
  controllers/operands/cliDownload.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2407 Update metrics_parser import
  go.mod
  go.sum
  tools/prom-metrics-collector/metrics_collector.go
  vendor/github.com/kubevirt/monitoring/pkg/metrics/parser/metrics_parser.go
  vendor/modules.txt
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved
