Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2023-09, with the labels that each got.

#2502 Bump ancillary images
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.11.0/manifests/kubevirt-hyperconverged-operator.v1.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/kubevirt-hyperconverged-operator.v1.11.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/config
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2506 [release-1.10] Bump ancillary images
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/config
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2507 [release-1.10] Bump HPP and Console Plugin
  deploy/crds/hostpath-provisioner00.crd.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/config
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#2514 Enable MTQ only at non SNO cluster
  controllers/operands/mtq.go
  controllers/operands/mtq_test.go
  pkg/webhooks/validator/validator.go
  pkg/webhooks/validator/validator_test.go
  tests/func-tests/cluster_eviction_strategy_test.go
  tests/func-tests/mtq_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2515 Fix a possible bug setting finalizers
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2522 Fix the auto-bump bot
  automation/release-bumper/release-bumper.sh
  tools/digester/main.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2531 Fix SSP validating webhook path
  deploy/webhooks.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2532 [release-1.8] fix CRModification alert in upgrade
  controllers/alerts/metrics_test.go
  controllers/alerts/reconciler.go
  controllers/hyperconverged/hyperconverged_controller.go
  hack/run-tests-in-container.sh
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved
