Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2023-05, with the labels that each got.

#2304 Consume virt images with full URL
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/build-manifests.sh
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2332 Fix dependabot alerts on the release-notes tool
  tools/release-notes/go.mod
  tools/release-notes/go.sum
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2315 Adds step to run functional test with Kubevirt CI
  docs/functest-container.md
Labels: release-note-none, size/M, ok-to-test, dco-signoff: yes, lgtm, approved

#2338 [func-tests] refactor updateHCO
  tests/func-tests/dict_test.go
  tests/func-tests/monitoring_test.go
  tests/func-tests/utils.go
  tests/go.mod
  tests/go.sum
  tests/vendor/github.com/onsi/ginkgo/v2/.gitignore
  tests/vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  tests/vendor/github.com/onsi/ginkgo/v2/ginkgo_t_dsl.go
  tests/vendor/github.com/onsi/ginkgo/v2/internal/interrupt_handler/interrupt_handler.go
  tests/vendor/github.com/onsi/ginkgo/v2/internal/output_interceptor_unix.go
  tests/vendor/github.com/onsi/ginkgo/v2/internal/suite.go
  tests/vendor/github.com/onsi/ginkgo/v2/internal/testingtproxy/testing_t_proxy.go
  tests/vendor/github.com/onsi/ginkgo/v2/internal/writer.go
  tests/vendor/github.com/onsi/ginkgo/v2/reporters/junit_report.go
  tests/vendor/github.com/onsi/ginkgo/v2/types/deprecation_support.go
  tests/vendor/github.com/onsi/ginkgo/v2/types/version.go
  tests/vendor/modules.txt
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2334 Fix gomega expressions without assertions
  controllers/operands/cliDownload_test.go
  controllers/operands/kubevirtConsolePlugin_test.go
  controllers/operands/kubevirt_test.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2335 Fix node placement test
  tests/func-tests/node_placement_test.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2341 Revert PR #2206 as it's not needed anymore
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/webhooks.yaml
  docs/cluster-configuration.md
  pkg/components/components.go
  pkg/util/consts.go
  pkg/webhooks/mutator/virt-launcher-mutator.go
  pkg/webhooks/mutator/virt-launcher-mutator_test.go
  pkg/webhooks/setup.go
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#2342 [func-tests] use and eventually block for OperatorHealthMetricValue
  tests/func-tests/monitoring_test.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2318 Add static rate limit profile `highBurst`
  api/v1beta1/hyperconverged_types.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  docs/cluster-configuration.md
  hack/check_tuningPolicy.sh
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2345 Revert "[release-1.7]: Kubevirt: Enforce limits & requests by a confi…
  api/v1beta1/hyperconverged_types.go
  controllers/operands/quickStart.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  deploy/webhooks.yaml
  docs/cluster-configuration.md
  go.mod
  hack/test_delete_ns.sh
  pkg/components/components.go
  pkg/util/consts.go
  pkg/util/file.go
  pkg/webhooks/mutator/mutator.go
  pkg/webhooks/mutator/mutator_test.go
  pkg/webhooks/mutator/utils.go
  pkg/webhooks/mutator/virt-launcher-mutator.go
  pkg/webhooks/mutator/virt-launcher-mutator_test.go
  pkg/webhooks/setup.go
  tests/func-tests/utils.go
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#2346 Revert "[release-1.8]: Kubevirt: Enforce limits & requests by a confi…
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.8.0/manifests/kubevirt-hyperconverged-operator.v1.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.8.0/manifests/kubevirt-hyperconverged-operator.v1.8.0.clusterserviceversion.yaml
  deploy/webhooks.yaml
  docs/cluster-configuration.md
  go.mod
  hack/test_delete_ns.sh
  pkg/components/components.go
  pkg/util/consts.go
  pkg/webhooks/mutator/mutator.go
  pkg/webhooks/mutator/mutator_test.go
  pkg/webhooks/mutator/utils.go
  pkg/webhooks/mutator/virt-launcher-mutator.go
  pkg/webhooks/mutator/virt-launcher-mutator_test.go
  pkg/webhooks/setup.go
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#2347 [release-1.9] Revert PR #2206 as it's not needed anymore (#2341)
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.9.0/manifests/kubevirt-hyperconverged-operator.v1.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.9.0/manifests/kubevirt-hyperconverged-operator.v1.9.0.clusterserviceversion.yaml
  deploy/webhooks.yaml
  docs/cluster-configuration.md
  pkg/components/components.go
  pkg/util/consts.go
  pkg/webhooks/mutator/virt-launcher-mutator.go
  pkg/webhooks/mutator/virt-launcher-mutator_test.go
  pkg/webhooks/setup.go
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#2071 Introduce cluster level EvictionStrategy
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.8.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  hack/check_defaults.sh
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2310 Label and unlabel nodes in functional tests
  hack/deploy.sh
  hack/deploy_only_cr.sh
  hack/np-config-hook.sh
  tests/func-tests/node_placement_test.go
  tests/func-tests/utils.go
  tests/func-tests/virtual_machines_test.go
Labels: release-note, size/L, ok-to-test, dco-signoff: yes, lgtm, approved

#2353 handle nonRoot -> root FG transition
  Makefile
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  hack/check_defaults.sh
  pkg/webhooks/mutator/hyperConvergedMutator.go
  pkg/webhooks/mutator/hyperConvergedMutator_test.go
  tests/func-tests/config.go
  tests/func-tests/nonroot_root_test.go
  tests/go.mod
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.defaults.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
  tests/vendor/k8s.io/utils/strings/slices/slices.go
  tests/vendor/modules.txt
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#2355 Fix local execution on OCP
  .gitignore
  hack/make_local.sh
  pkg/util/own_resources.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved
