Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2023-03, with the labels that each got.

#2268 Fix health metric recording rule expression
  controllers/alerts/alerts.go
  hack/prom-rule-ci/prom-rules-tests.yaml
Labels: release-note-none, size/XS, ok-to-test, dco-signoff: yes, lgtm, approved

#2271 [main] Bump Kubevirt to v0.59.0
  build/Dockerfile.artifacts
  deploy/cluster_role.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.9.0/manifests/kubevirt-hyperconverged-operator.v1.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.9.0/manifests/kubevirt-hyperconverged-operator.v1.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  hack/kv-smoke-tests.sh
  vendor/kubevirt.io/api/core/v1/types.go
  vendor/modules.txt
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2273 Workaround for nonRoot FG on Kubevirt
  api/v1beta1/hyperconverged_types.go
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#2279 Add Jira Ticket section to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2259 Add e2e-test to operator_health_status recording rule
  tests/func-tests/monitoring_test.go
Labels: size/M, release-note, ok-to-test, dco-signoff: yes, lgtm, approved

#2281 Disable PSA for upgrades with kv v0.58 on OCP/OKD
  hack/upgrade-test-index-image.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2282 Bump version to 1.10.0
  README.md
  controllers/hyperconverged/hyperconverged_controller_test.go
  deploy/index-image/Dockerfile.bundle.ci-index-image-upgrade
  deploy/index-image/bundle.Dockerfile
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/cluster-network-addons00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/containerized-data-importer00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/manifests/tekton-tasks-operator00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.10.0/metadata/annotations.yaml
  deploy/kustomize/base/subscription.yaml
  deploy/kustomize/deploy_kustomize.sh
  deploy/kustomize/image_registry/catalog_source.yaml
  deploy/olm-catalog/Dockerfile.bundle.ci-index-image-upgrade
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/cluster-network-addons00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt-hyperconverged-operator.v1.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/kubevirt00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/manifests/tekton-tasks-operator00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.10.0/metadata/annotations.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/kubevirt-hyperconverged.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#2288 [release-1.9] correctly configure sanity checks
  .github/workflows/pr-sanity.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2289 Build also FBC based unstable index images
  .github/workflows/build-push-images.yaml
  hack/build-index-image.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm

#2290 Fix FBC index build
  hack/build-index-image.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2292 Handle an unhandled error
  controllers/hyperconverged/hyperconverged_controller.go
Labels: release-note, size/XS, ok-to-test, dco-signoff: yes, lgtm, approved

#2280 [release-1.8]: Kubevirt: Enforce limits & requests by a configurable ratio
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.8.0/manifests/kubevirt-hyperconverged-operator.v1.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.8.0/manifests/kubevirt-hyperconverged-operator.v1.8.0.clusterserviceversion.yaml
  deploy/webhooks.yaml
  docs/cluster-configuration.md
  go.mod
  hack/test_delete_ns.sh
  pkg/components/components.go
  pkg/util/consts.go
  pkg/webhooks/mutator/namespace_mutator.go
  pkg/webhooks/mutator/namespace_mutator_test.go
  pkg/webhooks/mutator/utils.go
  pkg/webhooks/mutator/virt-launcher-mutator.go
  pkg/webhooks/mutator/virt-launcher-mutator_test.go
  pkg/webhooks/setup.go
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#2294 [CNV-26764] Change kubevirt-console-plugin ImagePullPolicy to IfNotPresent
  controllers/operands/kubevirtConsolePlugin.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#2225 [release-1.7]: Kubevirt: Enforce limits & requests by a configurable ratio
  api/v1beta1/hyperconverged_types.go
  controllers/operands/quickStart.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.7.0/manifests/kubevirt-hyperconverged-operator.v1.7.0.clusterserviceversion.yaml
  deploy/webhooks.yaml
  docs/cluster-configuration.md
  go.mod
  hack/test_delete_ns.sh
  pkg/components/components.go
  pkg/util/consts.go
  pkg/util/file.go
  pkg/webhooks/mutator/namespace_mutator.go
  pkg/webhooks/mutator/namespace_mutator_test.go
  pkg/webhooks/mutator/utils.go
  pkg/webhooks/mutator/virt-launcher-mutator.go
  pkg/webhooks/mutator/virt-launcher-mutator_test.go
  pkg/webhooks/setup.go
  tests/func-tests/utils.go
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#2298 [release-1.9] Bump KUBEVIRT_CONSOLE_PLUGIN to v4.13.0
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.9.0/manifests/kubevirt-hyperconverged-operator.v1.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.9.0/manifests/kubevirt-hyperconverged-operator.v1.9.0.clusterserviceversion.yaml
  hack/config
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#2297 fix CRModification alert in upgrade
  controllers/alerts/metrics_test.go
  controllers/alerts/reconciler.go
  controllers/hyperconverged/hyperconverged_controller.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2300 Use integer values for CPU requests in prom-rules-tests
  hack/prom-rule-ci/prom-rules-tests.yaml
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved
