Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2024-11, with the labels that each got.

#3156 Nightly build improvements
  automation/nightly/test-nightly-build.sh
  hack/build-index-image.sh
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3157 Fix the nightly test
  automation/nightly/test-nightly-build.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3144 Add OperatorConditionsUnhealthy alerts
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/monitoring/metrics/operator_metrics.go
  pkg/monitoring/rules/alerts/alerts.go
  pkg/monitoring/rules/alerts/health_alerts.go
  tests/func-tests/hco_prometheus_route.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3158 Fix the nightly build
  automation/nightly/test-nightly-build.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#3160 Use larger cluster for the deployment test
  automation/nightly/test-nightly-build.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3161 run functional tests in order to approve the nightly build
  automation/nightly/test-nightly-build.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#3162 Upgrade operator-observability to v0.0.24
  go.mod
  go.sum
  vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/registry.go
  vendor/modules.txt
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#3167 Fix the publish community operators bot
  .github/workflows/publish-community-operators.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3166 [Release 1.13] Fix the publish community operators bot
  .github/workflows/publish-community-operators.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3169 [release-1.12] Ensure PodDisruptionBudgetAtLimit alert is silenced
  cmd/hyperconverged-cluster-operator/main.go
  controllers/observability/observability_controller.go
  controllers/observability/pod_disruption_budget_at_limit.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.12.1/manifests/kubevirt-hyperconverged-operator.v1.12.1.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.12.1/manifests/kubevirt-hyperconverged-operator.v1.12.1.clusterserviceversion.yaml
  pkg/alertmanager/alertmanager_suite_test.go
  pkg/alertmanager/silences.go
  pkg/alertmanager/silences_test.go
  pkg/components/components.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3170 Reset kubevirt_hco_system_health_status on update
  controllers/hyperconverged/hyperconverged_controller_test.go
  pkg/monitoring/metrics/metrics_suite_test.go
  pkg/monitoring/metrics/operator_metrics.go
  pkg/monitoring/metrics/operator_metrics_test.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#3173 Fix nightly test: use operator-sdk v1.37, instead of latest
  automation/nightly/test-nightly-build.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3146 instancetypes: Remove common-instancetypes FG from KubeVirt
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/kubevirt.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3174 Add DataImportCron Source for CentOS Stream 10
  assets/dataImportCronTemplates/dataImportCronTemplates.yaml
  tests/func-tests/golden_image_test.go
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#3179 Update VMStateStorageClass docs
  docs/cluster-configuration.md
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3175 Code cleanup: remove 3 feature gates, deprecate 1
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  tests/func-tests/defaults_test.go
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#3172 Reduce number of events
  controllers/hyperconverged/hyperconverged_controller.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#3181 Fix OperatorConditionsUnhealthy alert expression metric value
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/monitoring/metrics/operator_metrics.go
  pkg/monitoring/rules/alerts/health_alerts.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#3184 Stop using the deprecated vm.spec.running field
  hack/vm.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved
