Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2024-08, with the labels that each got.

#3035 kubevirt-console-plugin: Use two replicas in case of highly available cluster
  controllers/operands/kubevirtConsolePlugin.go
  controllers/operands/kubevirtConsolePlugin_test.go
  go.mod
  go.sum
  tests/func-tests/console_plugin_test.go
  vendor/golang.org/x/mod/LICENSE
  vendor/golang.org/x/sync/LICENSE
  vendor/golang.org/x/sys/unix/mremap.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/tools/go/internal/packagesdriver/sizes.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/types/objectpath/objectpath.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/stdlib/manifest.go
  vendor/golang.org/x/tools/internal/typesinternal/types.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/modules.txt
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#3038 [Release-1.12] - fix the publish-community-operators gh action
  .github/workflows/publish-community-operators.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3040 [release 1.12] fix the publish gh action
  .github/workflows/publish-community-operators.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3042 fix the publish-community-operators gh action
  .github/workflows/publish-community-operators.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3037 Deprecate MTQ
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.openapi.go
  assets/upgradePatches.json
  automation/release-bumper/release-bumper.sh
  cmd/hyperconverged-cluster-operator/main.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/commontestutils/testUtils.go
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/mtq.go
  controllers/operands/mtq_test.go
  controllers/operands/operandHandler.go
  deploy/cluster_role.yaml
  deploy/cluster_role_binding.yaml
  deploy/crds/hco00.crd.yaml
  deploy/crds/managed-tenant-quota00.crd.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt-hyperconverged-operator.v1.13.0.clusterserviceversion.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/managed-tenant-quota00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt-hyperconverged-operator.v1.13.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/managed-tenant-quota00.crd.yaml
  deploy/operator.yaml
  deploy/service_account.yaml
  docs/api.md
  go.mod
  go.sum
  hack/build-manifests.sh
  hack/config
  pkg/components/components.go
  pkg/util/consts.go
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
  vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/register.go
  vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/doc.go
  vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/register.go
  vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/types.go
  vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#3034 Register user-defined-network (UDN) binding on kubevirt CR
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  cmd/hyperconverged-cluster-operator/main.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt-hyperconverged-operator.v1.13.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt-hyperconverged-operator.v1.13.0.clusterserviceversion.yaml
  deploy/operator.yaml
  docs/api.md
  docs/cluster-configuration.md
  hack/build-manifests.sh
  pkg/components/components.go
  pkg/util/consts.go
  pkg/util/util.go
  tests/func-tests/defaults_test.go
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3043 fix periodic-hco-push-nightly-build-main
  deploy/olm-catalog/community-kubevirt-hyperconverged/icon.svg.b64
  go.mod
  go.sum
  vendor/modules.txt
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3049 Add namespace label to UnsupportedHCOModification alerts
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/monitoring/rules/alerts/operator_alerts.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#3051 console plugin/proxy: Change AntiAffinity rule to `Preferred` instead of `Required`
  controllers/operands/kubevirtConsolePlugin.go
  controllers/operands/kubevirtConsolePlugin_test.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#3046 kubevirt-console-plugin: [release-1.12] Use two replicas in case of highly available cluster (#3035)
  controllers/operands/kubevirtConsolePlugin.go
  controllers/operands/kubevirtConsolePlugin_test.go
  tests/func-tests/console_plugin_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3052 refactor the KubeVirtCRModified alert e2e flaky test
  tests/func-tests/monitoring_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3055 node_placement e2e test: make sure all virt-hanlers are working
  tests/func-tests/node_placement_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3057 Fix the monitoring flaky functest
  tests/func-tests/labels_test.go
  tests/func-tests/main_test.go
  tests/func-tests/monitoring_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3059 Manually Bump CDI to v1.60.1
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/cdi.go
  controllers/operands/cdi_test.go
  deploy/cluster_role.yaml
  deploy/crds/containerized-data-importer00.crd.yaml
  deploy/crds/hco00.crd.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/containerized-data-importer00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt-hyperconverged-operator.v1.13.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt-hyperconverged-operator.v1.13.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/build-manifests.sh
  hack/config
  hack/kv-smoke-tests.sh
  tests/func-tests/golden_image_test.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_tlssecurityprofile.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#3061 Fix bug with ImageStreams in relatedObjects
  controllers/operands/imageStream.go
  controllers/operands/imageStream_test.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#3064 deploy: Fix script for external providers
  hack/deploy.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3063 Improve the monitoring functional test
  tests/func-tests/hco_prometheus_route.go
  tests/func-tests/main_test.go
  tests/func-tests/monitoring_test.go
  tests/func-tests/utils.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2824 Reference Kubevirt ancillary images by digest
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt-hyperconverged-operator.v1.13.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt-hyperconverged-operator.v1.13.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/build-manifests.sh
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#3066 [release-1.12] dataImportCronTemplates: Remove CentOS 7 & stream 8
  assets/dataImportCronTemplates/dataImportCronTemplates.yaml
  build/Dockerfile.okd
  ci-test-files/centos9-stream-imagestream.yaml
  ci-test-files/dataImportCronTemplatesWithImageStream.yaml
  tests/func-tests/golden_image_test.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#3068 [release-1.10] dataImportCronTemplates: Remove CentOS 7 & stream 8
  assets/dataImportCronTemplates/dataImportCronTemplates.yaml
  build/Dockerfile.okd
  ci-test-files/centos9-stream-imagestream.yaml
  ci-test-files/dataImportCronTemplatesWithImageStream.yaml
  tests/func-tests/golden_image_test.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#3071 [release-1.12] Manually Bump CDI to v1.59.1
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/cdi.go
  controllers/operands/cdi_test.go
  deploy/cluster_role.yaml
  deploy/crds/containerized-data-importer00.crd.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.12.1/manifests/containerized-data-importer00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.12.1/manifests/kubevirt-hyperconverged-operator.v1.12.1.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.12.1/manifests/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.12.1/manifests/kubevirt-hyperconverged-operator.v1.12.1.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/build-manifests.sh
  hack/config
  hack/kv-smoke-tests.sh
  tests/go.mod
  tests/vendor/modules.txt
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_tlssecurityprofile.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#3069 [release-1.9] dataImportCronTemplates: Remove CentOS 7 & stream 8
  assets/dataImportCronTemplates/dataImportCronTemplates.yaml
  build/Dockerfile.okd
  ci-test-files/centos9-stream-imagestream.yaml
  ci-test-files/dataImportCronTemplatesWithImageStream.yaml
  hack/check_golden_images.sh
  tests/func-tests/dict_test.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#3074 update the OWNERS file
  OWNERS_ALIASES
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3079 upgrade to cert-manager v1.15.3
  deploy/cert-manager.yaml
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved
