Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2024-12, with the labels that each got.

#3189 cnao, ipam-extensions: deploy IPAMController by default
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  assets/upgradePatches.json
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/networkAddons.go
  controllers/operands/networkAddons_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  hack/check_defaults.sh
  tests/func-tests/defaults_test.go
  tests/func-tests/node_placement_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3191 Enable Storage Live Migration by default
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/kubevirt.go
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#3178 Bump PROJECT to kubebuilder go/v4
  PROJECT
  automation/nightly/test-nightly-build.sh
  controllers/alerts/reconciler.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3194 Temporary set KVCI tag to 2412041602-733e595f
  automation/nightly/test-nightly-build.sh
  cluster/kubevirtci.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#3186 Don't rely on InfraStructureTopology for infra HA
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.openapi.go
  cmd/hyperconverged-cluster-operator/main.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/commontestutils/testUtils.go
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/nodes/nodes_controller.go
  controllers/nodes/nodes_controller_test.go
  controllers/nodes/nodes_suite_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.0/manifests/hco00.crd.yaml
  docs/api.md
  pkg/util/cluster.go
  pkg/util/cluster_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3195 Change default value for completionTimeoutPerGiB to 150s
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.0/manifests/hco00.crd.yaml
  docs/api.md
  tests/func-tests/defaults_test.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#3188 Fix health impact values in health status metrics
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/monitoring/rules/recordingrules/operator.go
  tests/func-tests/monitoring_test.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#3201 Restore deprecated feature gates
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  assets/upgradePatches.json
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.0/manifests/hco00.crd.yaml
  docs/api.md
  pkg/webhooks/validator/validator.go
  pkg/webhooks/validator/validator_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3197 Remove deprecated DataVolume garbage collection doc
  docs/cluster-configuration.md
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#3206 Fix the nightly test
  automation/nightly/test-nightly-build.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3204 Deprecate primaryUserDefinedNetworkBinding FG
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  assets/upgradePatches.json
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  tests/func-tests/defaults_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3138 Skip observability controller tests if no SA TLS cert
  controllers/observability/pod_disruption_budget_at_limit.go
  tests/func-tests/observability_controller_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3205 Fix issues with high availability detection
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/nodes/nodes_controller.go
  controllers/nodes/nodes_controller_test.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.0/manifests/kubevirt-hyperconverged-operator.v1.14.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.0/manifests/kubevirt-hyperconverged-operator.v1.14.0.clusterserviceversion.yaml
  docs/api.md
  pkg/components/components.go
  pkg/webhooks/mutator/hyperConvergedMutator.go
  pkg/webhooks/mutator/hyperConvergedMutator_test.go
  tests/func-tests/cluster_eviction_strategy_test.go
  tests/func-tests/node_placement_test.go
  tests/func-tests/utils.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3210 validate-bundles: remove sudo usage
  tools/operator-sdk-validate/validate-bundles.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3209 [Release 1.13] Fix issues with high availability detection
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/nodes/nodes_controller.go
  controllers/nodes/nodes_controller_test.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.13.1/manifests/kubevirt-hyperconverged-operator.v1.13.1.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.1/manifests/kubevirt-hyperconverged-operator.v1.13.1.clusterserviceversion.yaml
  docs/api.md
  pkg/components/components.go
  pkg/webhooks/mutator/hyperConvergedMutator.go
  pkg/webhooks/mutator/hyperConvergedMutator_test.go
  tests/func-tests/cluster_eviction_strategy_test.go
  tests/func-tests/node_placement_test.go
  tests/func-tests/utils.go
  tools/operator-sdk-validate/validate-bundles.sh
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3211 Bug fix: Allow setting vmiCPUAllocationRatio to 1
  api/v1beta1/hyperconverged_types.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.0/manifests/hco00.crd.yaml
  tests/func-tests/validation_test.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#3214 Add slack-bot for nightly builds
  .github/workflows/nightly-build-slack-bot.yml
  automation/hco-nightly-reporter/go.mod
  automation/hco-nightly-reporter/go.sum
  automation/hco-nightly-reporter/main.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3217 [Release-1.11]Bug fix: Allow setting vmiCPUAllocationRatio to 1
  api/v1beta1/hyperconverged_types.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.11.2/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.2/manifests/hco00.crd.yaml
  tests/func-tests/validation_test.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#3219 Handle kubevirt control plane NodePlacement on hypershift clusters
  controllers/commontestutils/testUtils.go
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  pkg/util/cluster.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#3218 [Tools] Remove deprecated flags
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3231 Minor fixes for #3219
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#3233 fix the sanity test to be applied for the new branch
  .github/workflows/pr-sanity.yaml
Labels: release-note-none, size/XS, dco-signoff: yes

#3235 [Release 1.9] Add avlitman as approver of HCO
  OWNERS_ALIASES
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3236 [Release 1.10] Add avlitman as approver of HCO
  OWNERS_ALIASES
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3237 [Release 1.11] Add avlitman as approver of HCO
  OWNERS_ALIASES
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3239 Bump own version to v1.15.0
  README.md
  deploy/index-image/Dockerfile.bundle.ci-index-image-upgrade
  deploy/index-image/bundle.Dockerfile
  deploy/index-image/community-kubevirt-hyperconverged/1.15.0/manifests/application-aware-quota00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.15.0/manifests/cluster-network-addons00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.15.0/manifests/containerized-data-importer00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.15.0/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.15.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.15.0/manifests/kubevirt-hyperconverged-operator.v1.15.0.clusterserviceversion.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.15.0/manifests/kubevirt00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.15.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.15.0/metadata/annotations.yaml
  deploy/kustomize/deploy_kustomize.sh
  deploy/olm-catalog/Dockerfile.bundle.ci-index-image-upgrade
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.0/manifests/application-aware-quota00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.0/manifests/cluster-network-addons00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.0/manifests/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.0/manifests/kubevirt-hyperconverged-operator.v1.15.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.0/manifests/kubevirt00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.0/metadata/annotations.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/index-template-release.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/index-template-unstable.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/kubevirt-hyperconverged.package.yaml
  deploy/operator.yaml
  hack/consecutive-upgrades-test.sh
  version/version.go
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#3238 [Release 1.12] remove aadmi as approver of HCO
  OWNERS_ALIASES
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3199 Fix the docgen tool
  docs/api.md
  go.mod
  tools/docgen/api.md.gotemplate
  tools/docgen/main.go
  vendor/golang.org/x/mod/internal/lazyregexp/lazyre.go
  vendor/golang.org/x/mod/modfile/print.go
  vendor/golang.org/x/mod/modfile/read.go
  vendor/golang.org/x/mod/modfile/rule.go
  vendor/golang.org/x/mod/modfile/work.go
  vendor/golang.org/x/mod/module/module.go
  vendor/golang.org/x/mod/module/pseudo.go
  vendor/modules.txt
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#3202 [release-1.12] Don't rely on InfraStructureTopology for infra HA (#3196)
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  cmd/hyperconverged-cluster-operator/main.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/commontestutils/testUtils.go
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/nodes/nodes_controller.go
  controllers/nodes/nodes_controller_test.go
  controllers/nodes/nodes_suite_test.go
  deploy/cluster_role.yaml
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.12.1/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.12.1/manifests/kubevirt-hyperconverged-operator.v1.12.1.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.12.1/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.12.1/manifests/kubevirt-hyperconverged-operator.v1.12.1.clusterserviceversion.yaml
  docs/api.md
  pkg/components/components.go
  pkg/util/cluster.go
  pkg/util/cluster_test.go
  pkg/webhooks/mutator/hyperConvergedMutator.go
  pkg/webhooks/mutator/hyperConvergedMutator_test.go
  tests/func-tests/cluster_eviction_strategy_test.go
  tests/func-tests/node_placement_test.go
  tests/func-tests/utils.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/util/cluster.go
  tools/operator-sdk-validate/validate-bundles.sh
Labels: size/XL, release-note-none, dco-signoff: yes, lgtm, approved

#3246 [release 1.12] Fix bug with user-defined labels in priorityClass
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  controllers/operands/labels.go
  controllers/operands/operand.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.12.1/manifests/kubevirt-hyperconverged-operator.v1.12.1.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.12.1/manifests/kubevirt-hyperconverged-operator.v1.12.1.clusterserviceversion.yaml
  pkg/components/components.go
  pkg/patch/patch.go
  tests/func-tests/dependency_objects_test.go
  tests/func-tests/update_priority_class_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3247 [release 1.11] Fix bug with user-defined labels in priorityClass
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  controllers/operands/labels.go
  controllers/operands/operand.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.11.2/manifests/kubevirt-hyperconverged-operator.v1.11.2.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.2/manifests/kubevirt-hyperconverged-operator.v1.11.2.clusterserviceversion.yaml
  pkg/components/components.go
  pkg/patch/patch.go
  tests/func-tests/dependency_objects_test.go
  tests/func-tests/update_priority_class_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3245 Add a workaround for a flaky test
  tests/func-tests/console_plugin_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3198 Bump golangci-lint to v1.62.2
  .github/workflows/pr-sanity.yaml
Labels: release-note-none, size/XS, dco-signoff: yes

#3242 Fix hco system health metric values
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/monitoring/metrics/operator_metrics.go
  pkg/monitoring/metrics/operator_metrics_test.go
  pkg/monitoring/rules/alerts/health_alerts.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3249 Fix smoke test on ocp-4.18
  hack/kv-smoke-tests.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3234 [Release 1.8] Add avlitman as approver of HCO
  OWNERS_ALIASES
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3208 DEV (kubevirtci): allow redploying the operator/webhook
  Makefile
  cluster/sync-pod.sh
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3250 update dependencies in the release notes tool
  tools/release-notes/git/go.mod
  tools/release-notes/git/go.sum
  tools/release-notes/go.mod
  tools/release-notes/go.sum
  tools/release-notes/release-notes.go
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved
