Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2024-05, with the labels that each got.

#2931 docs: AAQ default namespace selector
  docs/cluster-configuration.md
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#2929 [release-1.12] update the sanity test file for release 1.12
  .github/workflows/pr-sanity.yaml
  hack/bump-hco.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2927 Bump HCO to version 1.13.0
  README.md
  deploy/index-image/Dockerfile.bundle.ci-index-image-upgrade
  deploy/index-image/bundle.Dockerfile
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/application-aware-quota00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/cluster-network-addons00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/containerized-data-importer00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt-hyperconverged-operator.v1.13.0.clusterserviceversion.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/managed-tenant-quota00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/metadata/annotations.yaml
  deploy/kustomize/deploy_kustomize.sh
  deploy/olm-catalog/Dockerfile.bundle.ci-index-image-upgrade
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/application-aware-quota00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/cluster-network-addons00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt-hyperconverged-operator.v1.13.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/managed-tenant-quota00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/metadata/annotations.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/index-template-release.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/index-template-unstable.yaml
  deploy/operator.yaml
  docs/functest-container.md
  hack/bump-hco.sh
  hack/consecutive-upgrades-test.sh
  version/version.go
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#2934 Update the default hardcodedObsoleteCPUModels
  controllers/operands/kubevirt.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#2939 Add a daily schedule for the dashboard-updater gh action
  .github/workflows/dashboard-updater.yml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2940 Remove some hard coded KV FGs
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#2946 Ignore legacy MACHINETYPE when empty
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt-hyperconverged-operator.v1.13.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt-hyperconverged-operator.v1.13.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/build-manifests.sh
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2945 Remove node label from cnv_abnormal
  pkg/monitoring/rules/recordingrules/operator.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2947 [release-1.12] Ignore legacy MACHINETYPE when empty
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/index-image/community-kubevirt-hyperconverged/1.12.0/manifests/kubevirt-hyperconverged-operator.v1.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.12.0/manifests/kubevirt-hyperconverged-operator.v1.12.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/build-manifests.sh
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2956 Adding Aviv and Assaf as approvers of HCO
  OWNERS_ALIASES
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2962 Bump golang to 1.22.3
  automation/nightly/test-nightly-build.sh
  build/Dockerfile
  build/Dockerfile.functest
  build/Dockerfile.webhook
  tests/build/Dockerfile
  tools/digester/go.mod
  tools/release-notes/git/go.mod
  tools/release-notes/go.mod
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2953 Minor fixes to AAQ docs
  docs/cluster-configuration.md
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2963 Align with k8s.io/code-generator@v0.30.0
  api/v1beta1/zz_generated.openapi.go
  hack/generate.sh
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2968 [release 1.11] fix k8s-1.27 lane; hard codes the kvci version
  cluster/kubevirtci.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2967 Revert "[release-1.10] Update the default hardcodedObsoleteCPUModels"
  controllers/operands/kubevirt.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#2966 Use some new golang 1.22 new features
  controllers/hyperconverged/dataimportschedule_test.go
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/hyperconverged/testUtils_test.go
  controllers/operands/imageStream_test.go
  controllers/operands/kubevirt.go
  controllers/operands/kubevirtConsolePlugin.go
  pkg/util/cluster_test.go
  pkg/util/file.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/util/file.go
  tools/digester/main.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2965 [CNV-39949] enable nosniff for kubevirt-console-plugin nginx config
  controllers/operands/kubevirtConsolePlugin.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved
