Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2024-04, with the labels that each got.

#2844 Make `downwardMetric` feature gate opt-in
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.12.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.12.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  tests/func-tests/defaults_test.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.defaults.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#2860 Support labels in e2e tests
  hack/run-tests-in-container.sh
  hack/run-tests.sh
  tests/func-tests/cli_download_test.go
  tests/func-tests/cluster_eviction_strategy_test.go
  tests/func-tests/console_plugin_test.go
  tests/func-tests/dashboard_test.go
  tests/func-tests/golden_image_test.go
  tests/func-tests/monitoring_test.go
  tests/func-tests/mtq_test.go
  tests/func-tests/node_placement_test.go
  tests/func-tests/quickstart_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2861 Fix wrong labels in cluster_eviction_strategy_test
  tests/func-tests/cli_download_test.go
  tests/func-tests/cluster_eviction_strategy_test.go
  tests/func-tests/console_plugin_test.go
  tests/func-tests/dashboard_test.go
  tests/func-tests/golden_image_test.go
  tests/func-tests/main_test.go
  tests/func-tests/monitoring_test.go
  tests/func-tests/mtq_test.go
  tests/func-tests/node_placement_test.go
  tests/func-tests/quickstart_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2856 [operands]: Adding DaemonSet operand to deploy the swap agent
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/commontestutils/testUtils.go
  controllers/operands/operandHandler.go
  controllers/operands/wasp.go
  controllers/operands/wasp_test.go
  deploy/cluster_role.yaml
  deploy/cluster_role_binding.yaml
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.12.0/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.12.0/manifests/kubevirt-hyperconverged-operator.v1.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.12.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.12.0/manifests/kubevirt-hyperconverged-operator.v1.12.0.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/service_account.yaml
  docs/api.md
  hack/build-manifests.sh
  hack/config
  pkg/components/components.go
  pkg/util/cluster.go
  pkg/util/consts.go
  tests/func-tests/defaults_test.go
  tests/func-tests/wasp_test.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.defaults.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/util/cluster.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/util/consts.go
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#2862 Fix the monitoring e2e test
  tests/func-tests/monitoring_test.go
  tests/func-tests/wasp_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2832 feat: Switch common-instancetypes deployment to virt-operator
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/kubevirt.go
  controllers/operands/ssp.go
  controllers/operands/ssp_test.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2864 manual bump CDI to v1.59.0
  controllers/operands/cdi.go
  deploy/cluster_role.yaml
  deploy/crds/containerized-data-importer00.crd.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.12.0/manifests/containerized-data-importer00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.12.0/manifests/kubevirt-hyperconverged-operator.v1.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.12.0/manifests/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.12.0/manifests/kubevirt-hyperconverged-operator.v1.12.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  tests/func-tests/cli_download_test.go
  tests/func-tests/dashboard_test.go
  tests/func-tests/dependency_objects_test.go
  tests/func-tests/monitoring_test.go
  tests/func-tests/node_placement_test.go
  tests/func-tests/quickstart_test.go
  tests/func-tests/virtual_machines_test.go
  tests/go.mod
  tests/go.sum
  tests/vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  tests/vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  tests/vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  tests/vendor/modules.txt
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#2872 cluster-configuration.md: improved allowPostCopy
  docs/cluster-configuration.md
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2875 Drop skips from func tests
  tests/func-tests/cli_download_test.go
  tests/func-tests/cluster_eviction_strategy_test.go
  tests/func-tests/console_plugin_test.go
  tests/func-tests/dashboard_test.go
  tests/func-tests/golden_image_test.go
  tests/func-tests/main_test.go
  tests/func-tests/monitoring_test.go
  tests/func-tests/mtq_test.go
  tests/func-tests/node_placement_test.go
  tests/func-tests/quickstart_test.go
  tests/func-tests/utils.go
  tests/func-tests/wasp_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2881 ssp: Remove tekton from SSP object and documentation
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/ssp.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.12.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.12.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#2867 Bump golang.org/x/net to v0.23.0
  go.mod
  go.sum
  tests/go.mod
  tests/go.sum
  tests/vendor/golang.org/x/net/http/httpproxy/proxy.go
  tests/vendor/golang.org/x/net/http2/frame.go
  tests/vendor/golang.org/x/net/http2/pipe.go
  tests/vendor/golang.org/x/net/http2/server.go
  tests/vendor/golang.org/x/net/http2/testsync.go
  tests/vendor/golang.org/x/net/http2/transport.go
  tests/vendor/golang.org/x/sys/unix/aliases.go
  tests/vendor/golang.org/x/sys/unix/syscall_darwin_libSystem.go
  tests/vendor/golang.org/x/sys/unix/syscall_freebsd.go
  tests/vendor/golang.org/x/sys/unix/syscall_linux.go
  tests/vendor/golang.org/x/sys/unix/zsyscall_linux.go
  tests/vendor/golang.org/x/sys/unix/ztypes_linux.go
  tests/vendor/modules.txt
  tools/release-notes/go.mod
  vendor/golang.org/x/net/context/go17.go
  vendor/golang.org/x/net/context/go19.go
  vendor/golang.org/x/net/context/pre_go17.go
  vendor/golang.org/x/net/context/pre_go19.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/databuffer.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/go111.go
  vendor/golang.org/x/net/http2/go115.go
  vendor/golang.org/x/net/http2/go118.go
  vendor/golang.org/x/net/http2/not_go111.go
  vendor/golang.org/x/net/http2/not_go115.go
  vendor/golang.org/x/net/http2/not_go118.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/idna/go118.go
  vendor/golang.org/x/net/idna/idna10.0.0.go
  vendor/golang.org/x/net/idna/idna9.0.0.go
  vendor/golang.org/x/net/idna/pre_go118.go
  vendor/golang.org/x/net/idna/tables10.0.0.go
  vendor/golang.org/x/net/idna/tables11.0.0.go
  vendor/golang.org/x/net/idna/tables12.0.0.go
  vendor/golang.org/x/net/idna/tables13.0.0.go
  vendor/golang.org/x/net/idna/tables15.0.0.go
  vendor/golang.org/x/net/idna/tables9.0.0.go
  vendor/golang.org/x/net/idna/trie12.0.0.go
  vendor/golang.org/x/net/idna/trie13.0.0.go
  vendor/golang.org/x/sys/unix/aliases.go
  vendor/golang.org/x/sys/unix/syscall_darwin_libSystem.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/modules.txt
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#2891 Bump multiple components
  deploy/cluster_role.yaml
  deploy/crds/application-aware-quota00.crd.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.12.0/manifests/application-aware-quota00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.12.0/manifests/kubevirt-hyperconverged-operator.v1.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.12.0/manifests/application-aware-quota00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.12.0/manifests/kubevirt-hyperconverged-operator.v1.12.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  tests/go.mod
  tests/go.sum
  tests/vendor/github.com/golang/glog/glog.go
  tests/vendor/github.com/golang/glog/internal/logsink/logsink.go
  tests/vendor/kubevirt.io/application-aware-quota/staging/src/kubevirt.io/application-aware-quota-api/pkg/apis/core/v1alpha1/types.go
  tests/vendor/kubevirt.io/application-aware-quota/staging/src/kubevirt.io/application-aware-quota-api/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  tests/vendor/modules.txt
  vendor/kubevirt.io/application-aware-quota/staging/src/kubevirt.io/application-aware-quota-api/pkg/apis/core/v1alpha1/types.go
  vendor/kubevirt.io/application-aware-quota/staging/src/kubevirt.io/application-aware-quota-api/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#2901 [operands] remove wasp-agent operand from HCO
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/commontestutils/testUtils.go
  controllers/operands/operandHandler.go
  controllers/operands/wasp.go
  controllers/operands/wasp_test.go
  deploy/cluster_role.yaml
  deploy/cluster_role_binding.yaml
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.12.0/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.12.0/manifests/kubevirt-hyperconverged-operator.v1.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.12.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.12.0/manifests/kubevirt-hyperconverged-operator.v1.12.0.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/service_account.yaml
  docs/api.md
  hack/build-manifests.sh
  hack/config
  pkg/components/components.go
  pkg/util/cluster.go
  pkg/util/consts.go
  tests/func-tests/defaults_test.go
  tests/func-tests/wasp_test.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.deepcopy.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.defaults.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/util/cluster.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/pkg/util/consts.go
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
  tools/release-notes/go.mod
  tools/release-notes/go.sum
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#2904 Deprecate MTQ
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/mtq.go
  controllers/operands/mtq_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.12.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.12.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  docs/component.gv
  pkg/webhooks/validator/validator.go
  pkg/webhooks/validator/validator_test.go
  tests/func-tests/mtq_test.go
  tests/go.mod
  tests/go.sum
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/hyperconverged_types.go
  tests/vendor/github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1/zz_generated.openapi.go
  tests/vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/register.go
  tests/vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/doc.go
  tests/vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/register.go
  tests/vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/types.go
  tests/vendor/kubevirt.io/managed-tenant-quota/staging/src/kubevirt.io/managed-tenant-quota-api/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  tests/vendor/modules.txt
  tools/release-notes/go.mod
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#2917 [release-1.11] Destroy tektontasks CRD when upgrading from <=1.10.0
  assets/upgradePatches.json
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2916 Destroy tektontasks CRD when upgrading from <=1.10.0
  assets/upgradePatches.json
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2925 add arch specific machine types to csv-merger
  tools/csv-merger/csv-merger.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved
