Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2024-06, with the labels that each got.

#2981 [release-1.9] Add flag to csv-merger to pass the test images NVRs
  tools/csv-merger/csv-merger.go
  tools/release-notes/go.mod
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2980 [release-1.10] Add flag to csv-merger to pass the test images NVRs
  tools/csv-merger/csv-merger.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2985 [main] Bump KUBEVIRT to v1.2.2
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt-hyperconverged-operator.v1.13.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt-hyperconverged-operator.v1.13.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  tests/go.mod
  tests/go.sum
  tests/vendor/modules.txt
  vendor/modules.txt
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2846 Enable VM live update rollout strategy always
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  hack/kv-smoke-tests.sh
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#2986 [release-1.12] Enable VM live update rollout strategy always
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  hack/kv-smoke-tests.sh
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#2964 dataImportCronTemplates: Remove instancetype.kubevirt.io labels
  assets/dataImportCronTemplates/dataImportCronTemplates.yaml
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#2989 Follow up of tests/go.mod
  go.mod
  go.sum
  tests/.golangci.yml
  tests/func-tests/labels_test.go
  tests/func-tests/mediateddevices_mediateddevice_test.go
  tests/func-tests/monitoring_test.go
  tests/func-tests/tuningpolicy_test.go
  tests/func-tests/virtual_machines_test.go
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/funcr/funcr.go
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/CONTRIBUTING.md
  vendor/github.com/onsi/ginkgo/v2/Makefile
  vendor/github.com/onsi/ginkgo/v2/ginkgo/watch/package_hash.go
  vendor/github.com/onsi/ginkgo/v2/internal/suite.go
  vendor/github.com/onsi/ginkgo/v2/reporters/default_reporter.go
  vendor/github.com/onsi/ginkgo/v2/reporters/junit_report.go
  vendor/github.com/onsi/ginkgo/v2/table_dsl.go
  vendor/github.com/onsi/ginkgo/v2/types/config.go
  vendor/github.com/onsi/ginkgo/v2/types/label_filter.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/modules.txt
Labels: size/XL, release-note-none, dco-signoff: yes, lgtm, approved

#2998 Bump fedora base images to 40
  deploy/Dockerfile.registry.upgrade
  deploy/Dockerfile.registry.upgrade-prev
  deploy/index-image/Dockerfile.bundle.ci-index-image-upgrade
  deploy/olm-catalog/Dockerfile.bundle.ci-index-image-upgrade
  tools/mirror-csv-release/Dockerfile
  tools/operator-sdk-validate/Dockerfile
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#3000 [release-1.12] Bump KUBEVIRT_CONSOLE_PLUGIN to v4.16.0
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.12.0/manifests/kubevirt-hyperconverged-operator.v1.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.12.0/manifests/kubevirt-hyperconverged-operator.v1.12.0.clusterserviceversion.yaml
  hack/config
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#2952 Use ginkgo's context in e2e
  tests/func-tests/aaq_test.go
  tests/func-tests/cli_download_test.go
  tests/func-tests/cluster_eviction_strategy_test.go
  tests/func-tests/console_plugin_test.go
  tests/func-tests/dashboard_test.go
  tests/func-tests/defaults_test.go
  tests/func-tests/dependency_objects_test.go
  tests/func-tests/golden_image_test.go
  tests/func-tests/labels_test.go
  tests/func-tests/main_test.go
  tests/func-tests/mediateddevices_mediateddevice_test.go
  tests/func-tests/monitoring_test.go
  tests/func-tests/node_placement_test.go
  tests/func-tests/quickstart_test.go
  tests/func-tests/tuningpolicy_test.go
  tests/func-tests/update_priority_class_test.go
  tests/func-tests/utils.go
  tests/func-tests/validation_test.go
  tests/func-tests/virtual_machines_test.go
Labels: size/XL, release-note-none, dco-signoff: yes, lgtm, approved

#2995 Fix typo: oject -> Object
  cmd/hyperconverged-cluster-operator/main.go
Labels: release-note-none, size/XS, ok-to-test, dco-signoff: yes, lgtm, approved

#3009 Publish stable releases to the stable OLM channel
  automation/publisher/publisher.sh
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3006 CNAO, KubevirtIpamController: Support component by a feature gate
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/networkAddons.go
  controllers/operands/networkAddons_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt-hyperconverged-operator.v1.13.0.clusterserviceversion.yaml
  docs/api.md
  docs/cluster-configuration.md
  hack/check_defaults.sh
  tests/func-tests/defaults_test.go
  tests/func-tests/node_placement_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3012 Fix bug in community CSV
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt-hyperconverged-operator.v1.13.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt-hyperconverged-operator.v1.13.0.clusterserviceversion.yaml
  pkg/components/components.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3013 [Release 1.11] Fix bug in community CSV
  deploy/index-image/community-kubevirt-hyperconverged/1.11.2/manifests/kubevirt-hyperconverged-operator.v1.11.2.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.2/manifests/kubevirt-hyperconverged-operator.v1.11.2.clusterserviceversion.yaml
  pkg/components/components.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3014 [Release 1.12] Fix bug in community CSV
  deploy/index-image/community-kubevirt-hyperconverged/1.12.0/manifests/kubevirt-hyperconverged-operator.v1.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.12.0/manifests/kubevirt-hyperconverged-operator.v1.12.0.clusterserviceversion.yaml
  pkg/components/components.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved
