Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2024-09, with the labels that each got.

#3077 kubevirtci lanes: run in a pod
  automation/test.sh
  build/Dockerfile
  build/Dockerfile.artifacts
  build/Dockerfile.functest
  build/Dockerfile.webhook
  cluster/kubevirtci.sh
  deploy/webhooks.yaml
  hack/common.sh
  hack/run-tests-in-container.sh
  hack/test_delete_ns.sh
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3085 Fix a bug with user-defined labels in priorityClass
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  controllers/operands/labels.go
  controllers/operands/operand.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt-hyperconverged-operator.v1.13.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt-hyperconverged-operator.v1.13.0.clusterserviceversion.yaml
  pkg/components/components.go
  pkg/patch/patch.go
  tests/func-tests/dependency_objects_test.go
  tests/func-tests/update_priority_class_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3088 func test: Read metrics directly from HCO, instead of from Prometheus
  tests/func-tests/hco_prometheus_route.go
  tests/func-tests/monitoring_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3091 Bump HCO version to 1.14.0
  README.md
  deploy/index-image/Dockerfile.bundle.ci-index-image-upgrade
  deploy/index-image/bundle.Dockerfile
  deploy/index-image/community-kubevirt-hyperconverged/1.14.0/manifests/application-aware-quota00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.0/manifests/cluster-network-addons00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.0/manifests/containerized-data-importer00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.0/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.0/manifests/kubevirt-hyperconverged-operator.v1.14.0.clusterserviceversion.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.0/manifests/kubevirt00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.0/metadata/annotations.yaml
  deploy/kustomize/deploy_kustomize.sh
  deploy/olm-catalog/Dockerfile.bundle.ci-index-image-upgrade
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.0/manifests/application-aware-quota00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.0/manifests/cluster-network-addons00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.0/manifests/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.0/manifests/kubevirt-hyperconverged-operator.v1.14.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.0/manifests/kubevirt00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.0/metadata/annotations.yaml
  deploy/operator.yaml
  docs/functest-container.md
  version/version.go
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#3092 Bump HCO to 1.14: fix some leftovers
  deploy/olm-catalog/community-kubevirt-hyperconverged/index-template-release.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/index-template-unstable.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/kubevirt-hyperconverged.package.yaml
  hack/consecutive-upgrades-test.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#3093 [release-1.13] Revert "Bump SSP to v0.22.0-rc.0 (#3084)"
  deploy/crds/scheduling-scale-performance00.crd.yaml
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt-hyperconverged-operator.v1.13.0.clusterserviceversion.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt-hyperconverged-operator.v1.13.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/config
  vendor/kubevirt.io/ssp-operator/api/v1beta2/ssp_types.go
  vendor/kubevirt.io/ssp-operator/api/v1beta2/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3095 Bump OPM to v1.47.0
  .github/workflows/build-push-images.yaml
  hack/build-index-image.sh
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3104 unit-tests: Invoke unit tests using go test directly instead of ginkgo cli
  hack/build-tests.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3105 fix: Allow disabling of common data import crons
  controllers/operands/ssp.go
  controllers/operands/ssp_test.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#3100 raise an alert when the descheduler is not correctly configured
  Makefile
  cmd/hyperconverged-cluster-operator/main.go
  controllers/commontestutils/testUtils.go
  controllers/crd/crd_controller.go
  controllers/crd/crd_controller_test.go
  controllers/crd/crd_suite_test.go
  controllers/descheduler/descheduler_controller.go
  controllers/descheduler/descheduler_controller_test.go
  controllers/descheduler/descheduler_suite_test.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.0/manifests/kubevirt-hyperconverged-operator.v1.14.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.0/manifests/kubevirt-hyperconverged-operator.v1.14.0.clusterserviceversion.yaml
  docs/cluster-configuration.md
  docs/metrics.md
  go.mod
  go.sum
  hack/kubeDescheduler/deploy_fake_kubedescheduler.sh
  hack/kubeDescheduler/kube-descheduler-operator.crd.yaml
  hack/kubeDescheduler/kubeDescheduler.cr.yaml
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/components/components.go
  pkg/monitoring/metrics/infrastructure_metrics.go
  pkg/monitoring/rules/alerts/operator_alerts.go
  pkg/util/cluster.go
  pkg/util/cluster_test.go
  pkg/util/consts.go
  tests/func-tests/client.go
  tests/func-tests/monitoring_test.go
  vendor/github.com/openshift/cluster-kube-descheduler-operator/pkg/apis/descheduler/v1/doc.go
  vendor/github.com/openshift/cluster-kube-descheduler-operator/pkg/apis/descheduler/v1/register.go
  vendor/github.com/openshift/cluster-kube-descheduler-operator/pkg/apis/descheduler/v1/types_descheduler.go
  vendor/github.com/openshift/cluster-kube-descheduler-operator/pkg/apis/descheduler/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#3119 [Release 1.12] set kubevirtci tag to `2408151028-a0ad3359`
  cluster/kubevirtci.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3111 Fix the manual run of the bump bot, for specific branch
  .github/workflows/release-bumper.yml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved
