Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2024-07, with the labels that each got.

#3015 Use standard lib instead of self baked functions.
  controllers/hyperconverged/hyperconverged_controller.go
  pkg/util/cluster.go
  pkg/util/util.go
  pkg/util/util_test.go
  tools/csv-merger/csv-merger.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3020 Ensure PodDisruptionBudgetAtLimit alert is silenced
  cmd/hyperconverged-cluster-operator/main.go
  controllers/observability/observability_controller.go
  controllers/observability/pod_disruption_budget_at_limit.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt-hyperconverged-operator.v1.13.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.13.0/manifests/kubevirt-hyperconverged-operator.v1.13.0.clusterserviceversion.yaml
  pkg/alertmanager/alertmanager_suite_test.go
  pkg/alertmanager/silences.go
  pkg/alertmanager/silences_test.go
  pkg/components/components.go
  tests/func-tests/observability_controller_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3024 Fix runbook_url test
  tests/func-tests/monitoring_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved
