Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2025-06, with the labels that each got.

#3545 Sync hardcodedObsoleteCPUModels list
  controllers/operands/kubevirt.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#3534 Add HighNodeCPUFrequency alert
  hack/prom-rule-ci/observability-prom-rules-tests.yaml
  pkg/monitoring/observability/rules/alerts/cluster_alerts.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#3554 Fix issues with ingress-controller
  controllers/ingresscluster/ingress-cluster-controller.go
  tests/func-tests/cli_download_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3556 Fix non-stand-alone unit tests
  controllers/common/hcoConditions_test.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/aaq_test.go
  controllers/operands/cdi_test.go
  controllers/operands/dashboard.go
  controllers/operands/dashboard_test.go
  controllers/operands/imageStream_test.go
  controllers/operands/kubevirt_test.go
  controllers/operands/networkAddons_test.go
  controllers/operands/operandHandler_test.go
  controllers/operands/quickStart.go
  controllers/operands/quickStart_test.go
  controllers/operands/ssp_test.go
Labels: size/XL, release-note-none, dco-signoff: yes, lgtm, approved

#3558 Fix a bug when building a multi-ach manifest image
  hack/build-index-image.sh
  hack/build-push-multi-arch-images.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3562 Add the missing `ports` nob to the operator and the webhook pods
  controllers/operands/cliDownload.go
  deploy/index-image/community-kubevirt-hyperconverged/1.16.0/manifests/kubevirt-hyperconverged-operator.v1.16.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.16.0/manifests/kubevirt-hyperconverged-operator.v1.16.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/components/components.go
  pkg/util/consts.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#3570 Fix the publish-community-operators github action
  .github/workflows/publish-community-operators.yaml
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3572 Fix the nightly test in openshiftci
  deploy/kustomize/deploy_kustomize.sh
  tools/k8s-label-visualizer/conf.json
  tools/k8s-label-visualizer/k8s_fetcher.py
  tools/k8s-label-visualizer/requirements.txt
Labels: size/S, release-note-none, dco-signoff: yes

#3575 fix debug's leftovers in publish-community-operators.yaml
  .github/workflows/publish-community-operators.yaml
Labels: release-note-none, size/XS, dco-signoff: yes

#3583 fix the publish github action
  .github/workflows/publish-community-operators.yaml
Labels: release-note-none, size/XS, dco-signoff: yes

#3590 [release-1.15] Bump to v1.15.2
  deploy/index-image/Dockerfile.bundle.ci-index-image-upgrade
  deploy/index-image/bundle.Dockerfile
  deploy/index-image/community-kubevirt-hyperconverged/1.15.2/manifests/application-aware-quota00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.15.2/manifests/cluster-network-addons00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.15.2/manifests/containerized-data-importer00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.15.2/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.15.2/manifests/hostpath-provisioner00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.15.2/manifests/kubevirt-hyperconverged-operator.v1.15.2.clusterserviceversion.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.15.2/manifests/kubevirt00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.15.2/manifests/scheduling-scale-performance00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.15.2/metadata/annotations.yaml
  deploy/olm-catalog/Dockerfile.bundle.ci-index-image-upgrade
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.2/manifests/application-aware-quota00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.2/manifests/cluster-network-addons00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.2/manifests/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.2/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.2/manifests/hostpath-provisioner00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.2/manifests/kubevirt-hyperconverged-operator.v1.15.2.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.2/manifests/kubevirt00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.2/manifests/scheduling-scale-performance00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.2/metadata/annotations.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/index-template-release.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/index-template-unstable.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL, release-note, dco-signoff: yes

#3595 Bump golang base images to v1.24
  build/Dockerfile
  build/Dockerfile.functest
  build/Dockerfile.functest.ci
  build/Dockerfile.webhook
  tests/build/Dockerfile
Labels: size/S, release-note-none, dco-signoff: yes

#3585 Bump golang to v1.24
  Makefile
  automation/hco-nightly-reporter/go.mod
  automation/nightly/test-nightly-build.sh
  go.mod
  hack/build-tests.sh
  tools/annotate-dicts/go.mod
  tools/digester/go.mod
  tools/release-notes/go.mod
Labels: size/S, release-note, dco-signoff: yes
