Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2025-08, with the labels that each got.

#3675 document the DICT on heterogeneous cluster
  docs/cluster-configuration.md
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3680 Adding ClusterRole and ClusterRoleBinding handlers
  controllers/operands/rbac.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.16.0/manifests/kubevirt-hyperconverged-operator.v1.16.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.16.0/manifests/kubevirt-hyperconverged-operator.v1.16.0.clusterserviceversion.yaml
  pkg/components/components.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3681 [Chore] several refactoring's
  controllers/handlers/golden-images/golden_images.go
  controllers/handlers/golden-images/golden_images_test.go
  controllers/handlers/golden-images/testFiles/dataImportCronTemplates/dataImportCronTemplates.yaml
  controllers/handlers/golden-images/testFiles/dataImportCronTemplates/dataImportCronTemplatesNoAnnotation.yaml
  controllers/handlers/golden-images/testFiles/dataImportCronTemplates/dataImportCronTemplatesWithImageStream.yaml
  controllers/handlers/golden-images/testFiles/dataImportCronTemplates/wrongDataImportCronTemplates.yaml
  controllers/handlers/kubevirtConsolePlugin.go
  controllers/handlers/passt/passt.go
  controllers/handlers/quickStart.go
  controllers/handlers/ssp.go
  controllers/handlers/ssp_test.go
  controllers/operands/cmHandler.go
  controllers/operands/deploymentHandler.go
  controllers/operands/node_placement.go
  controllers/operands/rbac.go
  pkg/webhooks/mutator/hyperConvergedMutator.go
  pkg/webhooks/mutator/hyperConvergedMutator_test.go
  tests/func-tests/golden_image_test.go
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#3684 Add new metric when DICT is w/o supported architecture
  controllers/handlers/golden-images/golden_images.go
  controllers/handlers/golden-images/golden_images_test.go
  controllers/handlers/ssp.go
  controllers/handlers/ssp_test.go
  docs/metrics.md
  pkg/monitoring/hyperconverged/metrics/operator_metrics.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3686 Add network policies for the UI pods
  controllers/alerts/metrics_test.go
  controllers/alerts/reconciler.go
  controllers/common/network_policy.go
  controllers/commontestutils/testUtils.go
  controllers/handlers/kubevirtConsolePlugin.go
  controllers/handlers/kubevirtConsolePlugin_test.go
  controllers/operandhandler/operandHandler.go
  controllers/operands/network_policy.go
  pkg/components/components.go
  pkg/util/consts.go
  pkg/webhooks/setup_test.go
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#3682 Deploy wasp-agent using HCO
  cmd/hyperconverged-cluster-operator/main.go
  controllers/handlers/wasp-agent/daemonset.go
  controllers/handlers/wasp-agent/daemonset_test.go
  controllers/handlers/wasp-agent/rbac.go
  controllers/handlers/wasp-agent/rbac_test.go
  controllers/handlers/wasp-agent/scc.go
  controllers/handlers/wasp-agent/scc_test.go
  controllers/handlers/wasp-agent/service_account.go
  controllers/handlers/wasp-agent/service_account_test.go
  controllers/handlers/wasp-agent/wasp_agent_suite_test.go
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/operandhandler/operandHandler.go
  controllers/operands/rbac.go
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.16.0/manifests/kubevirt-hyperconverged-operator.v1.16.0.clusterserviceversion.yaml
  tests/func-tests/wasp_agent_test.go
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#3696 [1.14] Fix monitoring linter
  Makefile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3699 Always deploy Network Policies for operands
  controllers/alerts/metrics_test.go
  controllers/alerts/network_policy.go
  controllers/alerts/reconciler.go
  controllers/handlers/kubevirtConsolePlugin.go
  controllers/handlers/kubevirtConsolePlugin_test.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operandhandler/operandHandler.go
  tests/func-tests/console_plugin_test.go
  tools/csv-merger/network-policies-template.tmpl
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3701 [release-1.14] Force recreate metrics endpoint secret
  controllers/alerts/reconciler.go
  controllers/alerts/secret.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.1/manifests/kubevirt-hyperconverged-operator.v1.14.1.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.1/manifests/kubevirt-hyperconverged-operator.v1.14.1.clusterserviceversion.yaml
  pkg/components/components.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3706 Remove RWX filesystem mode requirement from vmStateStorageClass
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.16.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.16.0/manifests/hco00.crd.yaml
  docs/api.md
  tools/csv-merger/generated-crd.yaml
  tools/manifest-templator/generated-crd.yaml
Labels: size/M, release-note, ok-to-test, dco-signoff: yes, lgtm, approved

#3707 Sanity test: Ignore Coverall Failures
  .github/workflows/pr-sanity.yaml
Labels: release-note-none, size/XS, dco-signoff: yes

#3705 [wasp-agent] Add relevant alert and metric to detect duplicate wasp-agent deployment
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.0/manifests/kubevirt00.crd.yaml
  docs/metrics.md
  hack/prom-rule-ci/observability-prom-rules-tests.yaml
  pkg/monitoring/hyperconverged/metrics/operator_metrics.go
  pkg/monitoring/observability/rules/alerts/alerts.go
  pkg/monitoring/observability/rules/alerts/cluster_alerts.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3716 Use github.com/rhobs/operator-observability-toolkit
  cmd/hyperconverged-cluster-operator/main.go
  go.mod
  go.sum
  pkg/monitoring/hyperconverged/metrics/infrastructure_metrics.go
  pkg/monitoring/hyperconverged/metrics/metrics.go
  pkg/monitoring/hyperconverged/metrics/operator_metrics.go
  pkg/monitoring/hyperconverged/rules/alerts/alerts.go
  pkg/monitoring/hyperconverged/rules/recordingrules/operator.go
  pkg/monitoring/hyperconverged/rules/recordingrules/recordingrules.go
  pkg/monitoring/hyperconverged/rules/rules.go
  pkg/monitoring/hyperconverged/rules/rules_test.go
  pkg/monitoring/observability/rules/alerts/alerts.go
  pkg/monitoring/observability/rules/rules.go
  pkg/monitoring/observability/rules/rules_test.go
  tools/metricsdocs/metricsdocs.go
  vendor/github.com/rhobs/operator-observability-toolkit/LICENSE
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/docs/alerts.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/docs/metrics.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/operatormetrics/collector.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/operatormetrics/collector_result.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/operatormetrics/counter.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/operatormetrics/counter_vec.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/operatormetrics/gauge.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/operatormetrics/gauge_vec.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/operatormetrics/histogram.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/operatormetrics/histogram_vec.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/operatormetrics/metric.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/operatormetrics/registry.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/operatormetrics/summary.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/operatormetrics/summary_vec.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/operatormetrics/wrapper_registry.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/operatorrules/compatibility.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/operatorrules/prometheusrules.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/operatorrules/rbac.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/operatorrules/recordingrule.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/operatorrules/registry.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/operatorrules/schema.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/testutil/alert_custom_validations.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/testutil/alert_validation.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/testutil/fetch_metrics.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/testutil/linter.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/testutil/problem.go
  vendor/github.com/rhobs/operator-observability-toolkit/pkg/testutil/recording_rule_validation.go
  vendor/modules.txt
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3718 fix flaky test
  tests/func-tests/golden_image_test.go
Labels: size/S, release-note-none, dco-signoff: yes

#3723 Fix flaky test
  tests/func-tests/debugFuncs_test.go
  tests/func-tests/golden_image_test.go
Labels: release-note-none, size/L, dco-signoff: yes

#3728 enabled revive bare-return rule and fix findings
  .golangci.yml
  pkg/util/own_resources.go
Labels: size/S, release-note-none, ok-to-test, dco-signoff: yes, lgtm, approved

#3722 New alert: `HCOMultiArchGoldenImagesDisabled`
  api/v1beta1/register.go
  cmd/hyperconverged-cluster-operator/main.go
  deploy/index-image/community-kubevirt-hyperconverged/1.16.0/manifests/kubevirt-hyperconverged-operator.v1.16.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.16.0/manifests/kubevirt-hyperconverged-operator.v1.16.0.clusterserviceversion.yaml
  hack/prom-rule-ci/hyperconverged-prom-rules-tests.yaml
  pkg/components/components.go
  pkg/monitoring/hyperconverged/collectors/collectors_test.go
  pkg/monitoring/hyperconverged/collectors/controllers.go
  pkg/monitoring/hyperconverged/collectors/operator_collectors.go
  pkg/monitoring/hyperconverged/collectors/operator_collectors_test.go
  pkg/monitoring/hyperconverged/rules/alerts/operator_alerts.go
  pkg/util/consts.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3729 Fix logging when the HC CR is not found
  pkg/monitoring/hyperconverged/collectors/operator_collectors.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#3358 cluster-alerts: Add alert rule DeprecatedMachineType
  hack/prom-rule-ci/observability-prom-rules-tests.yaml
  pkg/monitoring/observability/rules/alerts/cluster_alerts.go
  tests/func-tests/monitoring_test.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#3730 Improve the performance of the HyperConverged CR deletion + some chores
  .github/workflows/pr-sanity.yaml
  Makefile
  controllers/handlers/aaq.go
  controllers/handlers/cdi.go
  controllers/handlers/cliDownload.go
  controllers/handlers/imageStream.go
  controllers/handlers/kubevirt.go
  controllers/handlers/kubevirtConsolePlugin.go
  controllers/handlers/networkAddons.go
  controllers/handlers/passt/passt.go
  controllers/handlers/quickStart.go
  controllers/handlers/ssp.go
  controllers/handlers/ssp_test.go
  controllers/handlers/wasp-agent/scc.go
  controllers/operandhandler/operandHandler.go
  controllers/operands/cmHandler.go
  controllers/operands/daemonSetHandler.go
  controllers/operands/deploymentHandler.go
  controllers/operands/generic_operand.go
  controllers/operands/networkAttachmentDefinitionHandler.go
  controllers/operands/network_policy.go
  controllers/operands/operand.go
  controllers/operands/rbac.go
  controllers/operands/securityContextConstraintsHandler.go
  controllers/operands/serviceAccountHandler.go
  controllers/operands/serviceHandler.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved
