Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2025-04, with the labels that each got.

#3355 Bump golangci-lint to v2.0.0 and fix new findings
  .github/workflows/pr-sanity.yaml
  .golangci.yml
  Makefile
  controllers/commontestutils/testUtils.go
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/ingresscluster/ingress-cluster-controller.go
  controllers/nodes/nodes_controller.go
  controllers/operands/cdi.go
  controllers/operands/cliDownload.go
  controllers/operands/deploymentHandler_test.go
  controllers/operands/imageStream.go
  controllers/operands/kubevirt.go
  controllers/operands/kubevirtConsolePlugin_test.go
  controllers/operands/networkAddons.go
  controllers/operands/ssp.go
  controllers/operands/ssp_test.go
  pkg/components/components.go
  pkg/util/cluster.go
  pkg/util/own_resources.go
  pkg/webhooks/mutator/hyperConvergedMutator_test.go
  pkg/webhooks/validator/validator.go
  pkg/webhooks/validator/validator_test.go
  tests/func-tests/hco_prometheus_route.go
  tests/func-tests/utils.go
  tools/crwriter/crwriter.go
  tools/csv-merger/csv-merger.go
  tools/docgen/main.go
  tools/manifest-templator/manifest-templator.go
  tools/util/marshaller.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3372 Move the `deployKubeSecondaryDNS` feature gate to new field
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  assets/upgradePatches.json
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/networkAddons.go
  controllers/operands/networkAddons_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.15.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  pkg/upgradepatch/hc.cr.json
  pkg/webhooks/validator/validator.go
  pkg/webhooks/validator/validator_test.go
  tests/func-tests/defaults_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3376 E2E: extand monitoring test timeout
  tests/func-tests/monitoring_test.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#3381 makefile: fix container-push-artifacts-server target
  Makefile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3379 Fix a bug when setting a CPU quantity without a type
  controllers/operands/aaq.go
  controllers/operands/aaq_test.go
  controllers/operands/cdi.go
  controllers/operands/cdi_test.go
  controllers/operands/deploymentHandler.go
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  controllers/operands/networkAddons.go
  controllers/operands/ssp.go
  pkg/reformatobj/reformatobj.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3383 Use the official coveralls github action
  .github/workflows/pr-sanity.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3387 Re-activate the renovate bot
  renovate.json
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3468 make renovate to run only for main branch, for now
  renovate.json
Labels: do-not-merge/release-note-label-needed, dco-signoff: yes

#3390 Add missing mutex lock for aaq.reset()
  controllers/operands/aaq.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3391 Move the enableApplicationAwareQuota feature gate to new field
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  assets/upgradePatches.json
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/aaq.go
  controllers/operands/aaq_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.15.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  pkg/upgradepatch/hc.cr.json
  pkg/webhooks/validator/validator.go
  pkg/webhooks/validator/validator_test.go
  tests/func-tests/aaq_test.go
  tests/func-tests/defaults_test.go
Labels: release-note, size/L, ok-to-test, dco-signoff: yes, lgtm, approved

#3386 Set terminationMessagePolicy=FallbackToLogsOnError
  controllers/operands/kubevirtConsolePlugin.go
  deploy/index-image/community-kubevirt-hyperconverged/1.15.0/manifests/kubevirt-hyperconverged-operator.v1.15.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.0/manifests/kubevirt-hyperconverged-operator.v1.15.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/run-tests-in-container.sh
  pkg/components/components.go
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#3475 [release-1.14] fix(api): Introduce CommonInstancetypesDeployment
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.1/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.1/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3477 Revert: default Eviction Strategy to None on ARM64 clusters
  pkg/webhooks/mutator/hyperConvergedMutator.go
  pkg/webhooks/mutator/hyperConvergedMutator_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3481 Bump own version to v1.16.0
  README.md
  deploy/index-image/Dockerfile.bundle.ci-index-image-upgrade
  deploy/index-image/bundle.Dockerfile
  deploy/index-image/community-kubevirt-hyperconverged/1.16.0/manifests/application-aware-quota00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.16.0/manifests/cluster-network-addons00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.16.0/manifests/containerized-data-importer00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.16.0/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.16.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.16.0/manifests/kubevirt-hyperconverged-operator.v1.16.0.clusterserviceversion.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.16.0/manifests/kubevirt00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.16.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.16.0/metadata/annotations.yaml
  deploy/kustomize/deploy_kustomize.sh
  deploy/olm-catalog/Dockerfile.bundle.ci-index-image-upgrade
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.16.0/manifests/application-aware-quota00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.16.0/manifests/cluster-network-addons00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.16.0/manifests/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.16.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.16.0/manifests/hostpath-provisioner00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.16.0/manifests/kubevirt-hyperconverged-operator.v1.16.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.16.0/manifests/kubevirt00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.16.0/manifests/scheduling-scale-performance00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.16.0/metadata/annotations.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/index-template-release.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/index-template-unstable.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/kubevirt-hyperconverged.package.yaml
  deploy/operator.yaml
  hack/consecutive-upgrades-test.sh
  version/version.go
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#3482 Reduce NodeNetworkInterfaceDown chance for false positives
  hack/prom-rule-ci/observability-prom-rules-tests.yaml
  pkg/monitoring/observability/rules/alerts/cluster_alerts.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3476 Check descheduler according to new profile
  .golangci.yml
  controllers/commontestutils/testUtils.go
  controllers/descheduler/descheduler_controller.go
  controllers/descheduler/descheduler_controller_test.go
  go.mod
  go.sum
  hack/kubeDescheduler/kube-descheduler-operator.crd.yaml
  hack/kubeDescheduler/kubeDescheduler.cr.yaml
  pkg/monitoring/hyperconverged/metrics/infrastructure_metrics.go
  pkg/util/cluster.go
  pkg/util/cluster_test.go
  pkg/util/operatorcondition_test.go
  pkg/util/util_suite_test.go
  tests/func-tests/monitoring_test.go
  vendor/github.com/openshift/cluster-kube-descheduler-operator/LICENSE
  vendor/github.com/openshift/cluster-kube-descheduler-operator/pkg/apis/descheduler/v1/types_descheduler.go
  vendor/github.com/openshift/cluster-kube-descheduler-operator/pkg/apis/descheduler/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/cluster-kube-descheduler-operator/pkg/apis/descheduler/v1/zz_generated.defaults.go
  vendor/modules.txt
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#3385 [release-1.14] Add observability controller alerts
  Makefile
  cmd/hyperconverged-cluster-operator/main.go
  controllers/alerts/alerts.go
  controllers/alerts/metrics_test.go
  controllers/alerts/reconciler.go
  controllers/descheduler/descheduler_controller.go
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/observability/alerts.go
  controllers/observability/alerts_test.go
  controllers/observability/observability_controller.go
  controllers/observability/observability_controller_test.go
  controllers/observability/observability_suite_test.go
  controllers/observability/pod_disruption_budget_at_limit.go
  controllers/operands/operandHandler.go
  hack/prom-rule-ci/hyperconverged-prom-rules-tests.yaml
  hack/prom-rule-ci/observability-prom-rules-tests.yaml
  hack/prom-rule-ci/rule-spec-dumper.go
  hack/prom-rule-ci/verify-rules.sh
  pkg/monitoring/hyperconverged/metrics/infrastructure_metrics.go
  pkg/monitoring/hyperconverged/metrics/metrics.go
  pkg/monitoring/hyperconverged/metrics/metrics_suite_test.go
  pkg/monitoring/hyperconverged/metrics/operator_metrics.go
  pkg/monitoring/hyperconverged/metrics/operator_metrics_test.go
  pkg/monitoring/hyperconverged/rules/alerts/alerts.go
  pkg/monitoring/hyperconverged/rules/alerts/health_alerts.go
  pkg/monitoring/hyperconverged/rules/alerts/operator_alerts.go
  pkg/monitoring/hyperconverged/rules/recordingrules/operator.go
  pkg/monitoring/hyperconverged/rules/recordingrules/recordingrules.go
  pkg/monitoring/hyperconverged/rules/rules.go
  pkg/monitoring/hyperconverged/rules/rules_test.go
  pkg/monitoring/observability/rules/alerts/alerts.go
  pkg/monitoring/observability/rules/alerts/cluster_alerts.go
  pkg/monitoring/observability/rules/rules.go
  pkg/monitoring/observability/rules/rules_test.go
  pkg/util/cluster.go
  tests/func-tests/monitoring_test.go
  tests/func-tests/observability_controller_test.go
  tools/metricsdocs/metricsdocs.go
  tools/prom-metrics-collector/metrics_json_generator.go
Labels: size/XL, release-note-none, dco-signoff: yes, lgtm, approved, needs-approver-review

#3490 Bump kubevirtci dependencies
  Makefile
  automation/nightly/test-nightly-build.sh
  cluster/kubevirtci.sh
  hack/bump-kubevirtci.sh
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3492 [Release 1.15] Revert moving deployKubeSecondaryDNS FG to a regular field
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  assets/upgradePatches.json
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/networkAddons.go
  controllers/operands/networkAddons_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.15.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  pkg/upgradepatch/hc.cr.json
  pkg/webhooks/validator/validator.go
  pkg/webhooks/validator/validator_test.go
  tests/func-tests/defaults_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3491 Revert moving deployKubeSecondaryDNS FG to a regular field
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  assets/upgradePatches.json
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/networkAddons.go
  controllers/operands/networkAddons_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.16.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.16.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  pkg/upgradepatch/hc.cr.json
  pkg/webhooks/validator/validator.go
  pkg/webhooks/validator/validator_test.go
  tests/func-tests/defaults_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3494 CNV-59923: Fix Console Plugin access in case of single stack IPv6
  controllers/operands/kubevirtConsolePlugin.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3500 Add retry for multi-arch image pushes
  hack/build-push-multi-arch-images.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#3501 Retry push images on the retag script
  hack/architecture.sh
  hack/build-index-image.sh
  hack/build-push-multi-arch-images.sh
  hack/retag-multi-arch-images.sh
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved
