Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2025-09, with the labels that each got.

#3739 Fix bug in bearer tokens
  controllers/alerts/reconciler.go
  controllers/alerts/secret.go
  controllers/webhooks/bearer-token-controller/controller_test.go
  controllers/webhooks/bearer-token-controller/secret.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3749 [1.14] NodeNetworkInterfaceDown alert fires for disabled NICs
  hack/prom-rule-ci/observability-prom-rules-tests.yaml
  pkg/monitoring/observability/rules/alerts/cluster_alerts.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3744 Add declarativeHotplugVolumes feature gate
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/handlers/kubevirt.go
  controllers/handlers/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.17.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.17.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  pkg/upgradepatch/hc.cr.json
  tests/func-tests/defaults_test.go
  tools/csv-merger/generated-crd.yaml
  tools/manifest-templator/generated-crd.yaml
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3753 Fix wrong label in the kubevirt-apiserver-proxy-np network policy
  controllers/handlers/kubevirtConsolePlugin.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3766 Fix the flaky MediatedDevices e2e test
  controllers/alerts/reconciler.go
  controllers/alerts/secret.go
  hack/run-tests-in-container.sh
  tests/func-tests/golden_image_test.go
  tests/func-tests/mediateddevices_mediateddevice_test.go
  tests/func-tests/utils.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3782 memory overcommit: bump minimum to 10 to match KubeVirt
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  deploy/crds/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.17.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.17.0/manifests/hco00.crd.yaml
  docs/api.md
  tools/csv-merger/generated-crd.yaml
  tools/manifest-templator/generated-crd.yaml
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#3622 api: expose VideoConfig feature gate in HCO
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/handlers/kubevirt.go
  controllers/handlers/kubevirt_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.17.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.16.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.17.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  pkg/upgradepatch/hc.cr.json
  tests/func-tests/defaults_test.go
  tools/csv-merger/generated-crd.yaml
  tools/manifest-templator/generated-crd.yaml
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved
