Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2025-03, with the labels that each got.

#3317 [release-1.14] Require Bearer token for /metrics endpoint
  cmd/hyperconverged-cluster-operator/main.go
  cmd/hyperconverged-cluster-webhook/main.go
  controllers/alerts/metrics_test.go
  controllers/alerts/reconciler.go
  controllers/alerts/secret.go
  controllers/alerts/serviceMonitor.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  deploy/cluster_role.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.0/manifests/kubevirt-hyperconverged-operator.v1.14.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.0/manifests/kubevirt-hyperconverged-operator.v1.14.0.clusterserviceversion.yaml
  go.mod
  go.sum
  pkg/authorization/authorization_suite_test.go
  pkg/authorization/bearer_token.go
  pkg/authorization/bearer_token_test.go
  pkg/authorization/http.go
  pkg/components/components.go
  tests/func-tests/hco_prometheus_route.go
  vendor/github.com/golang-jwt/jwt/v5/.gitignore
  vendor/github.com/golang-jwt/jwt/v5/LICENSE
  vendor/github.com/golang-jwt/jwt/v5/MIGRATION_GUIDE.md
  vendor/github.com/golang-jwt/jwt/v5/README.md
  vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
  vendor/github.com/golang-jwt/jwt/v5/VERSION_HISTORY.md
  vendor/github.com/golang-jwt/jwt/v5/claims.go
  vendor/github.com/golang-jwt/jwt/v5/doc.go
  vendor/github.com/golang-jwt/jwt/v5/ecdsa.go
  vendor/github.com/golang-jwt/jwt/v5/ecdsa_utils.go
  vendor/github.com/golang-jwt/jwt/v5/ed25519.go
  vendor/github.com/golang-jwt/jwt/v5/ed25519_utils.go
  vendor/github.com/golang-jwt/jwt/v5/errors.go
  vendor/github.com/golang-jwt/jwt/v5/errors_go1_20.go
  vendor/github.com/golang-jwt/jwt/v5/errors_go_other.go
  vendor/github.com/golang-jwt/jwt/v5/hmac.go
  vendor/github.com/golang-jwt/jwt/v5/map_claims.go
  vendor/github.com/golang-jwt/jwt/v5/none.go
  vendor/github.com/golang-jwt/jwt/v5/parser.go
  vendor/github.com/golang-jwt/jwt/v5/parser_option.go
  vendor/github.com/golang-jwt/jwt/v5/registered_claims.go
  vendor/github.com/golang-jwt/jwt/v5/rsa.go
  vendor/github.com/golang-jwt/jwt/v5/rsa_pss.go
  vendor/github.com/golang-jwt/jwt/v5/rsa_utils.go
  vendor/github.com/golang-jwt/jwt/v5/signing_method.go
  vendor/github.com/golang-jwt/jwt/v5/staticcheck.conf
  vendor/github.com/golang-jwt/jwt/v5/token.go
  vendor/github.com/golang-jwt/jwt/v5/token_option.go
  vendor/github.com/golang-jwt/jwt/v5/types.go
  vendor/github.com/golang-jwt/jwt/v5/validator.go
  vendor/modules.txt
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#3316 Don't use the default SA in the artifact-server
  deploy/index-image/community-kubevirt-hyperconverged/1.15.0/manifests/kubevirt-hyperconverged-operator.v1.15.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.0/manifests/kubevirt-hyperconverged-operator.v1.15.0.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/service_account.yaml
  pkg/components/components.go
  tools/manifest-templator/manifest-templator.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#3323 [release-1.14] Small multi-arch build fixes
  hack/build-index-image.sh
  hack/build-push-multi-arch-images.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3324 [Release 1.14] Fix the publish github action
  .github/workflows/publish-community-operators.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3325 Fix the publish github action
  .github/workflows/publish-community-operators.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3326 Prepare version 1.14.1
  deploy/index-image/Dockerfile.bundle.ci-index-image-upgrade
  deploy/index-image/bundle.Dockerfile
  deploy/index-image/community-kubevirt-hyperconverged/1.14.1/manifests/application-aware-quota00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.1/manifests/cluster-network-addons00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.1/manifests/containerized-data-importer00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.1/manifests/hco00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.1/manifests/hostpath-provisioner00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.1/manifests/kubevirt-hyperconverged-operator.v1.14.1.clusterserviceversion.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.1/manifests/kubevirt00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.1/manifests/scheduling-scale-performance00.crd.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.14.1/metadata/annotations.yaml
  deploy/olm-catalog/Dockerfile.bundle.ci-index-image-upgrade
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.1/manifests/application-aware-quota00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.1/manifests/cluster-network-addons00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.1/manifests/containerized-data-importer00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.1/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.1/manifests/hostpath-provisioner00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.1/manifests/kubevirt-hyperconverged-operator.v1.14.1.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.1/manifests/kubevirt00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.1/manifests/scheduling-scale-performance00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.14.1/metadata/annotations.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/index-template-release.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/index-template-unstable.yaml
  deploy/operator.yaml
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#3327 KubeVirt default FG: Remove graduated network FGs
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/kubevirt.go
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#3332 [release-1.13] Remove old api version from the SSP CRD on upgrade
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/hyperconverged/testUtils_test.go
  hack/upgrade-test-operator-sdk.sh
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3328 Move the enableCommonBootImageImport feature gate to new field
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  assets/upgradePatches.json
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/imageStream.go
  controllers/operands/imageStream_test.go
  controllers/operands/ssp.go
  controllers/operands/ssp_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.15.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  pkg/upgradepatch/upgradePatches_test.go
  pkg/webhooks/validator/validator.go
  pkg/webhooks/validator/validator_test.go
  tests/func-tests/defaults_test.go
  tests/func-tests/golden_image_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3334 [release-1.14] Update assignee list of the bump bot action
  .github/workflows/release-bumper.yml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3341 KubeVirtCRModified e2e: Remove prometheus check for metric value
  tests/func-tests/monitoring_test.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#3352 Don't set the deprecated FGs in KV CR
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/operands/kubevirt.go
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#3354 fix pkg/upgradepatch/hc.cr.json
  pkg/upgradepatch/hc.cr.json
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3357 [Release 1.13] fix CVE-2025-30204
  go.mod
  vendor/modules.txt
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3356 [Release 1.14] Fix CVE-2025-30204
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v5/README.md
  vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
  vendor/github.com/golang-jwt/jwt/v5/parser.go
  vendor/github.com/golang-jwt/jwt/v5/token.go
  vendor/modules.txt
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#3360 Fix issue in upgrade tests
  .github/workflows/build-push-images.yaml
  Makefile
  hack/retag-multi-arch-images.sh
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3359 Move the `deployVmConsoleProxy` feature gate to new field
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  assets/upgradePatches.json
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/ssp.go
  controllers/operands/ssp_test.go
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.15.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.0/manifests/hco00.crd.yaml
  docs/api.md
  docs/cluster-configuration.md
  pkg/upgradepatch/hc.cr.json
  pkg/webhooks/validator/validator.go
  pkg/webhooks/validator/validator_test.go
  tests/func-tests/defaults_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3368 added mising " in a github action
  .github/workflows/build-push-images.yaml
Labels: release-note-none, size/XS, dco-signoff: yes

#3212 Remove passt network binding plugin Registration
  cmd/hyperconverged-cluster-operator/main.go
  controllers/operands/kubevirt.go
  controllers/operands/kubevirt_test.go
  deploy/images.csv
  deploy/images.env
  deploy/index-image/community-kubevirt-hyperconverged/1.15.0/manifests/kubevirt-hyperconverged-operator.v1.15.0.clusterserviceversion.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.15.0/manifests/kubevirt-hyperconverged-operator.v1.15.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/build-manifests.sh
  pkg/components/components.go
  pkg/util/consts.go
  pkg/util/util.go
  tools/csv-merger/csv-merger.go
  tools/manifest-templator/manifest-templator.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved
