Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2025-05, with the labels that each got.

#3512 Enable CDI WebhookPvcRendering feature gate by default
  controllers/operands/cdi.go
  controllers/operands/cdi_test.go
Labels: size/S, release-note, dco-signoff: yes, lgtm, approved

#3517 Add script to generate description for bump kubevirtci PRs
  hack/pr-descriptio-for-bump-kvci.sh
Labels: size/S, release-note-none, dco-signoff: yes

#3520 Fix script name
  hack/pr-description-for-bump-kvci.sh
Labels: release-note-none, size/XS, dco-signoff: yes

#3522 Use latest nightly CNAO for HCO nightly build
  automation/nightly/test-nightly-build.sh
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3518 Add PersistentVolumeFillingUp alert
  hack/prom-rule-ci/observability-prom-rules-tests.yaml
  pkg/monitoring/observability/rules/alerts/cluster_alerts.go
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#3528 Fix the unit test command in the nightly build
  automation/nightly/test-nightly-build.sh
Labels: release-note-none, size/XS, dco-signoff: yes

#3531 Move the nightly build images to quay.io/kubevirt
  automation/nightly/test-nightly-build.sh
Labels: release-note, size/XS, dco-signoff: yes

#3521 Add multi-arch annotation to DICT
  api/v1beta1/hyperconverged_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  assets/dataImportCronTemplates/dataImportCronTemplates.yaml
  config/crd/bases/hco.kubevirt.io_hyperconvergeds.yaml
  controllers/operands/ssp.go
  controllers/operands/ssp_test.go
  controllers/operands/testFiles/dataImportCronTemplates/dataImportCronTemplatesMultiArch.yaml
  deploy/crds/hco00.crd.yaml
  deploy/hco.cr.yaml
  deploy/index-image/community-kubevirt-hyperconverged/1.16.0/manifests/hco00.crd.yaml
  deploy/olm-catalog/community-kubevirt-hyperconverged/1.16.0/manifests/hco00.crd.yaml
  docs/api.md
  pkg/upgradepatch/hc.cr.json
  tests/func-tests/defaults_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3538 Split the high-availability logic from ClusterInfo, into the new nodeinfo package
  controllers/commontestutils/nodeinfomocks.go
  controllers/commontestutils/testUtils.go
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/nodes/nodes_controller.go
  controllers/nodes/nodes_controller_test.go
  controllers/operands/aaq_test.go
  controllers/operands/kubevirt.go
  controllers/operands/kubevirtConsolePlugin.go
  controllers/operands/kubevirtConsolePlugin_test.go
  controllers/operands/kubevirt_test.go
  pkg/internal/nodeinfo/high_availability.go
  pkg/internal/nodeinfo/high_availability_test.go
  pkg/internal/nodeinfo/node_suite_test.go
  pkg/internal/nodeinfo/nodeinfo.go
  pkg/nodeinfo/nodeinfo.go
  pkg/util/cluster.go
  pkg/util/cluster_test.go
Labels: size/XL, release-note-none, dco-signoff: yes, lgtm, approved
