Repository kubevirt/hyperconverged-cluster-operator, pull requests merged in 2025-01, with the labels that each got.

#3256 Improve the slack message style
  automation/hco-nightly-reporter/main.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3261 [Release 1.14] Add missing upgrade patch
  assets/upgradePatches.json
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3262 Func Test: Don't verify Operator Health Metric
  tests/func-tests/monitoring_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3265 Fix the override-bot
  .github/workflows/override-bot.yaml
  automation/override-bot/override-bot.py
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#3260 Cleanup upgrade code
  Makefile
  assets/upgradePatches.json
  cmd/hyperconverged-cluster-operator/main.go
  controllers/hyperconverged/crdsRemover.go
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/hyperconverged/hyperconverged_suite_test.go
  controllers/hyperconverged/upgradePatches.go
  go.mod
  pkg/upgradepatch/hc.cr.json
  pkg/upgradepatch/test-files/badJson.json
  pkg/upgradepatch/test-files/badObject1.json
  pkg/upgradepatch/test-files/badObject1m.json
  pkg/upgradepatch/test-files/badObject2.json
  pkg/upgradepatch/test-files/badObject2m.json
  pkg/upgradepatch/test-files/badObject3.json
  pkg/upgradepatch/test-files/badObject3m.json
  pkg/upgradepatch/test-files/badPatches1.json
  pkg/upgradepatch/test-files/badPatches2.json
  pkg/upgradepatch/test-files/badPatches3.json
  pkg/upgradepatch/test-files/badPatches4.json
  pkg/upgradepatch/test-files/badPatches5.json
  pkg/upgradepatch/test-files/badPatches6.json
  pkg/upgradepatch/test-files/badPatches7.json
  pkg/upgradepatch/test-files/badSemverRange.json
  pkg/upgradepatch/test-files/badSemverRangeOR.json
  pkg/upgradepatch/test-files/empty.json
  pkg/upgradepatch/test-files/upgradePatches.json
  pkg/upgradepatch/upgradePatches.go
  pkg/upgradepatch/upgradePatches_test.go
  tools/crwriter/crwriter.go
  tools/csv-merger/csv-merger.go
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#3269 Fix the override bot
  .github/workflows/override-bot.yaml
  automation/override-bot/override-bot.py
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3270 fix the component release bump bot
  .github/workflows/release-bumper.yml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3273 Bump golang.org/x/net to v0.34.0
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3272 Add observability controller alerts
  Makefile
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.defaults.go
  api/v1beta1/zz_generated.openapi.go
  cmd/hyperconverged-cluster-operator/main.go
  controllers/alerts/alerts.go
  controllers/alerts/metrics_test.go
  controllers/alerts/reconciler.go
  controllers/descheduler/descheduler_controller.go
  controllers/hyperconverged/hyperconverged_controller.go
  controllers/hyperconverged/hyperconverged_controller_test.go
  controllers/observability/alerts.go
  controllers/observability/alerts_test.go
  controllers/observability/observability_controller.go
  controllers/observability/observability_controller_test.go
  controllers/observability/observability_suite_test.go
  controllers/observability/pod_disruption_budget_at_limit.go
  controllers/operands/operandHandler.go
  hack/prom-rule-ci/hyperconverged-prom-rules-tests.yaml
  hack/prom-rule-ci/observability-prom-rules-tests.yaml
  hack/prom-rule-ci/rule-spec-dumper.go
  hack/prom-rule-ci/verify-rules.sh
  pkg/monitoring/hyperconverged/metrics/infrastructure_metrics.go
  pkg/monitoring/hyperconverged/metrics/metrics.go
  pkg/monitoring/hyperconverged/metrics/metrics_suite_test.go
  pkg/monitoring/hyperconverged/metrics/operator_metrics.go
  pkg/monitoring/hyperconverged/metrics/operator_metrics_test.go
  pkg/monitoring/hyperconverged/rules/alerts/alerts.go
  pkg/monitoring/hyperconverged/rules/alerts/health_alerts.go
  pkg/monitoring/hyperconverged/rules/alerts/operator_alerts.go
  pkg/monitoring/hyperconverged/rules/recordingrules/operator.go
  pkg/monitoring/hyperconverged/rules/recordingrules/recordingrules.go
  pkg/monitoring/hyperconverged/rules/rules.go
  pkg/monitoring/hyperconverged/rules/rules_test.go
  pkg/monitoring/observability/rules/alerts/alerts.go
  pkg/monitoring/observability/rules/alerts/cluster_alerts.go
  pkg/monitoring/observability/rules/rules.go
  pkg/monitoring/observability/rules/rules_test.go
  pkg/util/cluster.go
  tests/func-tests/monitoring_test.go
  tests/func-tests/observability_controller_test.go
  tools/metricsdocs/metricsdocs.go
  tools/prom-metrics-collector/metrics_json_generator.go
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved
